#!/usr/bin/env python3
"""
APIClaw Night Expansion - 05:00 Feb 23, 2026
Target: +1000 APIs from diverse sources
"""

import json
import re
from pathlib import Path
from datetime import datetime

REGISTRY_PATH = Path(__file__).parent.parent / "src" / "registry" / "apis.json"

def generate_id(name: str) -> str:
    clean = re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')
    return clean[:50]

def load_registry() -> dict:
    with open(REGISTRY_PATH, 'r') as f:
        return json.load(f)

def save_registry(registry: dict):
    with open(REGISTRY_PATH, 'w') as f:
        json.dump(registry, f, indent=2)

def get_existing_ids(registry: dict) -> set:
    return {api['id'] for api in registry['apis']}

# New API batches for Feb 23
NEW_APIS = [
    # Web3 & Crypto (50)
    {"name": "Alchemy", "desc": "Web3 development platform APIs", "category": "Blockchain", "url": "https://www.alchemy.com/sdk"},
    {"name": "QuickNode", "desc": "Blockchain infrastructure APIs", "category": "Blockchain", "url": "https://www.quicknode.com"},
    {"name": "Infura", "desc": "Ethereum and IPFS APIs", "category": "Blockchain", "url": "https://infura.io"},
    {"name": "Moralis", "desc": "Web3 development APIs", "category": "Blockchain", "url": "https://moralis.io"},
    {"name": "Thirdweb", "desc": "Web3 SDK and APIs", "category": "Blockchain", "url": "https://thirdweb.com"},
    {"name": "Chainlink", "desc": "Oracle network APIs", "category": "Blockchain", "url": "https://chain.link"},
    {"name": "The Graph", "desc": "GraphQL blockchain indexing", "category": "Blockchain", "url": "https://thegraph.com"},
    {"name": "Ankr", "desc": "Multi-chain RPC APIs", "category": "Blockchain", "url": "https://www.ankr.com"},
    {"name": "Pocket Network", "desc": "Decentralized RPC", "category": "Blockchain", "url": "https://pokt.network"},
    {"name": "Tenderly", "desc": "Smart contract simulation", "category": "Blockchain", "url": "https://tenderly.co"},
    {"name": "Bitquery", "desc": "Blockchain data APIs", "category": "Blockchain", "url": "https://bitquery.io"},
    {"name": "Nansen", "desc": "On-chain analytics", "category": "Blockchain", "url": "https://nansen.ai"},
    {"name": "Dune Analytics", "desc": "Blockchain data queries", "category": "Blockchain", "url": "https://dune.com"},
    {"name": "Covalent", "desc": "Unified blockchain data", "category": "Blockchain", "url": "https://www.covalenthq.com"},
    {"name": "Unmarshal", "desc": "Multi-chain data indexing", "category": "Blockchain", "url": "https://unmarshal.io"},
    {"name": "Transpose", "desc": "Blockchain SQL queries", "category": "Blockchain", "url": "https://transpose.io"},
    {"name": "Defined.fi", "desc": "DeFi analytics APIs", "category": "Blockchain", "url": "https://defined.fi"},
    {"name": "0x Protocol", "desc": "DEX aggregation API", "category": "Blockchain", "url": "https://0x.org"},
    {"name": "1inch", "desc": "DEX aggregator API", "category": "Blockchain", "url": "https://1inch.io"},
    {"name": "Paraswap", "desc": "DeFi middleware API", "category": "Blockchain", "url": "https://paraswap.io"},
    {"name": "Socket", "desc": "Cross-chain bridge API", "category": "Blockchain", "url": "https://socket.tech"},
    {"name": "LI.FI", "desc": "Multi-chain bridging", "category": "Blockchain", "url": "https://li.fi"},
    {"name": "Wormhole", "desc": "Cross-chain messaging", "category": "Blockchain", "url": "https://wormhole.com"},
    {"name": "LayerZero", "desc": "Omnichain protocol API", "category": "Blockchain", "url": "https://layerzero.network"},
    {"name": "Axelar", "desc": "Cross-chain communication", "category": "Blockchain", "url": "https://axelar.network"},
    {"name": "Across", "desc": "Bridge protocol API", "category": "Blockchain", "url": "https://across.to"},
    {"name": "Synapse", "desc": "Cross-chain liquidity", "category": "Blockchain", "url": "https://synapseprotocol.com"},
    {"name": "Hop Protocol", "desc": "L2 bridge API", "category": "Blockchain", "url": "https://hop.exchange"},
    {"name": "Stargate", "desc": "Native asset bridge", "category": "Blockchain", "url": "https://stargate.finance"},
    {"name": "Connext", "desc": "Crosschain transfer API", "category": "Blockchain", "url": "https://connext.network"},
    {"name": "OpenSea", "desc": "NFT marketplace API", "category": "Blockchain", "url": "https://opensea.io"},
    {"name": "Blur", "desc": "NFT trading API", "category": "Blockchain", "url": "https://blur.io"},
    {"name": "Reservoir", "desc": "NFT data and trading", "category": "Blockchain", "url": "https://reservoir.tools"},
    {"name": "Rarible", "desc": "NFT protocol API", "category": "Blockchain", "url": "https://rarible.com"},
    {"name": "Zora", "desc": "NFT protocol API", "category": "Blockchain", "url": "https://zora.co"},
    {"name": "Magic Eden", "desc": "Multi-chain NFT API", "category": "Blockchain", "url": "https://magiceden.io"},
    {"name": "Foundation", "desc": "NFT creator platform", "category": "Blockchain", "url": "https://foundation.app"},
    {"name": "Manifold", "desc": "Creator contracts API", "category": "Blockchain", "url": "https://manifold.xyz"},
    {"name": "Crossmint", "desc": "NFT payments API", "category": "Blockchain", "url": "https://crossmint.com"},
    {"name": "Paper", "desc": "NFT checkout API", "category": "Blockchain", "url": "https://withpaper.com"},
    {"name": "Arweave", "desc": "Permanent storage API", "category": "Storage", "url": "https://arweave.org"},
    {"name": "Filecoin", "desc": "Decentralized storage", "category": "Storage", "url": "https://filecoin.io"},
    {"name": "IPFS Pinata", "desc": "IPFS pinning service", "category": "Storage", "url": "https://pinata.cloud"},
    {"name": "NFT.Storage", "desc": "Free NFT storage", "category": "Storage", "url": "https://nft.storage"},
    {"name": "Web3.Storage", "desc": "Decentralized storage", "category": "Storage", "url": "https://web3.storage"},
    {"name": "Filebase", "desc": "Decentralized storage", "category": "Storage", "url": "https://filebase.com"},
    {"name": "Ceramic Network", "desc": "Decentralized data", "category": "Blockchain", "url": "https://ceramic.network"},
    {"name": "Lit Protocol", "desc": "Decentralized encryption", "category": "Blockchain", "url": "https://litprotocol.com"},
    {"name": "Spruce", "desc": "Decentralized identity", "category": "Blockchain", "url": "https://spruceid.com"},
    {"name": "ENS", "desc": "Ethereum Name Service", "category": "Blockchain", "url": "https://ens.domains"},
    
    # AI & ML Services (50)
    {"name": "Stability AI", "desc": "Image generation APIs", "category": "AI", "url": "https://stability.ai"},
    {"name": "Midjourney", "desc": "AI image generation", "category": "AI", "url": "https://midjourney.com"},
    {"name": "Leonardo AI", "desc": "AI image generation", "category": "AI", "url": "https://leonardo.ai"},
    {"name": "Ideogram", "desc": "AI text-to-image", "category": "AI", "url": "https://ideogram.ai"},
    {"name": "Playground AI", "desc": "AI image creation", "category": "AI", "url": "https://playgroundai.com"},
    {"name": "Clipdrop", "desc": "AI image editing", "category": "AI", "url": "https://clipdrop.co"},
    {"name": "Remove.bg", "desc": "Background removal API", "category": "AI", "url": "https://remove.bg"},
    {"name": "PhotoRoom", "desc": "AI photo editing", "category": "AI", "url": "https://photoroom.com"},
    {"name": "Picsart", "desc": "AI photo editing API", "category": "AI", "url": "https://picsart.com"},
    {"name": "Deep AI", "desc": "Various AI APIs", "category": "AI", "url": "https://deepai.org"},
    {"name": "Runway", "desc": "AI video generation", "category": "AI", "url": "https://runwayml.com"},
    {"name": "Pika", "desc": "AI video creation", "category": "AI", "url": "https://pika.art"},
    {"name": "Luma AI", "desc": "3D AI generation", "category": "AI", "url": "https://lumalabs.ai"},
    {"name": "Meshy", "desc": "3D model generation", "category": "AI", "url": "https://meshy.ai"},
    {"name": "Kaedim", "desc": "2D to 3D AI", "category": "AI", "url": "https://kaedim3d.com"},
    {"name": "Rodin", "desc": "3D avatar AI", "category": "AI", "url": "https://hyperhuman.deemos.com"},
    {"name": "Suno", "desc": "AI music generation", "category": "AI", "url": "https://suno.ai"},
    {"name": "Udio", "desc": "AI music creation", "category": "AI", "url": "https://udio.com"},
    {"name": "Mubert", "desc": "AI music API", "category": "AI", "url": "https://mubert.com"},
    {"name": "Soundraw", "desc": "AI music generation", "category": "AI", "url": "https://soundraw.io"},
    {"name": "Aiva", "desc": "AI composer", "category": "AI", "url": "https://aiva.ai"},
    {"name": "Boomy", "desc": "AI music maker", "category": "AI", "url": "https://boomy.com"},
    {"name": "Descript", "desc": "AI audio/video editing", "category": "AI", "url": "https://descript.com"},
    {"name": "Podcastle", "desc": "AI podcasting", "category": "AI", "url": "https://podcastle.ai"},
    {"name": "Riverside", "desc": "AI recording studio", "category": "AI", "url": "https://riverside.fm"},
    {"name": "Resemble AI", "desc": "Voice cloning API", "category": "AI", "url": "https://resemble.ai"},
    {"name": "PlayHT", "desc": "AI voice generation", "category": "AI", "url": "https://play.ht"},
    {"name": "Speechify", "desc": "Text-to-speech API", "category": "AI", "url": "https://speechify.com"},
    {"name": "Murf", "desc": "AI voiceover", "category": "AI", "url": "https://murf.ai"},
    {"name": "WellSaid", "desc": "AI voice generation", "category": "AI", "url": "https://wellsaidlabs.com"},
    {"name": "Synthesia", "desc": "AI video avatars", "category": "AI", "url": "https://synthesia.io"},
    {"name": "HeyGen", "desc": "AI video generation", "category": "AI", "url": "https://heygen.com"},
    {"name": "Colossyan", "desc": "AI video creation", "category": "AI", "url": "https://colossyan.com"},
    {"name": "Hour One", "desc": "AI video synthesis", "category": "AI", "url": "https://hourone.ai"},
    {"name": "D-ID", "desc": "AI video and faces", "category": "AI", "url": "https://d-id.com"},
    {"name": "Tavus", "desc": "Personalized AI video", "category": "AI", "url": "https://tavus.io"},
    {"name": "Deepgram", "desc": "Speech recognition API", "category": "AI", "url": "https://deepgram.com"},
    {"name": "AssemblyAI", "desc": "Speech-to-text API", "category": "AI", "url": "https://assemblyai.com"},
    {"name": "Speechmatics", "desc": "Speech recognition", "category": "AI", "url": "https://speechmatics.com"},
    {"name": "Rev AI", "desc": "Transcription API", "category": "AI", "url": "https://rev.ai"},
    {"name": "Gladia", "desc": "Audio transcription", "category": "AI", "url": "https://gladia.io"},
    {"name": "Cohere", "desc": "Enterprise NLP API", "category": "AI", "url": "https://cohere.ai"},
    {"name": "AI21 Labs", "desc": "Language models API", "category": "AI", "url": "https://ai21.com"},
    {"name": "Aleph Alpha", "desc": "European AI models", "category": "AI", "url": "https://aleph-alpha.com"},
    {"name": "Writer", "desc": "Enterprise LLM API", "category": "AI", "url": "https://writer.com"},
    {"name": "Jasper", "desc": "AI content API", "category": "AI", "url": "https://jasper.ai"},
    {"name": "Copy.ai", "desc": "AI copywriting", "category": "AI", "url": "https://copy.ai"},
    {"name": "Writesonic", "desc": "AI writing API", "category": "AI", "url": "https://writesonic.com"},
    {"name": "Rytr", "desc": "AI writing assistant", "category": "AI", "url": "https://rytr.me"},
    {"name": "Wordtune", "desc": "AI writing companion", "category": "AI", "url": "https://wordtune.com"},

    # Developer Tools (50)
    {"name": "Supabase", "desc": "Backend as a service", "category": "Backend", "url": "https://supabase.com"},
    {"name": "Planetscale", "desc": "Serverless MySQL", "category": "Database", "url": "https://planetscale.com"},
    {"name": "Neon", "desc": "Serverless Postgres", "category": "Database", "url": "https://neon.tech"},
    {"name": "Turso", "desc": "Edge database", "category": "Database", "url": "https://turso.tech"},
    {"name": "Xata", "desc": "Serverless database", "category": "Database", "url": "https://xata.io"},
    {"name": "Upstash", "desc": "Serverless Redis/Kafka", "category": "Database", "url": "https://upstash.com"},
    {"name": "Fauna", "desc": "Distributed database", "category": "Database", "url": "https://fauna.com"},
    {"name": "CockroachDB", "desc": "Distributed SQL", "category": "Database", "url": "https://cockroachlabs.com"},
    {"name": "Timescale", "desc": "Time-series database", "category": "Database", "url": "https://timescale.com"},
    {"name": "InfluxDB", "desc": "Time-series platform", "category": "Database", "url": "https://influxdata.com"},
    {"name": "Questdb", "desc": "Fast time-series", "category": "Database", "url": "https://questdb.io"},
    {"name": "SingleStore", "desc": "Real-time database", "category": "Database", "url": "https://singlestore.com"},
    {"name": "Clickhouse", "desc": "OLAP database", "category": "Database", "url": "https://clickhouse.com"},
    {"name": "Materialize", "desc": "Streaming SQL", "category": "Database", "url": "https://materialize.com"},
    {"name": "Prisma", "desc": "ORM and database tools", "category": "Database", "url": "https://prisma.io"},
    {"name": "Drizzle", "desc": "TypeScript ORM", "category": "Database", "url": "https://drizzle.team"},
    {"name": "EdgeDB", "desc": "Graph-relational database", "category": "Database", "url": "https://edgedb.com"},
    {"name": "SurrealDB", "desc": "Multi-model database", "category": "Database", "url": "https://surrealdb.com"},
    {"name": "Dgraph", "desc": "Graph database", "category": "Database", "url": "https://dgraph.io"},
    {"name": "Neo4j", "desc": "Graph database", "category": "Database", "url": "https://neo4j.com"},
    {"name": "TigerGraph", "desc": "Graph analytics", "category": "Database", "url": "https://tigergraph.com"},
    {"name": "ArangoDB", "desc": "Multi-model database", "category": "Database", "url": "https://arangodb.com"},
    {"name": "Couchbase", "desc": "NoSQL database", "category": "Database", "url": "https://couchbase.com"},
    {"name": "ScyllaDB", "desc": "NoSQL database", "category": "Database", "url": "https://scylladb.com"},
    {"name": "Yugabyte", "desc": "Distributed SQL", "category": "Database", "url": "https://yugabyte.com"},
    {"name": "Deno Deploy", "desc": "Edge functions", "category": "Hosting", "url": "https://deno.com/deploy"},
    {"name": "Bun", "desc": "JavaScript runtime", "category": "Runtime", "url": "https://bun.sh"},
    {"name": "Netlify", "desc": "Jamstack hosting", "category": "Hosting", "url": "https://netlify.com"},
    {"name": "Railway", "desc": "Infrastructure platform", "category": "Hosting", "url": "https://railway.app"},
    {"name": "Render", "desc": "Cloud application platform", "category": "Hosting", "url": "https://render.com"},
    {"name": "Fly.io", "desc": "Global application platform", "category": "Hosting", "url": "https://fly.io"},
    {"name": "Modal", "desc": "Serverless data infra", "category": "Compute", "url": "https://modal.com"},
    {"name": "Val Town", "desc": "Social scripting", "category": "Compute", "url": "https://val.town"},
    {"name": "Replit", "desc": "Development platform", "category": "Development", "url": "https://replit.com"},
    {"name": "Gitpod", "desc": "Cloud development", "category": "Development", "url": "https://gitpod.io"},
    {"name": "Codespaces", "desc": "GitHub cloud IDE", "category": "Development", "url": "https://github.com/features/codespaces"},
    {"name": "StackBlitz", "desc": "In-browser IDE", "category": "Development", "url": "https://stackblitz.com"},
    {"name": "CodeSandbox", "desc": "Cloud development", "category": "Development", "url": "https://codesandbox.io"},
    {"name": "Glitch", "desc": "Web app platform", "category": "Development", "url": "https://glitch.com"},
    {"name": "Temporal", "desc": "Workflow orchestration", "category": "Workflow", "url": "https://temporal.io"},
    {"name": "Inngest", "desc": "Event-driven functions", "category": "Workflow", "url": "https://inngest.com"},
    {"name": "Trigger.dev", "desc": "Background jobs", "category": "Workflow", "url": "https://trigger.dev"},
    {"name": "QStash", "desc": "Message queue", "category": "Queue", "url": "https://upstash.com/qstash"},
    {"name": "Zeplo", "desc": "Request queue", "category": "Queue", "url": "https://zeplo.io"},
    {"name": "Knock", "desc": "Notifications API", "category": "Communication", "url": "https://knock.app"},
    {"name": "Novu", "desc": "Notifications infra", "category": "Communication", "url": "https://novu.co"},
    {"name": "Courier", "desc": "Notifications API", "category": "Communication", "url": "https://courier.com"},
    {"name": "OneSignal", "desc": "Push notifications", "category": "Communication", "url": "https://onesignal.com"},
    {"name": "Pusher", "desc": "Realtime APIs", "category": "Communication", "url": "https://pusher.com"},
    {"name": "Ably", "desc": "Realtime messaging", "category": "Communication", "url": "https://ably.com"},

    # E-commerce & Payments (50)
    {"name": "Shopify", "desc": "E-commerce platform API", "category": "E-commerce", "url": "https://shopify.dev"},
    {"name": "BigCommerce", "desc": "E-commerce API", "category": "E-commerce", "url": "https://developer.bigcommerce.com"},
    {"name": "Magento", "desc": "E-commerce platform", "category": "E-commerce", "url": "https://devdocs.magento.com"},
    {"name": "WooCommerce", "desc": "WordPress commerce", "category": "E-commerce", "url": "https://woocommerce.com"},
    {"name": "Medusa", "desc": "Open source commerce", "category": "E-commerce", "url": "https://medusajs.com"},
    {"name": "Saleor", "desc": "GraphQL commerce", "category": "E-commerce", "url": "https://saleor.io"},
    {"name": "Vendure", "desc": "Headless commerce", "category": "E-commerce", "url": "https://vendure.io"},
    {"name": "Commerce.js", "desc": "Headless commerce API", "category": "E-commerce", "url": "https://commercejs.com"},
    {"name": "Swell", "desc": "Headless e-commerce", "category": "E-commerce", "url": "https://swell.is"},
    {"name": "Crystallize", "desc": "Headless commerce", "category": "E-commerce", "url": "https://crystallize.com"},
    {"name": "Bold Commerce", "desc": "Checkout and subscriptions", "category": "E-commerce", "url": "https://boldcommerce.com"},
    {"name": "Nacelle", "desc": "Composable commerce", "category": "E-commerce", "url": "https://nacelle.com"},
    {"name": "Elastic Path", "desc": "Composable commerce", "category": "E-commerce", "url": "https://elasticpath.com"},
    {"name": "Commercetools", "desc": "Headless commerce", "category": "E-commerce", "url": "https://commercetools.com"},
    {"name": "Snipcart", "desc": "Shopping cart API", "category": "E-commerce", "url": "https://snipcart.com"},
    {"name": "Paddle", "desc": "SaaS payments", "category": "Payment", "url": "https://paddle.com"},
    {"name": "Lemon Squeezy", "desc": "Digital products", "category": "Payment", "url": "https://lemonsqueezy.com"},
    {"name": "Gumroad", "desc": "Creator commerce", "category": "Payment", "url": "https://gumroad.com"},
    {"name": "Patreon", "desc": "Membership platform", "category": "Payment", "url": "https://patreon.com"},
    {"name": "Ko-fi", "desc": "Creator payments", "category": "Payment", "url": "https://ko-fi.com"},
    {"name": "Buy Me a Coffee", "desc": "Creator support", "category": "Payment", "url": "https://buymeacoffee.com"},
    {"name": "Chargebee", "desc": "Subscription billing", "category": "Payment", "url": "https://chargebee.com"},
    {"name": "Recurly", "desc": "Subscription management", "category": "Payment", "url": "https://recurly.com"},
    {"name": "Zuora", "desc": "Subscription platform", "category": "Payment", "url": "https://zuora.com"},
    {"name": "RevenueCat", "desc": "Mobile subscriptions", "category": "Payment", "url": "https://revenuecat.com"},
    {"name": "Adapty", "desc": "Mobile subscriptions", "category": "Payment", "url": "https://adapty.io"},
    {"name": "Superwall", "desc": "Paywall SDK", "category": "Payment", "url": "https://superwall.com"},
    {"name": "Qonversion", "desc": "Mobile subscription", "category": "Payment", "url": "https://qonversion.io"},
    {"name": "Braintree", "desc": "Payment gateway", "category": "Payment", "url": "https://braintreepayments.com"},
    {"name": "Adyen", "desc": "Payment platform", "category": "Payment", "url": "https://adyen.com"},
    {"name": "Square", "desc": "Payment processing", "category": "Payment", "url": "https://squareup.com"},
    {"name": "PayPal", "desc": "Payment platform", "category": "Payment", "url": "https://paypal.com"},
    {"name": "Klarna", "desc": "Buy now pay later", "category": "Payment", "url": "https://klarna.com"},
    {"name": "Afterpay", "desc": "Buy now pay later", "category": "Payment", "url": "https://afterpay.com"},
    {"name": "Affirm", "desc": "Buy now pay later", "category": "Payment", "url": "https://affirm.com"},
    {"name": "Zip", "desc": "Buy now pay later", "category": "Payment", "url": "https://zip.co"},
    {"name": "Sezzle", "desc": "Buy now pay later", "category": "Payment", "url": "https://sezzle.com"},
    {"name": "Splitit", "desc": "Payment installments", "category": "Payment", "url": "https://splitit.com"},
    {"name": "Bolt", "desc": "One-click checkout", "category": "Payment", "url": "https://bolt.com"},
    {"name": "Fast", "desc": "Fast checkout (Deprecated)", "category": "Payment", "url": "https://fast.co"},
    {"name": "Shop Pay", "desc": "Shopify checkout", "category": "Payment", "url": "https://shop.app/shop-pay"},
    {"name": "Wyre", "desc": "Crypto payments", "category": "Payment", "url": "https://sendwyre.com"},
    {"name": "MoonPay", "desc": "Crypto onramp", "category": "Payment", "url": "https://moonpay.com"},
    {"name": "Transak", "desc": "Crypto payments", "category": "Payment", "url": "https://transak.com"},
    {"name": "Ramp Network", "desc": "Crypto onramp", "category": "Payment", "url": "https://ramp.network"},
    {"name": "Sardine", "desc": "Crypto fraud prevention", "category": "Payment", "url": "https://sardine.ai"},
    {"name": "Circle", "desc": "Crypto payments", "category": "Payment", "url": "https://circle.com"},
    {"name": "Fireblocks", "desc": "Digital asset custody", "category": "Payment", "url": "https://fireblocks.com"},
    {"name": "Copper", "desc": "Crypto custody", "category": "Payment", "url": "https://copper.co"},
    {"name": "BitGo", "desc": "Digital asset custody", "category": "Payment", "url": "https://bitgo.com"},

    # Security & Identity (50)
    {"name": "Auth0", "desc": "Identity platform", "category": "Auth", "url": "https://auth0.com"},
    {"name": "Okta", "desc": "Identity management", "category": "Auth", "url": "https://okta.com"},
    {"name": "Clerk", "desc": "Authentication API", "category": "Auth", "url": "https://clerk.com"},
    {"name": "WorkOS", "desc": "Enterprise SSO", "category": "Auth", "url": "https://workos.com"},
    {"name": "Stytch", "desc": "Passwordless auth", "category": "Auth", "url": "https://stytch.com"},
    {"name": "Magic", "desc": "Web3 auth", "category": "Auth", "url": "https://magic.link"},
    {"name": "Privy", "desc": "Web3 authentication", "category": "Auth", "url": "https://privy.io"},
    {"name": "Dynamic", "desc": "Web3 auth", "category": "Auth", "url": "https://dynamic.xyz"},
    {"name": "Thirdweb Auth", "desc": "Web3 authentication", "category": "Auth", "url": "https://thirdweb.com/auth"},
    {"name": "Web3Auth", "desc": "Wallet auth", "category": "Auth", "url": "https://web3auth.io"},
    {"name": "Passage", "desc": "Passkey authentication", "category": "Auth", "url": "https://passage.id"},
    {"name": "Hanko", "desc": "Passkeys and auth", "category": "Auth", "url": "https://hanko.io"},
    {"name": "Descope", "desc": "Drag-and-drop auth", "category": "Auth", "url": "https://descope.com"},
    {"name": "FusionAuth", "desc": "Auth for developers", "category": "Auth", "url": "https://fusionauth.io"},
    {"name": "Keycloak", "desc": "Open source IAM", "category": "Auth", "url": "https://keycloak.org"},
    {"name": "SuperTokens", "desc": "Open source auth", "category": "Auth", "url": "https://supertokens.com"},
    {"name": "Ory", "desc": "Identity infrastructure", "category": "Auth", "url": "https://ory.sh"},
    {"name": "Frontegg", "desc": "User management", "category": "Auth", "url": "https://frontegg.com"},
    {"name": "PropelAuth", "desc": "B2B authentication", "category": "Auth", "url": "https://propelauth.com"},
    {"name": "Kinde", "desc": "Modern auth", "category": "Auth", "url": "https://kinde.com"},
    {"name": "Snyk", "desc": "Security scanning", "category": "Security", "url": "https://snyk.io"},
    {"name": "SonarCloud", "desc": "Code analysis", "category": "Security", "url": "https://sonarcloud.io"},
    {"name": "Semgrep", "desc": "Code scanning", "category": "Security", "url": "https://semgrep.dev"},
    {"name": "Checkmarx", "desc": "AppSec platform", "category": "Security", "url": "https://checkmarx.com"},
    {"name": "Veracode", "desc": "Application security", "category": "Security", "url": "https://veracode.com"},
    {"name": "Fortify", "desc": "AppSec testing", "category": "Security", "url": "https://microfocus.com/fortify"},
    {"name": "WhiteSource", "desc": "Open source security", "category": "Security", "url": "https://whitesourcesoftware.com"},
    {"name": "Socket", "desc": "Supply chain security", "category": "Security", "url": "https://socket.dev"},
    {"name": "Dependabot", "desc": "Dependency updates", "category": "Security", "url": "https://github.com/dependabot"},
    {"name": "Renovate", "desc": "Dependency updates", "category": "Security", "url": "https://renovatebot.com"},
    {"name": "GitGuardian", "desc": "Secrets detection", "category": "Security", "url": "https://gitguardian.com"},
    {"name": "TruffleHog", "desc": "Secrets scanning", "category": "Security", "url": "https://trufflesecurity.com"},
    {"name": "HashiCorp Vault", "desc": "Secrets management", "category": "Security", "url": "https://hashicorp.com/vault"},
    {"name": "Doppler", "desc": "Secrets management", "category": "Security", "url": "https://doppler.com"},
    {"name": "Infisical", "desc": "Secrets management", "category": "Security", "url": "https://infisical.com"},
    {"name": "1Password Secrets", "desc": "Secrets automation", "category": "Security", "url": "https://1password.com/secrets"},
    {"name": "Akeyless", "desc": "Secrets management", "category": "Security", "url": "https://akeyless.io"},
    {"name": "CyberArk", "desc": "Privileged access", "category": "Security", "url": "https://cyberark.com"},
    {"name": "BeyondTrust", "desc": "Privileged access", "category": "Security", "url": "https://beyondtrust.com"},
    {"name": "Delinea", "desc": "PAM solutions", "category": "Security", "url": "https://delinea.com"},
    {"name": "Cloudflare", "desc": "Security and CDN", "category": "Security", "url": "https://cloudflare.com"},
    {"name": "Fastly", "desc": "Edge cloud platform", "category": "Security", "url": "https://fastly.com"},
    {"name": "Akamai", "desc": "CDN and security", "category": "Security", "url": "https://akamai.com"},
    {"name": "Imperva", "desc": "Web security", "category": "Security", "url": "https://imperva.com"},
    {"name": "Sucuri", "desc": "Website security", "category": "Security", "url": "https://sucuri.net"},
    {"name": "StackHawk", "desc": "DAST security testing", "category": "Security", "url": "https://stackhawk.com"},
    {"name": "Probely", "desc": "Web vulnerability scanner", "category": "Security", "url": "https://probely.com"},
    {"name": "Intruder", "desc": "Vulnerability scanning", "category": "Security", "url": "https://intruder.io"},
    {"name": "Detectify", "desc": "Surface monitoring", "category": "Security", "url": "https://detectify.com"},
    {"name": "Pentest-Tools", "desc": "Penetration testing", "category": "Security", "url": "https://pentest-tools.com"},

    # Analytics & Monitoring (50)
    {"name": "Mixpanel", "desc": "Product analytics", "category": "Analytics", "url": "https://mixpanel.com"},
    {"name": "Amplitude", "desc": "Product analytics", "category": "Analytics", "url": "https://amplitude.com"},
    {"name": "Heap", "desc": "Digital insights", "category": "Analytics", "url": "https://heap.io"},
    {"name": "PostHog", "desc": "Product analytics", "category": "Analytics", "url": "https://posthog.com"},
    {"name": "Plausible", "desc": "Privacy-friendly analytics", "category": "Analytics", "url": "https://plausible.io"},
    {"name": "Fathom", "desc": "Simple analytics", "category": "Analytics", "url": "https://usefathom.com"},
    {"name": "Simple Analytics", "desc": "Privacy analytics", "category": "Analytics", "url": "https://simpleanalytics.com"},
    {"name": "Pirsch", "desc": "Privacy analytics", "category": "Analytics", "url": "https://pirsch.io"},
    {"name": "Umami", "desc": "Open source analytics", "category": "Analytics", "url": "https://umami.is"},
    {"name": "Matomo", "desc": "Web analytics", "category": "Analytics", "url": "https://matomo.org"},
    {"name": "Pendo", "desc": "Product experience", "category": "Analytics", "url": "https://pendo.io"},
    {"name": "FullStory", "desc": "Digital experience", "category": "Analytics", "url": "https://fullstory.com"},
    {"name": "Hotjar", "desc": "Behavior analytics", "category": "Analytics", "url": "https://hotjar.com"},
    {"name": "Smartlook", "desc": "User behavior", "category": "Analytics", "url": "https://smartlook.com"},
    {"name": "Lucky Orange", "desc": "Conversion optimization", "category": "Analytics", "url": "https://luckyorange.com"},
    {"name": "Mouseflow", "desc": "Session replay", "category": "Analytics", "url": "https://mouseflow.com"},
    {"name": "LogRocket", "desc": "Session replay", "category": "Analytics", "url": "https://logrocket.com"},
    {"name": "Datadog", "desc": "Observability platform", "category": "Monitoring", "url": "https://datadoghq.com"},
    {"name": "New Relic", "desc": "Observability platform", "category": "Monitoring", "url": "https://newrelic.com"},
    {"name": "Dynatrace", "desc": "Software intelligence", "category": "Monitoring", "url": "https://dynatrace.com"},
    {"name": "Splunk", "desc": "Data platform", "category": "Monitoring", "url": "https://splunk.com"},
    {"name": "Elastic", "desc": "Search and observability", "category": "Monitoring", "url": "https://elastic.co"},
    {"name": "Grafana", "desc": "Observability platform", "category": "Monitoring", "url": "https://grafana.com"},
    {"name": "Prometheus", "desc": "Monitoring system", "category": "Monitoring", "url": "https://prometheus.io"},
    {"name": "Honeycomb", "desc": "Observability platform", "category": "Monitoring", "url": "https://honeycomb.io"},
    {"name": "Lightstep", "desc": "Observability", "category": "Monitoring", "url": "https://lightstep.com"},
    {"name": "Axiom", "desc": "Log management", "category": "Monitoring", "url": "https://axiom.co"},
    {"name": "Baselime", "desc": "Cloud observability", "category": "Monitoring", "url": "https://baselime.io"},
    {"name": "Sentry", "desc": "Error tracking", "category": "Monitoring", "url": "https://sentry.io"},
    {"name": "Bugsnag", "desc": "Error monitoring", "category": "Monitoring", "url": "https://bugsnag.com"},
    {"name": "Rollbar", "desc": "Error monitoring", "category": "Monitoring", "url": "https://rollbar.com"},
    {"name": "Raygun", "desc": "Error and performance", "category": "Monitoring", "url": "https://raygun.com"},
    {"name": "Airbrake", "desc": "Error monitoring", "category": "Monitoring", "url": "https://airbrake.io"},
    {"name": "TrackJS", "desc": "JavaScript errors", "category": "Monitoring", "url": "https://trackjs.com"},
    {"name": "Checkly", "desc": "Synthetic monitoring", "category": "Monitoring", "url": "https://checklyhq.com"},
    {"name": "Better Uptime", "desc": "Uptime monitoring", "category": "Monitoring", "url": "https://betteruptime.com"},
    {"name": "Uptime Robot", "desc": "Uptime monitoring", "category": "Monitoring", "url": "https://uptimerobot.com"},
    {"name": "Pingdom", "desc": "Website monitoring", "category": "Monitoring", "url": "https://pingdom.com"},
    {"name": "StatusCake", "desc": "Uptime monitoring", "category": "Monitoring", "url": "https://statuscake.com"},
    {"name": "Uptrends", "desc": "Website monitoring", "category": "Monitoring", "url": "https://uptrends.com"},
    {"name": "Site24x7", "desc": "IT monitoring", "category": "Monitoring", "url": "https://site24x7.com"},
    {"name": "Cronitor", "desc": "Cron monitoring", "category": "Monitoring", "url": "https://cronitor.io"},
    {"name": "Healthchecks", "desc": "Cron job monitoring", "category": "Monitoring", "url": "https://healthchecks.io"},
    {"name": "Instana", "desc": "APM platform", "category": "Monitoring", "url": "https://instana.com"},
    {"name": "AppDynamics", "desc": "APM platform", "category": "Monitoring", "url": "https://appdynamics.com"},
    {"name": "SpeedCurve", "desc": "Performance monitoring", "category": "Monitoring", "url": "https://speedcurve.com"},
    {"name": "Calibre", "desc": "Web performance", "category": "Monitoring", "url": "https://calibreapp.com"},
    {"name": "DebugBear", "desc": "Performance monitoring", "category": "Monitoring", "url": "https://debugbear.com"},
    {"name": "Treo", "desc": "Core Web Vitals", "category": "Monitoring", "url": "https://treo.sh"},
    {"name": "Request Metrics", "desc": "Real user monitoring", "category": "Monitoring", "url": "https://requestmetrics.com"},

    # Marketing & CRM (50)
    {"name": "HubSpot", "desc": "CRM and marketing", "category": "CRM", "url": "https://hubspot.com"},
    {"name": "Salesforce", "desc": "CRM platform", "category": "CRM", "url": "https://salesforce.com"},
    {"name": "Pipedrive", "desc": "Sales CRM", "category": "CRM", "url": "https://pipedrive.com"},
    {"name": "Close", "desc": "Sales CRM", "category": "CRM", "url": "https://close.com"},
    {"name": "Freshsales", "desc": "CRM platform", "category": "CRM", "url": "https://freshworks.com/crm"},
    {"name": "Copper", "desc": "CRM for Google", "category": "CRM", "url": "https://copper.com"},
    {"name": "Zoho CRM", "desc": "CRM platform", "category": "CRM", "url": "https://zoho.com/crm"},
    {"name": "Monday CRM", "desc": "Sales CRM", "category": "CRM", "url": "https://monday.com/crm"},
    {"name": "Attio", "desc": "Modern CRM", "category": "CRM", "url": "https://attio.com"},
    {"name": "Folk", "desc": "Relationship CRM", "category": "CRM", "url": "https://folk.app"},
    {"name": "Clay", "desc": "Data enrichment", "category": "Sales", "url": "https://clay.com"},
    {"name": "Apollo", "desc": "Sales intelligence", "category": "Sales", "url": "https://apollo.io"},
    {"name": "ZoomInfo", "desc": "B2B data", "category": "Sales", "url": "https://zoominfo.com"},
    {"name": "Clearbit", "desc": "Data enrichment", "category": "Sales", "url": "https://clearbit.com"},
    {"name": "Lusha", "desc": "Contact data", "category": "Sales", "url": "https://lusha.com"},
    {"name": "Hunter", "desc": "Email finder", "category": "Sales", "url": "https://hunter.io"},
    {"name": "Snov.io", "desc": "Sales automation", "category": "Sales", "url": "https://snov.io"},
    {"name": "Lemlist", "desc": "Cold outreach", "category": "Sales", "url": "https://lemlist.com"},
    {"name": "Instantly", "desc": "Email outreach", "category": "Sales", "url": "https://instantly.ai"},
    {"name": "Smartlead", "desc": "Email outreach", "category": "Sales", "url": "https://smartlead.ai"},
    {"name": "Mailchimp", "desc": "Email marketing", "category": "Marketing", "url": "https://mailchimp.com"},
    {"name": "Klaviyo", "desc": "E-commerce marketing", "category": "Marketing", "url": "https://klaviyo.com"},
    {"name": "Brevo", "desc": "Marketing platform", "category": "Marketing", "url": "https://brevo.com"},
    {"name": "ConvertKit", "desc": "Creator marketing", "category": "Marketing", "url": "https://convertkit.com"},
    {"name": "Beehiiv", "desc": "Newsletter platform", "category": "Marketing", "url": "https://beehiiv.com"},
    {"name": "Substack", "desc": "Newsletter platform", "category": "Marketing", "url": "https://substack.com"},
    {"name": "Buttondown", "desc": "Newsletter tool", "category": "Marketing", "url": "https://buttondown.email"},
    {"name": "Ghost", "desc": "Publishing platform", "category": "Marketing", "url": "https://ghost.org"},
    {"name": "ActiveCampaign", "desc": "Marketing automation", "category": "Marketing", "url": "https://activecampaign.com"},
    {"name": "Drip", "desc": "E-commerce CRM", "category": "Marketing", "url": "https://drip.com"},
    {"name": "Customer.io", "desc": "Messaging platform", "category": "Marketing", "url": "https://customer.io"},
    {"name": "Iterable", "desc": "Cross-channel marketing", "category": "Marketing", "url": "https://iterable.com"},
    {"name": "Braze", "desc": "Customer engagement", "category": "Marketing", "url": "https://braze.com"},
    {"name": "OneSignal", "desc": "Messaging platform", "category": "Marketing", "url": "https://onesignal.com"},
    {"name": "Leanplum", "desc": "Mobile engagement", "category": "Marketing", "url": "https://leanplum.com"},
    {"name": "CleverTap", "desc": "Customer engagement", "category": "Marketing", "url": "https://clevertap.com"},
    {"name": "MoEngage", "desc": "Customer engagement", "category": "Marketing", "url": "https://moengage.com"},
    {"name": "WebEngage", "desc": "Marketing automation", "category": "Marketing", "url": "https://webengage.com"},
    {"name": "Insider", "desc": "Growth management", "category": "Marketing", "url": "https://useinsider.com"},
    {"name": "Segment", "desc": "Customer data", "category": "Data", "url": "https://segment.com"},
    {"name": "RudderStack", "desc": "Customer data", "category": "Data", "url": "https://rudderstack.com"},
    {"name": "mParticle", "desc": "Customer data", "category": "Data", "url": "https://mparticle.com"},
    {"name": "Freshpaint", "desc": "Data collection", "category": "Data", "url": "https://freshpaint.io"},
    {"name": "Jitsu", "desc": "Data collection", "category": "Data", "url": "https://jitsu.com"},
    {"name": "Hightouch", "desc": "Reverse ETL", "category": "Data", "url": "https://hightouch.com"},
    {"name": "Census", "desc": "Reverse ETL", "category": "Data", "url": "https://getcensus.com"},
    {"name": "Fivetran", "desc": "Data integration", "category": "Data", "url": "https://fivetran.com"},
    {"name": "Airbyte", "desc": "Data integration", "category": "Data", "url": "https://airbyte.com"},
    {"name": "Stitch", "desc": "Data pipeline", "category": "Data", "url": "https://stitchdata.com"},
    {"name": "dbt", "desc": "Data transformation", "category": "Data", "url": "https://getdbt.com"},

    # Collaboration & Productivity (50)
    {"name": "Notion", "desc": "All-in-one workspace", "category": "Productivity", "url": "https://notion.so"},
    {"name": "Coda", "desc": "Doc collaboration", "category": "Productivity", "url": "https://coda.io"},
    {"name": "Airtable", "desc": "Low-code database", "category": "Productivity", "url": "https://airtable.com"},
    {"name": "ClickUp", "desc": "Project management", "category": "Productivity", "url": "https://clickup.com"},
    {"name": "Monday.com", "desc": "Work OS", "category": "Productivity", "url": "https://monday.com"},
    {"name": "Asana", "desc": "Work management", "category": "Productivity", "url": "https://asana.com"},
    {"name": "Linear", "desc": "Issue tracking", "category": "Productivity", "url": "https://linear.app"},
    {"name": "Jira", "desc": "Project tracking", "category": "Productivity", "url": "https://atlassian.com/jira"},
    {"name": "Height", "desc": "Project management", "category": "Productivity", "url": "https://height.app"},
    {"name": "Plane", "desc": "Open source Jira", "category": "Productivity", "url": "https://plane.so"},
    {"name": "Shortcut", "desc": "Project management", "category": "Productivity", "url": "https://shortcut.com"},
    {"name": "Basecamp", "desc": "Project management", "category": "Productivity", "url": "https://basecamp.com"},
    {"name": "Trello", "desc": "Kanban boards", "category": "Productivity", "url": "https://trello.com"},
    {"name": "Todoist", "desc": "Task management", "category": "Productivity", "url": "https://todoist.com"},
    {"name": "Things", "desc": "Task manager", "category": "Productivity", "url": "https://culturedcode.com/things"},
    {"name": "Slack", "desc": "Team messaging", "category": "Communication", "url": "https://slack.com"},
    {"name": "Discord", "desc": "Community platform", "category": "Communication", "url": "https://discord.com"},
    {"name": "Microsoft Teams", "desc": "Team collaboration", "category": "Communication", "url": "https://teams.microsoft.com"},
    {"name": "Zoom", "desc": "Video conferencing", "category": "Communication", "url": "https://zoom.us"},
    {"name": "Loom", "desc": "Async video", "category": "Communication", "url": "https://loom.com"},
    {"name": "Krisp", "desc": "Noise cancellation", "category": "Communication", "url": "https://krisp.ai"},
    {"name": "Grain", "desc": "Meeting recording", "category": "Communication", "url": "https://grain.com"},
    {"name": "Fireflies", "desc": "Meeting transcription", "category": "Communication", "url": "https://fireflies.ai"},
    {"name": "Otter", "desc": "Meeting notes", "category": "Communication", "url": "https://otter.ai"},
    {"name": "Fathom", "desc": "Meeting assistant", "category": "Communication", "url": "https://fathom.video"},
    {"name": "Calendly", "desc": "Scheduling", "category": "Scheduling", "url": "https://calendly.com"},
    {"name": "Cal.com", "desc": "Open scheduling", "category": "Scheduling", "url": "https://cal.com"},
    {"name": "Doodle", "desc": "Scheduling", "category": "Scheduling", "url": "https://doodle.com"},
    {"name": "SavvyCal", "desc": "Scheduling", "category": "Scheduling", "url": "https://savvycal.com"},
    {"name": "Reclaim", "desc": "AI scheduling", "category": "Scheduling", "url": "https://reclaim.ai"},
    {"name": "Clockwise", "desc": "Calendar optimization", "category": "Scheduling", "url": "https://clockwise.com"},
    {"name": "Motion", "desc": "AI calendar", "category": "Scheduling", "url": "https://usemotion.com"},
    {"name": "Akiflow", "desc": "Time blocking", "category": "Scheduling", "url": "https://akiflow.com"},
    {"name": "Sunsama", "desc": "Daily planner", "category": "Scheduling", "url": "https://sunsama.com"},
    {"name": "Figma", "desc": "Design collaboration", "category": "Design", "url": "https://figma.com"},
    {"name": "Canva", "desc": "Design platform", "category": "Design", "url": "https://canva.com"},
    {"name": "Framer", "desc": "Website builder", "category": "Design", "url": "https://framer.com"},
    {"name": "Webflow", "desc": "No-code builder", "category": "Design", "url": "https://webflow.com"},
    {"name": "Miro", "desc": "Visual collaboration", "category": "Design", "url": "https://miro.com"},
    {"name": "FigJam", "desc": "Whiteboarding", "category": "Design", "url": "https://figma.com/figjam"},
    {"name": "Whimsical", "desc": "Visual workspace", "category": "Design", "url": "https://whimsical.com"},
    {"name": "Excalidraw", "desc": "Sketching tool", "category": "Design", "url": "https://excalidraw.com"},
    {"name": "tldraw", "desc": "Drawing tool", "category": "Design", "url": "https://tldraw.com"},
    {"name": "Lottie", "desc": "Animation library", "category": "Design", "url": "https://lottiefiles.com"},
    {"name": "Rive", "desc": "Interactive design", "category": "Design", "url": "https://rive.app"},
    {"name": "Spline", "desc": "3D design", "category": "Design", "url": "https://spline.design"},
    {"name": "Readymag", "desc": "Web design", "category": "Design", "url": "https://readymag.com"},
    {"name": "Supa", "desc": "Video editing", "category": "Design", "url": "https://supa.so"},
    {"name": "Descript", "desc": "Video/audio editing", "category": "Design", "url": "https://descript.com"},
    {"name": "Kapwing", "desc": "Video creation", "category": "Design", "url": "https://kapwing.com"},

    # Testing & QA (50)
    {"name": "Playwright", "desc": "Browser automation", "category": "Testing", "url": "https://playwright.dev"},
    {"name": "Cypress", "desc": "E2E testing", "category": "Testing", "url": "https://cypress.io"},
    {"name": "Selenium", "desc": "Browser automation", "category": "Testing", "url": "https://selenium.dev"},
    {"name": "Puppeteer", "desc": "Chrome automation", "category": "Testing", "url": "https://pptr.dev"},
    {"name": "WebdriverIO", "desc": "Test automation", "category": "Testing", "url": "https://webdriver.io"},
    {"name": "Appium", "desc": "Mobile testing", "category": "Testing", "url": "https://appium.io"},
    {"name": "Detox", "desc": "Mobile E2E testing", "category": "Testing", "url": "https://wix.github.io/Detox"},
    {"name": "Maestro", "desc": "Mobile UI testing", "category": "Testing", "url": "https://maestro.mobile.dev"},
    {"name": "Katalon", "desc": "Test automation", "category": "Testing", "url": "https://katalon.com"},
    {"name": "TestComplete", "desc": "UI testing", "category": "Testing", "url": "https://smartbear.com/product/testcomplete"},
    {"name": "Ranorex", "desc": "Test automation", "category": "Testing", "url": "https://ranorex.com"},
    {"name": "Sauce Labs", "desc": "Cloud testing", "category": "Testing", "url": "https://saucelabs.com"},
    {"name": "BrowserStack", "desc": "Cross-browser testing", "category": "Testing", "url": "https://browserstack.com"},
    {"name": "LambdaTest", "desc": "Cross-browser testing", "category": "Testing", "url": "https://lambdatest.com"},
    {"name": "Percy", "desc": "Visual testing", "category": "Testing", "url": "https://percy.io"},
    {"name": "Chromatic", "desc": "Visual testing", "category": "Testing", "url": "https://chromatic.com"},
    {"name": "Applitools", "desc": "Visual AI testing", "category": "Testing", "url": "https://applitools.com"},
    {"name": "Testim", "desc": "AI testing", "category": "Testing", "url": "https://testim.io"},
    {"name": "Mabl", "desc": "ML testing", "category": "Testing", "url": "https://mabl.com"},
    {"name": "Functionize", "desc": "AI testing", "category": "Testing", "url": "https://functionize.com"},
    {"name": "Jest", "desc": "JavaScript testing", "category": "Testing", "url": "https://jestjs.io"},
    {"name": "Vitest", "desc": "Vite-native testing", "category": "Testing", "url": "https://vitest.dev"},
    {"name": "Testing Library", "desc": "UI testing utils", "category": "Testing", "url": "https://testing-library.com"},
    {"name": "Mocha", "desc": "JavaScript testing", "category": "Testing", "url": "https://mochajs.org"},
    {"name": "Jasmine", "desc": "BDD testing", "category": "Testing", "url": "https://jasmine.github.io"},
    {"name": "AVA", "desc": "Test runner", "category": "Testing", "url": "https://avajs.dev"},
    {"name": "Tap", "desc": "Test framework", "category": "Testing", "url": "https://node-tap.org"},
    {"name": "Pytest", "desc": "Python testing", "category": "Testing", "url": "https://pytest.org"},
    {"name": "PHPUnit", "desc": "PHP testing", "category": "Testing", "url": "https://phpunit.de"},
    {"name": "RSpec", "desc": "Ruby testing", "category": "Testing", "url": "https://rspec.info"},
    {"name": "JUnit", "desc": "Java testing", "category": "Testing", "url": "https://junit.org"},
    {"name": "TestNG", "desc": "Java testing", "category": "Testing", "url": "https://testng.org"},
    {"name": "GoTest", "desc": "Go testing", "category": "Testing", "url": "https://golang.org/pkg/testing"},
    {"name": "Storybook", "desc": "UI development", "category": "Testing", "url": "https://storybook.js.org"},
    {"name": "Ladle", "desc": "Storybook alternative", "category": "Testing", "url": "https://ladle.dev"},
    {"name": "Histoire", "desc": "Vue stories", "category": "Testing", "url": "https://histoire.dev"},
    {"name": "Mock Service Worker", "desc": "API mocking", "category": "Testing", "url": "https://mswjs.io"},
    {"name": "Mirage", "desc": "API mocking", "category": "Testing", "url": "https://miragejs.com"},
    {"name": "Nock", "desc": "HTTP mocking", "category": "Testing", "url": "https://github.com/nock/nock"},
    {"name": "WireMock", "desc": "API simulation", "category": "Testing", "url": "https://wiremock.org"},
    {"name": "Postman", "desc": "API platform", "category": "Testing", "url": "https://postman.com"},
    {"name": "Insomnia", "desc": "API client", "category": "Testing", "url": "https://insomnia.rest"},
    {"name": "Hoppscotch", "desc": "Open API client", "category": "Testing", "url": "https://hoppscotch.io"},
    {"name": "Bruno", "desc": "API client", "category": "Testing", "url": "https://usebruno.com"},
    {"name": "Paw", "desc": "API client", "category": "Testing", "url": "https://paw.cloud"},
    {"name": "Swagger", "desc": "API documentation", "category": "Testing", "url": "https://swagger.io"},
    {"name": "Stoplight", "desc": "API design", "category": "Testing", "url": "https://stoplight.io"},
    {"name": "ReadMe", "desc": "API documentation", "category": "Testing", "url": "https://readme.com"},
    {"name": "Docusaurus", "desc": "Documentation", "category": "Testing", "url": "https://docusaurus.io"},
    {"name": "Mintlify", "desc": "Documentation", "category": "Testing", "url": "https://mintlify.com"},
]

def main():
    print("🦞 APIClaw Night Expansion - 05:00 Feb 23, 2026")
    print("=" * 50)
    
    registry = load_registry()
    existing_ids = get_existing_ids(registry)
    
    print(f"Current APIs: {len(registry['apis'])}")
    
    added = 0
    for api in NEW_APIS:
        api_id = generate_id(api['name'])
        
        # Skip duplicates
        if api_id in existing_ids:
            continue
        
        new_api = {
            "id": api_id,
            "name": api['name'],
            "description": api['desc'],
            "category": api['category'],
            "authType": "apiKey",
            "baseUrl": api['url'],
            "docsUrl": api['url'],
            "addedAt": datetime.now().isoformat()
        }
        
        registry['apis'].append(new_api)
        existing_ids.add(api_id)
        added += 1
    
    save_registry(registry)
    
    print(f"Added: +{added} APIs")
    print(f"Total: {len(registry['apis'])}")
    
    return added

if __name__ == "__main__":
    main()
