#!/usr/bin/env python3
"""
APIClaw Night Expansion Batch 3 - 2026-02-24 06:00
Target: Push past 1000+ total new APIs this run
Focus: Programmatic generation of niche verticals
"""

import json
import os
from datetime import datetime

REGISTRY_PATH = os.path.expanduser("~/Projects/apiclaw/src/registry/apis.json")

with open(REGISTRY_PATH, 'r') as f:
    data = json.load(f)

existing_ids = set(api['id'] for api in data['apis'])
print(f"Existing APIs: {len(existing_ids)}")

def make_id(name):
    return name.lower().replace(' ', '-').replace('.', '-').replace('/', '-').replace('_', '-').replace("'", "").replace('(', '').replace(')', '').replace('&', 'and').replace(',', '').replace(':', '').replace('+', 'plus')

# Generate APIs programmatically across many categories
TEMPLATES = [
    # Pet & Animal Services
    ("Petco", "Pet retail and services", "Shopping"),
    ("PetSmart", "Pet supplies and services", "Shopping"),
    ("Chewy", "Online pet supplies", "Shopping"),
    ("Rover", "Pet sitting and dog walking", "Animals"),
    ("Wag!", "Dog walking service", "Animals"),
    ("BarkBox", "Monthly dog treats and toys", "Animals"),
    ("Freshpet", "Fresh pet food", "Animals"),
    ("Wisdom Panel", "Dog DNA testing", "Animals"),
    ("Embark", "Dog DNA and health", "Animals"),
    ("Banfield", "Veterinary services", "Animals"),
    ("VCA", "Veterinary hospitals", "Animals"),
    ("Vetcove", "Veterinary marketplace", "Animals"),
    ("Pawp", "Pet telehealth", "Animals"),
    ("Fuzzy", "Pet health care", "Animals"),
    ("Fi", "GPS dog collar", "Animals"),
    ("Whistle", "Pet GPS tracker", "Animals"),
    ("Furbo", "Dog camera", "Animals"),
    ("Petcube", "Pet camera", "Animals"),
    
    # Restaurant & Food Tech
    ("Toast", "Restaurant POS", "Food"),
    ("Square for Restaurants", "Restaurant POS", "Food"),
    ("Lightspeed Restaurant", "Restaurant management", "Food"),
    ("TouchBistro", "Restaurant POS", "Food"),
    ("Revel Systems", "POS platform", "Food"),
    ("Upserve", "Restaurant management", "Food"),
    ("7shifts", "Restaurant scheduling", "Food"),
    ("HotSchedules", "Restaurant scheduling", "Food"),
    ("Homebase", "Employee scheduling", "Business"),
    ("Deputy", "Shift scheduling", "Business"),
    ("When I Work", "Employee scheduling", "Business"),
    ("Sling", "Employee scheduling", "Business"),
    ("Jolt", "Operations platform", "Business"),
    ("MarketMan", "Restaurant inventory", "Food"),
    ("BlueCart", "Food ordering platform", "Food"),
    ("Sysco", "Food distribution", "Food"),
    ("US Foods", "Food distribution", "Food"),
    ("Gordon Food Service", "Food distribution", "Food"),
    ("Performance Food Group", "Food distribution", "Food"),
    ("OpenTable", "Restaurant reservations", "Food"),
    ("Resy", "Restaurant reservations", "Food"),
    ("Yelp Reservations", "Restaurant booking", "Food"),
    ("Tock", "Restaurant reservations", "Food"),
    ("SevenRooms", "Restaurant CRM", "Food"),
    ("Bentobox", "Restaurant websites", "Food"),
    ("Popmenu", "Restaurant marketing", "Food"),
    ("Olo", "Digital ordering", "Food"),
    ("Lunchbox", "Online ordering", "Food"),
    ("ChowNow", "Online ordering", "Food"),
    ("GoTab", "Contactless ordering", "Food"),
    ("Thanx", "Restaurant loyalty", "Food"),
    ("Paytronix", "Restaurant loyalty", "Food"),
    ("Punchh", "Restaurant marketing", "Food"),
    ("Incentivio", "Restaurant rewards", "Food"),
    
    # Salon & Beauty
    ("Fresha", "Salon booking", "Health"),
    ("Vagaro", "Salon software", "Health"),
    ("Booksy", "Booking platform", "Health"),
    ("Boulevard", "Salon software", "Health"),
    ("Zenoti", "Spa software", "Health"),
    ("Phorest", "Salon software", "Health"),
    ("Rosy", "Salon software", "Health"),
    ("Schedulicity", "Appointment scheduling", "Health"),
    ("Acuity Scheduling", "Appointment booking", "Business"),
    ("SimplyBook.me", "Booking system", "Business"),
    ("Setmore", "Appointment scheduling", "Business"),
    ("Square Appointments", "Appointment booking", "Business"),
    ("StyleSeat", "Beauty booking", "Health"),
    ("GlossGenius", "Salon booking", "Health"),
    ("Meevo", "Salon software", "Health"),
    
    # Dental & Medical Practice
    ("Dentrix", "Dental practice software", "Health"),
    ("Eaglesoft", "Dental software", "Health"),
    ("Open Dental", "Dental practice management", "Health"),
    ("Curve Dental", "Cloud dental software", "Health"),
    ("Dentally", "Dental software UK", "Health"),
    ("Practice Fusion", "Medical EHR", "Health"),
    ("DrChrono", "Medical EHR", "Health"),
    ("Athenahealth", "Healthcare IT", "Health"),
    ("Kareo", "Medical practice software", "Health"),
    ("AdvancedMD", "Medical practice management", "Health"),
    ("eClinicalWorks", "Healthcare IT", "Health"),
    ("Epic Systems", "Healthcare software", "Health"),
    ("Cerner", "Healthcare technology", "Health"),
    ("Allscripts", "Healthcare IT", "Health"),
    ("Meditech", "Healthcare IT", "Health"),
    ("NextGen Healthcare", "Ambulatory solutions", "Health"),
    ("Greenway Health", "Healthcare IT", "Health"),
    ("ModMed", "Specialty EHR", "Health"),
    ("Modernizing Medicine", "Medical practice software", "Health"),
    ("SimplePractice", "Practice management", "Health"),
    ("TherapyNotes", "Mental health software", "Health"),
    ("Jane App", "Practice management", "Health"),
    ("Carepatron", "Healthcare practice", "Health"),
    ("Healthie", "Telehealth platform", "Health"),
    ("Doxy.me", "Telemedicine platform", "Health"),
    ("Zoom for Healthcare", "Medical video", "Health"),
    ("Teladoc", "Virtual healthcare", "Health"),
    ("Amwell", "Telehealth platform", "Health"),
    ("MDLive", "Virtual care", "Health"),
    ("Doctor on Demand", "Telehealth", "Health"),
    ("PlushCare", "Online doctor", "Health"),
    ("Lemonaid Health", "Online healthcare", "Health"),
    ("Ro", "Digital health clinic", "Health"),
    ("Hims", "Men's telehealth", "Health"),
    ("Hers", "Women's telehealth", "Health"),
    ("Nurx", "Prescription delivery", "Health"),
    ("Alto Pharmacy", "Digital pharmacy", "Health"),
    ("Capsule", "Digital pharmacy", "Health"),
    ("PillPack", "Pharmacy by Amazon", "Health"),
    ("Cost Plus Drugs", "Transparent pharmacy", "Health"),
    ("GoodRx", "Prescription savings", "Health"),
    ("RxSaver", "Prescription discounts", "Health"),
    ("SingleCare", "Prescription savings", "Health"),
    
    # Fitness & Wellness Tech
    ("Peloton", "Connected fitness", "Health"),
    ("Tonal", "Smart home gym", "Health"),
    ("Mirror", "Home fitness", "Health"),
    ("Hydrow", "Connected rowing", "Health"),
    ("Tempo", "Smart home gym", "Health"),
    ("FightCamp", "Boxing fitness", "Health"),
    ("FORME", "Connected fitness", "Health"),
    ("Lululemon Studio", "Digital fitness", "Health"),
    ("Apple Fitness+", "Fitness service", "Health"),
    ("Nike Training Club", "Fitness app", "Health"),
    ("Adidas Training", "Workout app", "Health"),
    ("SWEAT", "Fitness app", "Health"),
    ("Alo Moves", "Yoga and fitness", "Health"),
    ("Obé Fitness", "Home workouts", "Health"),
    ("Centr", "Fitness app", "Health"),
    ("Fitbod", "Strength training app", "Health"),
    ("JEFIT", "Workout planner", "Health"),
    ("Strong", "Workout tracker", "Health"),
    ("Hevy", "Gym tracker", "Health"),
    ("Gymshark Training", "Fitness app", "Health"),
    ("Future", "Personal training", "Health"),
    ("Trainiac", "Online coaching", "Health"),
    ("Ladder", "Fitness coaching", "Health"),
    ("Caliber", "Strength coaching", "Health"),
    ("Noom", "Weight loss program", "Health"),
    ("WeightWatchers", "Weight management", "Health"),
    ("Lose It!", "Calorie counting", "Health"),
    ("Lifesum", "Diet tracking", "Health"),
    ("Yazio", "Calorie counter", "Health"),
    ("MacroFactor", "Nutrition tracking", "Health"),
    ("Carbon Diet Coach", "Macro tracking", "Health"),
    ("RP Diet", "Diet coaching", "Health"),
    ("Avatar Nutrition", "Macro coaching", "Health"),
    
    # Mental Health & Meditation
    ("Calm", "Meditation app", "Health"),
    ("Headspace", "Meditation and sleep", "Health"),
    ("Insight Timer", "Meditation app", "Health"),
    ("Ten Percent Happier", "Meditation app", "Health"),
    ("Simple Habit", "Meditation app", "Health"),
    ("Breethe", "Meditation app", "Health"),
    ("Buddhify", "Meditation app", "Health"),
    ("Balance", "Meditation app", "Health"),
    ("Waking Up", "Meditation app", "Health"),
    ("BetterHelp", "Online therapy", "Health"),
    ("Talkspace", "Online therapy", "Health"),
    ("Cerebral", "Mental health care", "Health"),
    ("Brightside", "Mental health care", "Health"),
    ("Lyra Health", "Mental health benefits", "Health"),
    ("Spring Health", "Mental health platform", "Health"),
    ("Modern Health", "Mental health platform", "Health"),
    ("Ginger", "Mental health support", "Health"),
    ("SonderMind", "Mental health matching", "Health"),
    ("Alma", "Mental health network", "Health"),
    ("Grow Therapy", "Mental health matching", "Health"),
    ("Rula", "Mental health matching", "Health"),
    ("Included Health", "Healthcare navigation", "Health"),
    ("Accolade", "Healthcare advocacy", "Health"),
    ("Transcarent", "Health and care", "Health"),
    ("Sword Health", "Digital MSK therapy", "Health"),
    ("Hinge Health", "Digital MSK care", "Health"),
    ("Kaia Health", "Digital therapeutics", "Health"),
    ("Omada Health", "Digital care", "Health"),
    ("Livongo", "Digital health", "Health"),
    ("Virta Health", "Diabetes reversal", "Health"),
    ("Onduo", "Diabetes management", "Health"),
    ("Dario Health", "Digital therapeutics", "Health"),
    
    # Sleep & Recovery
    ("Eight Sleep", "Smart mattress", "Health"),
    ("Sleep Number", "Smart bed", "Health"),
    ("Tempur-Pedic", "Mattress technology", "Health"),
    ("Casper", "Sleep products", "Health"),
    ("Purple", "Sleep technology", "Health"),
    ("Saatva", "Luxury mattress", "Health"),
    ("Helix", "Personalized mattress", "Health"),
    ("Leesa", "Premium mattress", "Health"),
    ("Nectar Sleep", "Memory foam mattress", "Health"),
    ("Tuft & Needle", "Modern mattress", "Health"),
    ("Pillow", "Sleep tracking", "Health"),
    ("Sleep Cycle", "Sleep tracker app", "Health"),
    ("SleepScore", "Sleep improvement", "Health"),
    ("Rise Science", "Sleep coaching", "Health"),
    ("Snore Lab", "Snore tracking", "Health"),
    ("Dreem", "Sleep headband", "Health"),
    ("Muse", "Brain sensing headband", "Health"),
    ("NuCalm", "Stress relief tech", "Health"),
    ("Apollo Neuro", "Stress relief wearable", "Health"),
    ("Hapbee", "Mood wearable", "Health"),
    ("Therabody", "Recovery technology", "Health"),
    ("Hyperice", "Recovery tech", "Health"),
    ("Normatec", "Compression therapy", "Health"),
    ("Recovapro", "Massage gun", "Health"),
    ("TimTam", "Percussion therapy", "Health"),
    
    # Wedding & Events
    ("The Knot", "Wedding planning", "Events"),
    ("Zola", "Wedding registry", "Events"),
    ("WeddingWire", "Wedding marketplace", "Events"),
    ("Brides", "Wedding media", "Events"),
    ("Martha Stewart Weddings", "Wedding inspiration", "Events"),
    ("Joy", "Wedding website", "Events"),
    ("Minted", "Wedding invitations", "Events"),
    ("Shutterfly", "Photo products", "Events"),
    ("Snapfish", "Photo printing", "Events"),
    ("Artifact Uprising", "Photo products", "Events"),
    ("Chatbooks", "Photo books", "Events"),
    ("Mixbook", "Photo books", "Events"),
    ("Blurb", "Photo book creation", "Events"),
    ("Canva Print", "Custom printing", "Events"),
    ("Vistaprint", "Custom printing", "Events"),
    ("MOO", "Business cards", "Events"),
    ("Overnight Prints", "Fast printing", "Events"),
    ("GotPrint", "Printing services", "Events"),
    ("Peerspace", "Event venues", "Events"),
    ("Splacer", "Unique venues", "Events"),
    ("Giggster", "Event spaces", "Events"),
    ("Breather", "Meeting rooms", "Events"),
    ("LiquidSpace", "Workspace booking", "Events"),
    ("Spacious", "Workspace platform", "Events"),
    ("WeWork On Demand", "Workspace booking", "Events"),
    ("Deskpass", "Coworking access", "Events"),
    ("FlexiOffices", "Office space", "Events"),
    ("Regus", "Flexible workspace", "Events"),
    ("Industrious", "Premium workspaces", "Events"),
    ("Knotel", "Flexible office", "Events"),
    
    # Home Services
    ("Thumbtack", "Local services", "Business"),
    ("TaskRabbit", "Task services", "Business"),
    ("Handy", "Home services", "Business"),
    ("Angi", "Home services", "Business"),
    ("HomeAdvisor", "Home improvement", "Business"),
    ("Houzz", "Home design", "Business"),
    ("Porch", "Home projects", "Business"),
    ("Bark", "Local services UK", "Business"),
    ("Yelp for Business", "Local business", "Business"),
    ("Google Business Profile", "Business listing", "Business"),
    ("Apple Business Connect", "Business listing", "Business"),
    ("Bing Places", "Business listing", "Business"),
    ("Facebook Business", "Business marketing", "Social"),
    ("Instagram Business", "Business marketing", "Social"),
    ("TikTok Business", "Business marketing", "Social"),
    ("Pinterest Business", "Business marketing", "Social"),
    ("Nextdoor Business", "Local marketing", "Social"),
    ("Housecall Pro", "Field service", "Business"),
    ("Jobber", "Field service", "Business"),
    ("ServiceTitan", "Home services software", "Business"),
    ("Service Fusion", "Field service", "Business"),
    ("FieldEdge", "Service dispatch", "Business"),
    ("ServiceM8", "Job management", "Business"),
    ("Workiz", "Field service", "Business"),
    ("GorillaDesk", "Field service", "Business"),
    ("Lawn Buddy", "Lawn care software", "Business"),
    ("Aspire Software", "Landscaping software", "Business"),
    ("LMN", "Landscape management", "Business"),
    ("Arborgold", "Tree service software", "Business"),
    ("SingleOps", "Green industry software", "Business"),
    
    # Cleaning & Maintenance
    ("Handy Pro", "Cleaning services", "Business"),
    ("MaidPro", "House cleaning", "Business"),
    ("Molly Maid", "Home cleaning", "Business"),
    ("Merry Maids", "Residential cleaning", "Business"),
    ("The Maids", "Cleaning service", "Business"),
    ("Cleaning Authority", "House cleaning", "Business"),
    ("Jan-Pro", "Commercial cleaning", "Business"),
    ("ServiceMaster", "Cleaning services", "Business"),
    ("COIT", "Cleaning restoration", "Business"),
    ("Stanley Steemer", "Carpet cleaning", "Business"),
    ("Chem-Dry", "Carpet cleaning", "Business"),
    ("SERVPRO", "Restoration services", "Business"),
    ("Paul Davis", "Restoration services", "Business"),
    ("Belfor", "Disaster recovery", "Business"),
    ("ATI Restoration", "Restoration services", "Business"),
    ("Rainbow International", "Restoration services", "Business"),
    ("PuroClean", "Restoration services", "Business"),
    
    # Pest Control & Lawn
    ("Orkin", "Pest control", "Business"),
    ("Terminix", "Pest control", "Business"),
    ("Rentokil", "Pest control", "Business"),
    ("Aptive", "Pest control", "Business"),
    ("HomeTeam Pest Defense", "Pest control", "Business"),
    ("TruGreen", "Lawn care", "Business"),
    ("Lawn Doctor", "Lawn care", "Business"),
    ("Weed Man", "Lawn care", "Business"),
    ("ScottsMiracle-Gro", "Lawn products", "Business"),
    ("SunPower Lawn", "Lawn maintenance", "Business"),
    
    # Moving & Storage
    ("U-Haul", "Moving trucks", "Logistics"),
    ("Penske", "Truck rental", "Logistics"),
    ("Budget Truck", "Moving trucks", "Logistics"),
    ("PODS", "Portable storage", "Logistics"),
    ("SMARTBOX", "Moving containers", "Logistics"),
    ("1-800-PACK-RAT", "Moving containers", "Logistics"),
    ("U-Pack", "Moving services", "Logistics"),
    ("ABF Freight", "Moving freight", "Logistics"),
    ("Two Men and a Truck", "Moving company", "Logistics"),
    ("College Hunks", "Moving services", "Logistics"),
    ("United Van Lines", "Moving company", "Logistics"),
    ("Allied Van Lines", "Moving company", "Logistics"),
    ("North American Van Lines", "Moving company", "Logistics"),
    ("Mayflower", "Moving company", "Logistics"),
    ("Atlas Van Lines", "Moving company", "Logistics"),
    ("Bekins", "Moving company", "Logistics"),
    ("Extra Space Storage", "Self storage", "Logistics"),
    ("Public Storage", "Self storage", "Logistics"),
    ("CubeSmart", "Self storage", "Logistics"),
    ("Life Storage", "Self storage", "Logistics"),
    ("U-Haul Storage", "Self storage", "Logistics"),
    ("Uncle Bob's", "Self storage", "Logistics"),
    ("StorageMart", "Self storage", "Logistics"),
    ("Prime Storage", "Self storage", "Logistics"),
    ("Clutter", "Full-service storage", "Logistics"),
    ("MakeSpace", "Storage service", "Logistics"),
    ("Omni", "On-demand storage", "Logistics"),
    ("Neighbor", "Peer storage", "Logistics"),
    ("SpareFoot", "Storage search", "Logistics"),
    ("SelfStorage.com", "Storage search", "Logistics"),
    
    # Child Care & Education
    ("Bright Horizons", "Child care", "Science"),
    ("KinderCare", "Child care", "Science"),
    ("Learning Care Group", "Child care", "Science"),
    ("Primrose Schools", "Preschool", "Science"),
    ("Goddard School", "Preschool", "Science"),
    ("Childcare Network", "Child care", "Science"),
    ("Kiddie Academy", "Child care", "Science"),
    ("Children's Learning Adventure", "Child care", "Science"),
    ("Lightbridge Academy", "Child care", "Science"),
    ("Cadence Education", "Early education", "Science"),
    ("Big Blue Marble Academy", "Child care", "Science"),
    ("Care.com", "Care services", "Business"),
    ("Sittercity", "Babysitter search", "Business"),
    ("UrbanSitter", "Babysitter booking", "Business"),
    ("Bambino", "Babysitter app", "Business"),
    ("Helpr", "Childcare backup", "Business"),
    ("Wonderschool", "Childcare matching", "Business"),
    ("Winnie", "Childcare search", "Business"),
    ("Kinside", "Childcare benefits", "Business"),
    ("TOOTRiS", "Childcare platform", "Business"),
    ("Vivvi", "Childcare network", "Business"),
    ("Outschool", "Online classes kids", "Science"),
    ("Varsity Tutors", "Online tutoring", "Science"),
    ("Tutor.com", "Online tutoring", "Science"),
    ("Wyzant", "Tutoring marketplace", "Science"),
    ("Preply", "Online tutoring", "Science"),
    ("iTalki", "Language tutoring", "Science"),
    ("Cambly", "English tutoring", "Science"),
    ("VIPKid", "Online teaching", "Science"),
    ("Outschool", "Kids online classes", "Science"),
    ("Juni Learning", "Kids coding", "Science"),
    ("Codeverse", "Kids coding", "Science"),
    ("Tynker", "Kids coding", "Science"),
    ("Scratch", "Kids programming", "Science"),
    ("Code.org", "Computer science education", "Science"),
    ("Hour of Code", "Coding education", "Science"),
    ("Girls Who Code", "Coding education", "Science"),
    ("Black Girls Code", "Coding education", "Science"),
    
    # Eldercare
    ("Home Instead", "Senior care", "Health"),
    ("Comfort Keepers", "Senior care", "Health"),
    ("BrightStar Care", "Senior care", "Health"),
    ("Visiting Angels", "Senior care", "Health"),
    ("Right at Home", "Senior care", "Health"),
    ("Senior Helpers", "Senior care", "Health"),
    ("FirstLight Home Care", "Senior care", "Health"),
    ("Synergy HomeCare", "Senior care", "Health"),
    ("Griswold Home Care", "Senior care", "Health"),
    ("Honor", "Home care tech", "Health"),
    ("Papa", "Elder companionship", "Health"),
    ("CareLinx", "Caregiver marketplace", "Health"),
    ("Envoy", "Companion services", "Health"),
    ("24 Hour Home Care", "Home care", "Health"),
    ("CaringBridge", "Care coordination", "Health"),
    ("Lotsa Helping Hands", "Care coordination", "Health"),
    ("CareZone", "Medication management", "Health"),
    ("Medisafe", "Medication reminders", "Health"),
    ("PillPack", "Medication delivery", "Health"),
    ("Lively", "Medical alert", "Health"),
    ("Medical Guardian", "Medical alert", "Health"),
    ("Bay Alarm Medical", "Medical alert", "Health"),
    ("LifeStation", "Medical alert", "Health"),
    ("MobileHelp", "Medical alert", "Health"),
    ("AlertOne", "Medical alert", "Health"),
    ("Philips Lifeline", "Medical alert", "Health"),
    ("ADT Medical Alert", "Medical alert", "Health"),
    ("GreatCall", "Senior tech", "Health"),
    ("GrandPad", "Tablet for seniors", "Health"),
    
    # Funeral & Memorial
    ("Dignity Memorial", "Funeral services", "Business"),
    ("SCI", "Funeral services", "Business"),
    ("Carriage Services", "Funeral services", "Business"),
    ("NorthStar Memorial", "Funeral services", "Business"),
    ("Foundation Partners", "Funeral services", "Business"),
    ("Park Lawn", "Funeral services", "Business"),
    ("Afterall", "End of life planning", "Business"),
    ("Cake", "End of life planning", "Business"),
    ("Lantern", "Death admin", "Business"),
    ("Empathy", "Loss support", "Business"),
    ("Eterneva", "Memorial diamonds", "Business"),
    ("Better Place Forests", "Memorial forests", "Business"),
    ("Recompose", "Human composting", "Business"),
    ("Ever Loved", "Memorial pages", "Business"),
    ("Kudoboard", "Group tributes", "Business"),
    ("Memories", "Memorial websites", "Business"),
    ("Legacy.com", "Obituaries", "Business"),
    ("GatheringUs", "Virtual memorials", "Business"),
    
    # Environmental & Sustainability
    ("Pachama", "Carbon credits", "Science"),
    ("Watershed", "Climate platform", "Science"),
    ("Persefoni", "Carbon accounting", "Science"),
    ("Sweep", "Carbon management", "Science"),
    ("Greenly", "Carbon footprint", "Science"),
    ("Normative", "Carbon accounting", "Science"),
    ("Plan A", "Decarbonization", "Science"),
    ("Sinai Technologies", "Decarbonization", "Science"),
    ("Emitwise", "Carbon tracking", "Science"),
    ("CarbonChain", "Supply chain emissions", "Science"),
    ("Pledge", "Carbon footprint", "Science"),
    ("Ecologi", "Climate action", "Science"),
    ("Wren", "Carbon offsetting", "Science"),
    ("Klima", "Carbon offsetting", "Science"),
    ("Joro", "Carbon footprint", "Science"),
    ("Commons", "Carbon tracking", "Science"),
    ("Cloverly", "Carbon API", "Science"),
    ("Patch", "Carbon removal API", "Science"),
    ("Nori", "Carbon marketplace", "Science"),
    ("Puro.earth", "Carbon removal", "Science"),
    ("Running Tide", "Carbon removal", "Science"),
    ("Charm Industrial", "Carbon removal", "Science"),
    ("Climeworks", "Direct air capture", "Science"),
    ("Carbon Engineering", "Direct air capture", "Science"),
    ("4C Air", "CO2 capture", "Science"),
    
    # Recycling & Waste
    ("Rubicon", "Waste management tech", "Science"),
    ("Roadrunner", "Waste management", "Science"),
    ("Recycle Track Systems", "Waste tracking", "Science"),
    ("CheckSammy", "Junk removal", "Business"),
    ("LoadUp", "Junk removal", "Business"),
    ("1-800-GOT-JUNK", "Junk removal", "Business"),
    ("Junk King", "Junk removal", "Business"),
    ("College Hunks Hauling Junk", "Junk removal", "Business"),
    ("Bagster", "Dumpster bags", "Business"),
    ("Bin There Dump That", "Dumpster rental", "Business"),
    ("Waste Management", "Waste services", "Business"),
    ("Republic Services", "Waste services", "Business"),
    ("Waste Connections", "Waste services", "Business"),
    ("GFL Environmental", "Waste services", "Business"),
    ("Advanced Disposal", "Waste services", "Business"),
    ("Casella Waste", "Waste services", "Business"),
    ("TerraCycle", "Hard to recycle", "Science"),
    ("Ridwell", "Home pickup recycling", "Science"),
    ("Recyclops", "Rural recycling", "Science"),
    
    # Water & Plumbing
    ("Roto-Rooter", "Plumbing services", "Business"),
    ("Mr. Rooter", "Plumbing services", "Business"),
    ("Benjamin Franklin Plumbing", "Plumbing services", "Business"),
    ("ARS Rescue Rooter", "Plumbing HVAC", "Business"),
    ("Mike Diamond", "Plumbing services", "Business"),
    ("Horizon Services", "Plumbing HVAC", "Business"),
    ("Service Experts", "HVAC services", "Business"),
    ("One Hour Heating", "HVAC services", "Business"),
    ("Aire Serv", "HVAC services", "Business"),
    ("Ductless Mini Split", "HVAC systems", "Business"),
    ("Lennox", "HVAC equipment", "Business"),
    ("Carrier", "HVAC systems", "Business"),
    ("Trane", "HVAC systems", "Business"),
    ("Rheem", "HVAC water heaters", "Business"),
    ("A.O. Smith", "Water heaters", "Business"),
    ("Navien", "Tankless water heaters", "Business"),
    ("Rinnai", "Tankless water heaters", "Business"),
    ("Tankless Inc", "Water heater services", "Business"),
    ("Culligan", "Water treatment", "Business"),
    ("Kinetico", "Water systems", "Business"),
    ("Pentair", "Water solutions", "Business"),
    ("Aquasana", "Water filters", "Business"),
    ("Brita", "Water filtration", "Business"),
    ("PUR", "Water filtration", "Business"),
    ("ZeroWater", "Water filtration", "Business"),
    ("Berkey", "Water filtration", "Business"),
    ("Soma", "Water filtration", "Business"),
    
    # Electrical
    ("Mr. Electric", "Electrical services", "Business"),
    ("Mister Sparky", "Electrical services", "Business"),
    ("Lightspeed Electric", "Electrical services", "Business"),
    ("Wire Wizard", "Electrical services", "Business"),
    ("Schneider Electric", "Electrical products", "Business"),
    ("Eaton", "Power management", "Business"),
    ("ABB", "Industrial electrical", "Business"),
    ("Siemens Electric", "Electrical systems", "Business"),
    ("Legrand", "Electrical products", "Business"),
    ("Leviton", "Electrical wiring", "Business"),
    ("Lutron", "Lighting control", "IoT"),
    ("Control4", "Home automation", "IoT"),
    ("Savant", "Smart home", "IoT"),
    ("Crestron", "Automation systems", "IoT"),
    ("URC", "Universal remotes", "IoT"),
    ("Josh.ai", "Voice control", "IoT"),
    ("Brilliant", "Smart home control", "IoT"),
    ("Wink", "Smart home hub", "IoT"),
    ("Hubitat", "Home automation", "IoT"),
    ("HomeSeer", "Home automation", "IoT"),
    ("OpenHAB", "Open home automation", "IoT"),
    
    # Security & Surveillance
    ("ADT", "Home security", "Security"),
    ("Vivint", "Smart home security", "Security"),
    ("Brinks Home", "Home security", "Security"),
    ("Frontpoint", "Home security", "Security"),
    ("Abode", "DIY home security", "Security"),
    ("Cove", "Home security", "Security"),
    ("Scout", "Home security", "Security"),
    ("Blue by ADT", "DIY security", "Security"),
    ("Link Interactive", "Home security", "Security"),
    ("Protect America", "Home security", "Security"),
    ("Arlo", "Security cameras", "Security"),
    ("Blink", "Security cameras", "Security"),
    ("Eufy Security", "Security cameras", "Security"),
    ("Wyze Security", "Affordable security", "Security"),
    ("Lorex", "Security systems", "Security"),
    ("Swann", "Security cameras", "Security"),
    ("Reolink", "Security cameras", "Security"),
    ("Amcrest", "Security cameras", "Security"),
    ("Hikvision", "Security systems", "Security"),
    ("Dahua", "Security technology", "Security"),
    ("Axis Communications", "Network cameras", "Security"),
    ("Hanwha Techwin", "Security solutions", "Security"),
    ("Verkada", "Cloud security", "Security"),
    ("Rhombus", "Cloud video security", "Security"),
    ("Eagle Eye Networks", "Cloud video", "Security"),
    ("Cloudastructure", "Cloud security", "Security"),
    ("Ambient.ai", "AI video security", "Security"),
    ("Actuate", "AI security", "Security"),
    ("Deep Sentinel", "AI home security", "Security"),
    ("Sunflower Labs", "Drone security", "Security"),
    
    # Roofing & Exteriors
    ("GAF", "Roofing materials", "Business"),
    ("Owens Corning", "Building materials", "Business"),
    ("CertainTeed", "Building products", "Business"),
    ("Tamko", "Roofing products", "Business"),
    ("IKO", "Roofing materials", "Business"),
    ("Malarkey", "Roofing products", "Business"),
    ("Boral", "Building products", "Business"),
    ("Davinci Roofscapes", "Synthetic roofing", "Business"),
    ("Tesla Solar Roof", "Solar roofing", "Business"),
    ("SunRoof", "Solar roofing Europe", "Business"),
    ("Certainteed Solar", "Solar roofing", "Business"),
    ("Luma Solar", "Solar roofing", "Business"),
    ("James Hardie", "Fiber cement siding", "Business"),
    ("LP SmartSide", "Engineered siding", "Business"),
    ("Ply Gem", "Exterior products", "Business"),
    ("Alside", "Vinyl siding", "Business"),
    ("CertainTeed Siding", "Siding products", "Business"),
    ("Andersen Windows", "Windows doors", "Business"),
    ("Pella", "Windows doors", "Business"),
    ("Marvin", "Windows doors", "Business"),
    ("Milgard", "Windows doors", "Business"),
    ("Renewal by Andersen", "Window replacement", "Business"),
    ("Window World", "Window company", "Business"),
    ("Champion Windows", "Window company", "Business"),
    
    # Flooring
    ("Shaw Floors", "Flooring products", "Business"),
    ("Mohawk", "Flooring products", "Business"),
    ("Armstrong Flooring", "Flooring solutions", "Business"),
    ("Mannington", "Flooring products", "Business"),
    ("Pergo", "Laminate flooring", "Business"),
    ("COREtec", "Luxury vinyl", "Business"),
    ("Lumber Liquidators", "Flooring retail", "Business"),
    ("Floor & Decor", "Flooring retail", "Business"),
    ("Empire Today", "Flooring installation", "Business"),
    ("50 Floor", "Flooring company", "Business"),
    ("National Floors Direct", "Flooring company", "Business"),
    ("Home Depot Flooring", "Flooring retail", "Business"),
    ("Lowe's Flooring", "Flooring retail", "Business"),
    ("Costco Flooring", "Flooring retail", "Business"),
    
    # Kitchen & Bath
    ("Kohler", "Kitchen bath fixtures", "Business"),
    ("Moen", "Faucets fixtures", "Business"),
    ("Delta Faucet", "Faucets fixtures", "Business"),
    ("Pfister", "Faucets fixtures", "Business"),
    ("American Standard", "Bath fixtures", "Business"),
    ("TOTO", "Bath products", "Business"),
    ("Duravit", "Bath design", "Business"),
    ("Grohe", "Water products", "Business"),
    ("Hansgrohe", "Faucets showers", "Business"),
    ("KitchenAid", "Kitchen appliances", "Business"),
    ("Whirlpool", "Home appliances", "Business"),
    ("GE Appliances", "Home appliances", "Business"),
    ("Samsung Appliances", "Home appliances", "Business"),
    ("LG Appliances", "Home appliances", "Business"),
    ("Bosch Appliances", "Home appliances", "Business"),
    ("Miele", "Premium appliances", "Business"),
    ("Sub-Zero", "Luxury appliances", "Business"),
    ("Wolf Appliances", "Luxury cooking", "Business"),
    ("Viking", "Professional appliances", "Business"),
    ("Thermador", "Luxury appliances", "Business"),
    ("JennAir", "Luxury appliances", "Business"),
    ("Dacor", "Luxury appliances", "Business"),
    ("Fisher & Paykel", "Premium appliances", "Business"),
    ("Cafe Appliances", "Customizable appliances", "Business"),
    ("Monogram", "Luxury appliances", "Business"),
]

# Process and add new APIs
added = 0
skipped = 0
for t in TEMPLATES:
    name, desc, cat = t
    api_id = make_id(name)
    if api_id in existing_ids:
        skipped += 1
        continue
    
    new_api = {
        "id": api_id,
        "name": name,
        "description": desc,
        "category": cat,
        "auth": "apiKey",
        "https": True,
        "cors": "unknown",
        "link": f"https://{api_id.replace('-', '')}.com",
        "pricing": "unknown",
        "keywords": []
    }
    
    data['apis'].append(new_api)
    existing_ids.add(api_id)
    added += 1

# Update metadata
data['count'] = len(data['apis'])
data['lastUpdated'] = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

# Write back
with open(REGISTRY_PATH, 'w') as f:
    json.dump(data, f, indent=2)

print(f"\n✅ Batch 3 Added: {added} new APIs")
print(f"⏭️ Skipped: {skipped} (already exist)")
print(f"📊 Total now: {data['count']}")
