#!/usr/bin/env python3
"""
APIClaw Night Expansion - 05:00 Feb 23, 2026 - Batch 2
More unique APIs from specialized categories
"""

import json
import re
from pathlib import Path
from datetime import datetime

REGISTRY_PATH = Path(__file__).parent.parent / "src" / "registry" / "apis.json"

def generate_id(name: str) -> str:
    clean = re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')
    return clean[:50]

def load_registry() -> dict:
    with open(REGISTRY_PATH, 'r') as f:
        return json.load(f)

def save_registry(registry: dict):
    with open(REGISTRY_PATH, 'w') as f:
        json.dump(registry, f, indent=2)

def get_existing_ids(registry: dict) -> set:
    return {api['id'] for api in registry['apis']}

# Batch 2 - More specialized APIs
NEW_APIS = [
    # IoT & Hardware (40)
    {"name": "Particle", "desc": "IoT platform API", "category": "IoT", "url": "https://particle.io"},
    {"name": "Balena", "desc": "Fleet management IoT", "category": "IoT", "url": "https://balena.io"},
    {"name": "Losant", "desc": "IoT platform", "category": "IoT", "url": "https://losant.com"},
    {"name": "Hologram", "desc": "IoT cellular", "category": "IoT", "url": "https://hologram.io"},
    {"name": "Blues Wireless", "desc": "IoT connectivity", "category": "IoT", "url": "https://blues.io"},
    {"name": "Golioth", "desc": "IoT cloud", "category": "IoT", "url": "https://golioth.io"},
    {"name": "Bytebeam", "desc": "IoT platform", "category": "IoT", "url": "https://bytebeam.io"},
    {"name": "EMnify", "desc": "IoT connectivity", "category": "IoT", "url": "https://emnify.com"},
    {"name": "Soracom", "desc": "IoT platform", "category": "IoT", "url": "https://soracom.io"},
    {"name": "Tago.io", "desc": "IoT analytics", "category": "IoT", "url": "https://tago.io"},
    {"name": "Ubidots", "desc": "IoT platform", "category": "IoT", "url": "https://ubidots.com"},
    {"name": "Datacake", "desc": "IoT dashboard", "category": "IoT", "url": "https://datacake.co"},
    {"name": "Favoriot", "desc": "IoT middleware", "category": "IoT", "url": "https://favoriot.com"},
    {"name": "ThingsBoard", "desc": "IoT platform", "category": "IoT", "url": "https://thingsboard.io"},
    {"name": "Thinger.io", "desc": "IoT platform", "category": "IoT", "url": "https://thinger.io"},
    {"name": "Blynk", "desc": "IoT platform", "category": "IoT", "url": "https://blynk.io"},
    {"name": "IFTTT", "desc": "Automation platform", "category": "Automation", "url": "https://ifttt.com"},
    {"name": "Integromat", "desc": "Automation platform", "category": "Automation", "url": "https://integromat.com"},
    {"name": "Tines", "desc": "Security automation", "category": "Automation", "url": "https://tines.com"},
    {"name": "Workato", "desc": "Enterprise automation", "category": "Automation", "url": "https://workato.com"},
    {"name": "Bardeen", "desc": "Browser automation", "category": "Automation", "url": "https://bardeen.ai"},
    {"name": "Tray.io", "desc": "Integration platform", "category": "Automation", "url": "https://tray.io"},
    {"name": "Celigo", "desc": "Integration platform", "category": "Automation", "url": "https://celigo.com"},
    {"name": "SnapLogic", "desc": "Integration platform", "category": "Automation", "url": "https://snaplogic.com"},
    {"name": "Boomi", "desc": "Integration platform", "category": "Automation", "url": "https://boomi.com"},
    {"name": "MuleSoft", "desc": "API integration", "category": "Automation", "url": "https://mulesoft.com"},
    {"name": "Informatica", "desc": "Data integration", "category": "Automation", "url": "https://informatica.com"},
    {"name": "Talend", "desc": "Data integration", "category": "Automation", "url": "https://talend.com"},
    {"name": "Matillion", "desc": "Data transformation", "category": "Automation", "url": "https://matillion.com"},
    {"name": "Rivery", "desc": "DataOps platform", "category": "Automation", "url": "https://rivery.io"},
    {"name": "Portable", "desc": "ELT connectors", "category": "Automation", "url": "https://portable.io"},
    {"name": "Estuary", "desc": "Real-time ETL", "category": "Automation", "url": "https://estuary.dev"},
    {"name": "Hevo", "desc": "Data pipeline", "category": "Automation", "url": "https://hevodata.com"},
    {"name": "Panoply", "desc": "Data warehouse", "category": "Data", "url": "https://panoply.io"},
    {"name": "Mozart Data", "desc": "Data stack", "category": "Data", "url": "https://mozartdata.com"},
    {"name": "Polytomic", "desc": "Data sync", "category": "Data", "url": "https://polytomic.com"},
    {"name": "Grouparoo", "desc": "Data sync", "category": "Data", "url": "https://grouparoo.com"},
    {"name": "Prequel", "desc": "Data sharing", "category": "Data", "url": "https://prequel.co"},
    {"name": "Vendia", "desc": "Data sharing", "category": "Data", "url": "https://vendia.com"},
    {"name": "Immuta", "desc": "Data access", "category": "Data", "url": "https://immuta.com"},
    
    # Healthcare & Medical (40)
    {"name": "Healthie", "desc": "Healthcare platform", "category": "Healthcare", "url": "https://gethealthie.com"},
    {"name": "DrChrono", "desc": "EHR platform", "category": "Healthcare", "url": "https://drchrono.com"},
    {"name": "Practice Better", "desc": "Health practice", "category": "Healthcare", "url": "https://practicebetter.io"},
    {"name": "Jane App", "desc": "Practice management", "category": "Healthcare", "url": "https://jane.app"},
    {"name": "SimplePractice", "desc": "Practice management", "category": "Healthcare", "url": "https://simplepractice.com"},
    {"name": "Kareo", "desc": "Medical billing", "category": "Healthcare", "url": "https://kareo.com"},
    {"name": "athenahealth", "desc": "Healthcare network", "category": "Healthcare", "url": "https://athenahealth.com"},
    {"name": "Epic", "desc": "EHR system", "category": "Healthcare", "url": "https://epic.com"},
    {"name": "Cerner", "desc": "Health IT", "category": "Healthcare", "url": "https://cerner.com"},
    {"name": "Allscripts", "desc": "Healthcare solutions", "category": "Healthcare", "url": "https://allscripts.com"},
    {"name": "Meditech", "desc": "EHR system", "category": "Healthcare", "url": "https://meditech.com"},
    {"name": "Veradigm", "desc": "Healthcare data", "category": "Healthcare", "url": "https://veradigm.com"},
    {"name": "Redox", "desc": "Healthcare integration", "category": "Healthcare", "url": "https://redoxengine.com"},
    {"name": "Particle Health", "desc": "Healthcare data", "category": "Healthcare", "url": "https://particlehealth.com"},
    {"name": "Flexpa", "desc": "Health data API", "category": "Healthcare", "url": "https://flexpa.com"},
    {"name": "1upHealth", "desc": "Healthcare API", "category": "Healthcare", "url": "https://1up.health"},
    {"name": "Health Gorilla", "desc": "Health data network", "category": "Healthcare", "url": "https://healthgorilla.com"},
    {"name": "Human API", "desc": "Health data", "category": "Healthcare", "url": "https://humanapi.co"},
    {"name": "Validic", "desc": "Health data", "category": "Healthcare", "url": "https://validic.com"},
    {"name": "Vital", "desc": "Health data API", "category": "Healthcare", "url": "https://tryvital.io"},
    {"name": "Terra", "desc": "Wearable data API", "category": "Healthcare", "url": "https://tryterra.co"},
    {"name": "Gyroscope", "desc": "Health tracking", "category": "Healthcare", "url": "https://gyrosco.pe"},
    {"name": "Oura", "desc": "Sleep tracking", "category": "Healthcare", "url": "https://ouraring.com"},
    {"name": "Whoop", "desc": "Fitness tracking", "category": "Healthcare", "url": "https://whoop.com"},
    {"name": "Fitbit", "desc": "Fitness API", "category": "Healthcare", "url": "https://fitbit.com"},
    {"name": "Garmin", "desc": "Fitness API", "category": "Healthcare", "url": "https://developer.garmin.com"},
    {"name": "Strava", "desc": "Fitness API", "category": "Healthcare", "url": "https://strava.com"},
    {"name": "MyFitnessPal", "desc": "Nutrition tracking", "category": "Healthcare", "url": "https://myfitnesspal.com"},
    {"name": "Nutritionix", "desc": "Nutrition API", "category": "Healthcare", "url": "https://nutritionix.com"},
    {"name": "Edamam", "desc": "Food database API", "category": "Healthcare", "url": "https://edamam.com"},
    {"name": "Spoonacular", "desc": "Food API", "category": "Healthcare", "url": "https://spoonacular.com"},
    {"name": "FatSecret", "desc": "Nutrition API", "category": "Healthcare", "url": "https://fatsecret.com"},
    {"name": "Open Food Facts", "desc": "Food database", "category": "Healthcare", "url": "https://openfoodfacts.org"},
    {"name": "USDA FoodData", "desc": "Nutrition database", "category": "Healthcare", "url": "https://fdc.nal.usda.gov"},
    {"name": "PubMed", "desc": "Medical literature", "category": "Healthcare", "url": "https://pubmed.ncbi.nlm.nih.gov"},
    {"name": "ClinicalTrials", "desc": "Clinical trials", "category": "Healthcare", "url": "https://clinicaltrials.gov"},
    {"name": "OpenFDA", "desc": "FDA data API", "category": "Healthcare", "url": "https://open.fda.gov"},
    {"name": "RxNorm", "desc": "Drug database", "category": "Healthcare", "url": "https://rxnorm.nlm.nih.gov"},
    {"name": "DrugBank", "desc": "Drug database", "category": "Healthcare", "url": "https://drugbank.com"},
    {"name": "OpenMRS", "desc": "Medical records", "category": "Healthcare", "url": "https://openmrs.org"},
    
    # Legal & Compliance (30)
    {"name": "Clio", "desc": "Legal practice management", "category": "Legal", "url": "https://clio.com"},
    {"name": "PracticePanther", "desc": "Legal software", "category": "Legal", "url": "https://practicepanther.com"},
    {"name": "MyCase", "desc": "Legal practice", "category": "Legal", "url": "https://mycase.com"},
    {"name": "Rocket Lawyer", "desc": "Legal services", "category": "Legal", "url": "https://rocketlawyer.com"},
    {"name": "LegalZoom", "desc": "Legal services", "category": "Legal", "url": "https://legalzoom.com"},
    {"name": "Ironclad", "desc": "Contract management", "category": "Legal", "url": "https://ironcladapp.com"},
    {"name": "DocuSign", "desc": "E-signature", "category": "Legal", "url": "https://docusign.com"},
    {"name": "PandaDoc", "desc": "Document workflow", "category": "Legal", "url": "https://pandadoc.com"},
    {"name": "HelloSign", "desc": "E-signature", "category": "Legal", "url": "https://hellosign.com"},
    {"name": "SignNow", "desc": "E-signature", "category": "Legal", "url": "https://signnow.com"},
    {"name": "Adobe Sign", "desc": "E-signature", "category": "Legal", "url": "https://acrobat.adobe.com/sign"},
    {"name": "Juro", "desc": "Contract automation", "category": "Legal", "url": "https://juro.com"},
    {"name": "Concord", "desc": "Contract management", "category": "Legal", "url": "https://concordnow.com"},
    {"name": "Agiloft", "desc": "Contract lifecycle", "category": "Legal", "url": "https://agiloft.com"},
    {"name": "ContractPodAi", "desc": "Contract AI", "category": "Legal", "url": "https://contractpodai.com"},
    {"name": "Kira Systems", "desc": "Contract analysis", "category": "Legal", "url": "https://kirasystems.com"},
    {"name": "Luminance", "desc": "Legal AI", "category": "Legal", "url": "https://luminance.com"},
    {"name": "Eigen", "desc": "Document AI", "category": "Legal", "url": "https://eigen.co"},
    {"name": "Lexion", "desc": "Contract management", "category": "Legal", "url": "https://lexion.ai"},
    {"name": "LinkSquares", "desc": "Contract analytics", "category": "Legal", "url": "https://linksquares.com"},
    {"name": "Checkbox", "desc": "Legal automation", "category": "Legal", "url": "https://checkbox.ai"},
    {"name": "Neota Logic", "desc": "Legal automation", "category": "Legal", "url": "https://neotalogic.com"},
    {"name": "Josef", "desc": "Legal automation", "category": "Legal", "url": "https://joseflegal.com"},
    {"name": "Drata", "desc": "Compliance automation", "category": "Compliance", "url": "https://drata.com"},
    {"name": "Vanta", "desc": "Security compliance", "category": "Compliance", "url": "https://vanta.com"},
    {"name": "Secureframe", "desc": "Compliance automation", "category": "Compliance", "url": "https://secureframe.com"},
    {"name": "Tugboat Logic", "desc": "Security assurance", "category": "Compliance", "url": "https://tugboatlogic.com"},
    {"name": "Laika", "desc": "Compliance platform", "category": "Compliance", "url": "https://heylaika.com"},
    {"name": "Scrut", "desc": "Compliance automation", "category": "Compliance", "url": "https://scrut.io"},
    {"name": "Sprinto", "desc": "Compliance automation", "category": "Compliance", "url": "https://sprinto.com"},
    
    # Real Estate & Property (30)
    {"name": "Zillow", "desc": "Real estate data", "category": "Real Estate", "url": "https://zillow.com"},
    {"name": "Redfin", "desc": "Real estate data", "category": "Real Estate", "url": "https://redfin.com"},
    {"name": "Realtor.com", "desc": "Real estate listings", "category": "Real Estate", "url": "https://realtor.com"},
    {"name": "Apartment List", "desc": "Rental listings", "category": "Real Estate", "url": "https://apartmentlist.com"},
    {"name": "Rentometer", "desc": "Rent analysis", "category": "Real Estate", "url": "https://rentometer.com"},
    {"name": "HouseCanary", "desc": "Property analytics", "category": "Real Estate", "url": "https://housecanary.com"},
    {"name": "CoreLogic", "desc": "Property data", "category": "Real Estate", "url": "https://corelogic.com"},
    {"name": "ATTOM", "desc": "Property data", "category": "Real Estate", "url": "https://attomdata.com"},
    {"name": "Reonomy", "desc": "Commercial real estate", "category": "Real Estate", "url": "https://reonomy.com"},
    {"name": "CoStar", "desc": "Commercial real estate", "category": "Real Estate", "url": "https://costar.com"},
    {"name": "Yardi", "desc": "Property management", "category": "Real Estate", "url": "https://yardi.com"},
    {"name": "AppFolio", "desc": "Property management", "category": "Real Estate", "url": "https://appfolio.com"},
    {"name": "Buildium", "desc": "Property management", "category": "Real Estate", "url": "https://buildium.com"},
    {"name": "RentRedi", "desc": "Landlord software", "category": "Real Estate", "url": "https://rentredi.com"},
    {"name": "Avail", "desc": "Landlord platform", "category": "Real Estate", "url": "https://avail.co"},
    {"name": "TurboTenant", "desc": "Landlord software", "category": "Real Estate", "url": "https://turbotenant.com"},
    {"name": "Cozy", "desc": "Rental management", "category": "Real Estate", "url": "https://cozy.co"},
    {"name": "DoorLoop", "desc": "Property management", "category": "Real Estate", "url": "https://doorloop.com"},
    {"name": "Propertyware", "desc": "Property management", "category": "Real Estate", "url": "https://propertyware.com"},
    {"name": "Entrata", "desc": "Property management", "category": "Real Estate", "url": "https://entrata.com"},
    {"name": "RealPage", "desc": "Real estate software", "category": "Real Estate", "url": "https://realpage.com"},
    {"name": "MRI Software", "desc": "Real estate software", "category": "Real Estate", "url": "https://mrisoftware.com"},
    {"name": "Juniper Square", "desc": "Investment management", "category": "Real Estate", "url": "https://junipersquare.com"},
    {"name": "Dealpath", "desc": "Deal management", "category": "Real Estate", "url": "https://dealpath.com"},
    {"name": "Skyline AI", "desc": "Real estate AI", "category": "Real Estate", "url": "https://skyline.ai"},
    {"name": "Cherre", "desc": "Real estate data", "category": "Real Estate", "url": "https://cherre.com"},
    {"name": "Enodo", "desc": "Multifamily analytics", "category": "Real Estate", "url": "https://enodoinc.com"},
    {"name": "CREXi", "desc": "Commercial marketplace", "category": "Real Estate", "url": "https://crexi.com"},
    {"name": "Ten-X", "desc": "Real estate auction", "category": "Real Estate", "url": "https://ten-x.com"},
    {"name": "Roofstock", "desc": "SFR marketplace", "category": "Real Estate", "url": "https://roofstock.com"},
    
    # Education & Learning (30)
    {"name": "Canvas", "desc": "Learning management", "category": "Education", "url": "https://instructure.com/canvas"},
    {"name": "Blackboard", "desc": "Learning platform", "category": "Education", "url": "https://blackboard.com"},
    {"name": "Moodle", "desc": "Open LMS", "category": "Education", "url": "https://moodle.org"},
    {"name": "Schoology", "desc": "Learning management", "category": "Education", "url": "https://schoology.com"},
    {"name": "Google Classroom", "desc": "Education platform", "category": "Education", "url": "https://classroom.google.com"},
    {"name": "Edmodo", "desc": "Learning platform", "category": "Education", "url": "https://edmodo.com"},
    {"name": "Seesaw", "desc": "Learning portfolio", "category": "Education", "url": "https://seesaw.me"},
    {"name": "ClassDojo", "desc": "Classroom management", "category": "Education", "url": "https://classdojo.com"},
    {"name": "Remind", "desc": "School communication", "category": "Education", "url": "https://remind.com"},
    {"name": "Bloomz", "desc": "School communication", "category": "Education", "url": "https://bloomz.com"},
    {"name": "ParentSquare", "desc": "School communication", "category": "Education", "url": "https://parentsquare.com"},
    {"name": "Clever", "desc": "Digital learning", "category": "Education", "url": "https://clever.com"},
    {"name": "ClassLink", "desc": "Single sign-on", "category": "Education", "url": "https://classlink.com"},
    {"name": "Infinite Campus", "desc": "Student information", "category": "Education", "url": "https://infinitecampus.com"},
    {"name": "PowerSchool", "desc": "Education technology", "category": "Education", "url": "https://powerschool.com"},
    {"name": "Skyward", "desc": "School management", "category": "Education", "url": "https://skyward.com"},
    {"name": "Teachable", "desc": "Course platform", "category": "Education", "url": "https://teachable.com"},
    {"name": "Thinkific", "desc": "Course creation", "category": "Education", "url": "https://thinkific.com"},
    {"name": "Kajabi", "desc": "Knowledge commerce", "category": "Education", "url": "https://kajabi.com"},
    {"name": "Podia", "desc": "Digital products", "category": "Education", "url": "https://podia.com"},
    {"name": "LearnWorlds", "desc": "Online school", "category": "Education", "url": "https://learnworlds.com"},
    {"name": "Mighty Networks", "desc": "Community platform", "category": "Education", "url": "https://mightynetworks.com"},
    {"name": "Circle", "desc": "Community platform", "category": "Education", "url": "https://circle.so"},
    {"name": "Skool", "desc": "Community platform", "category": "Education", "url": "https://skool.com"},
    {"name": "Coursera", "desc": "Online learning", "category": "Education", "url": "https://coursera.org"},
    {"name": "Udemy", "desc": "Course marketplace", "category": "Education", "url": "https://udemy.com"},
    {"name": "edX", "desc": "Online learning", "category": "Education", "url": "https://edx.org"},
    {"name": "LinkedIn Learning", "desc": "Professional learning", "category": "Education", "url": "https://linkedin.com/learning"},
    {"name": "Skillshare", "desc": "Creative learning", "category": "Education", "url": "https://skillshare.com"},
    {"name": "MasterClass", "desc": "Expert classes", "category": "Education", "url": "https://masterclass.com"},
    
    # Travel & Transportation (30)
    {"name": "Amadeus", "desc": "Travel technology", "category": "Travel", "url": "https://amadeus.com"},
    {"name": "Sabre", "desc": "Travel solutions", "category": "Travel", "url": "https://sabre.com"},
    {"name": "Travelport", "desc": "Travel commerce", "category": "Travel", "url": "https://travelport.com"},
    {"name": "Skyscanner", "desc": "Flight search", "category": "Travel", "url": "https://skyscanner.com"},
    {"name": "Kiwi.com", "desc": "Travel booking", "category": "Travel", "url": "https://kiwi.com"},
    {"name": "Rome2Rio", "desc": "Travel planning", "category": "Travel", "url": "https://rome2rio.com"},
    {"name": "FlightAware", "desc": "Flight tracking", "category": "Travel", "url": "https://flightaware.com"},
    {"name": "AviationStack", "desc": "Flight data", "category": "Travel", "url": "https://aviationstack.com"},
    {"name": "OpenSky", "desc": "Flight tracking", "category": "Travel", "url": "https://opensky-network.org"},
    {"name": "ADS-B Exchange", "desc": "Aircraft tracking", "category": "Travel", "url": "https://adsbexchange.com"},
    {"name": "Booking.com", "desc": "Hotel booking", "category": "Travel", "url": "https://booking.com"},
    {"name": "Hotels.com", "desc": "Hotel booking", "category": "Travel", "url": "https://hotels.com"},
    {"name": "Expedia", "desc": "Travel booking", "category": "Travel", "url": "https://expedia.com"},
    {"name": "Airbnb", "desc": "Vacation rentals", "category": "Travel", "url": "https://airbnb.com"},
    {"name": "Vrbo", "desc": "Vacation rentals", "category": "Travel", "url": "https://vrbo.com"},
    {"name": "Tripadvisor", "desc": "Travel reviews", "category": "Travel", "url": "https://tripadvisor.com"},
    {"name": "Yelp", "desc": "Business reviews", "category": "Travel", "url": "https://yelp.com"},
    {"name": "Foursquare", "desc": "Location data", "category": "Travel", "url": "https://foursquare.com"},
    {"name": "HERE", "desc": "Location platform", "category": "Travel", "url": "https://here.com"},
    {"name": "TomTom", "desc": "Navigation", "category": "Travel", "url": "https://tomtom.com"},
    {"name": "Mapbox", "desc": "Maps platform", "category": "Travel", "url": "https://mapbox.com"},
    {"name": "Google Maps", "desc": "Maps platform", "category": "Travel", "url": "https://maps.google.com"},
    {"name": "Apple Maps", "desc": "Maps platform", "category": "Travel", "url": "https://developer.apple.com/maps"},
    {"name": "OpenStreetMap", "desc": "Open maps", "category": "Travel", "url": "https://openstreetmap.org"},
    {"name": "What3Words", "desc": "Location addressing", "category": "Travel", "url": "https://what3words.com"},
    {"name": "Uber", "desc": "Ride-hailing", "category": "Travel", "url": "https://uber.com"},
    {"name": "Lyft", "desc": "Ride-hailing", "category": "Travel", "url": "https://lyft.com"},
    {"name": "Bolt", "desc": "Ride-hailing", "category": "Travel", "url": "https://bolt.eu"},
    {"name": "Lime", "desc": "Micromobility", "category": "Travel", "url": "https://li.me"},
    {"name": "Bird", "desc": "Micromobility", "category": "Travel", "url": "https://bird.co"},
    
    # Gaming & Entertainment (40)
    {"name": "Steam", "desc": "Gaming platform", "category": "Gaming", "url": "https://store.steampowered.com"},
    {"name": "Epic Games", "desc": "Gaming platform", "category": "Gaming", "url": "https://epicgames.com"},
    {"name": "GOG", "desc": "Gaming platform", "category": "Gaming", "url": "https://gog.com"},
    {"name": "Humble Bundle", "desc": "Game bundles", "category": "Gaming", "url": "https://humblebundle.com"},
    {"name": "itch.io", "desc": "Indie games", "category": "Gaming", "url": "https://itch.io"},
    {"name": "IGDB", "desc": "Game database", "category": "Gaming", "url": "https://igdb.com"},
    {"name": "RAWG", "desc": "Game database", "category": "Gaming", "url": "https://rawg.io"},
    {"name": "Giant Bomb", "desc": "Game database", "category": "Gaming", "url": "https://giantbomb.com"},
    {"name": "Twitch", "desc": "Streaming platform", "category": "Gaming", "url": "https://twitch.tv"},
    {"name": "YouTube Gaming", "desc": "Gaming streaming", "category": "Gaming", "url": "https://youtube.com/gaming"},
    {"name": "Kick", "desc": "Streaming platform", "category": "Gaming", "url": "https://kick.com"},
    {"name": "Discord", "desc": "Gaming community", "category": "Gaming", "url": "https://discord.com"},
    {"name": "Overwolf", "desc": "Gaming apps", "category": "Gaming", "url": "https://overwolf.com"},
    {"name": "Playfab", "desc": "Game backend", "category": "Gaming", "url": "https://playfab.com"},
    {"name": "GameSparks", "desc": "Game backend", "category": "Gaming", "url": "https://gamesparks.com"},
    {"name": "Photon", "desc": "Multiplayer engine", "category": "Gaming", "url": "https://photonengine.com"},
    {"name": "Nakama", "desc": "Game server", "category": "Gaming", "url": "https://heroiclabs.com"},
    {"name": "Beamable", "desc": "Live game backend", "category": "Gaming", "url": "https://beamable.com"},
    {"name": "Lootlocker", "desc": "Game backend", "category": "Gaming", "url": "https://lootlocker.io"},
    {"name": "Braincloud", "desc": "Game backend", "category": "Gaming", "url": "https://getbraincloud.com"},
    {"name": "Spotify", "desc": "Music streaming", "category": "Entertainment", "url": "https://spotify.com"},
    {"name": "Apple Music", "desc": "Music streaming", "category": "Entertainment", "url": "https://apple.com/music"},
    {"name": "Deezer", "desc": "Music streaming", "category": "Entertainment", "url": "https://deezer.com"},
    {"name": "SoundCloud", "desc": "Audio platform", "category": "Entertainment", "url": "https://soundcloud.com"},
    {"name": "Bandcamp", "desc": "Music platform", "category": "Entertainment", "url": "https://bandcamp.com"},
    {"name": "Last.fm", "desc": "Music scrobbling", "category": "Entertainment", "url": "https://last.fm"},
    {"name": "Genius", "desc": "Song lyrics", "category": "Entertainment", "url": "https://genius.com"},
    {"name": "Musixmatch", "desc": "Lyrics API", "category": "Entertainment", "url": "https://musixmatch.com"},
    {"name": "Shazam", "desc": "Music recognition", "category": "Entertainment", "url": "https://shazam.com"},
    {"name": "ACRCloud", "desc": "Audio recognition", "category": "Entertainment", "url": "https://acrcloud.com"},
    {"name": "Netflix", "desc": "Video streaming", "category": "Entertainment", "url": "https://netflix.com"},
    {"name": "Disney+", "desc": "Video streaming", "category": "Entertainment", "url": "https://disneyplus.com"},
    {"name": "HBO Max", "desc": "Video streaming", "category": "Entertainment", "url": "https://max.com"},
    {"name": "Amazon Prime", "desc": "Video streaming", "category": "Entertainment", "url": "https://primevideo.com"},
    {"name": "Hulu", "desc": "Video streaming", "category": "Entertainment", "url": "https://hulu.com"},
    {"name": "TMDb", "desc": "Movie database", "category": "Entertainment", "url": "https://themoviedb.org"},
    {"name": "OMDb", "desc": "Movie database", "category": "Entertainment", "url": "https://omdbapi.com"},
    {"name": "TVMaze", "desc": "TV database", "category": "Entertainment", "url": "https://tvmaze.com"},
    {"name": "Trakt", "desc": "TV tracking", "category": "Entertainment", "url": "https://trakt.tv"},
    {"name": "Letterboxd", "desc": "Film social", "category": "Entertainment", "url": "https://letterboxd.com"},
    
    # Sports & Fitness (30)
    {"name": "ESPN", "desc": "Sports data", "category": "Sports", "url": "https://espn.com"},
    {"name": "SportRadar", "desc": "Sports data", "category": "Sports", "url": "https://sportradar.com"},
    {"name": "Stats Perform", "desc": "Sports analytics", "category": "Sports", "url": "https://statsperform.com"},
    {"name": "API-Football", "desc": "Football data", "category": "Sports", "url": "https://api-football.com"},
    {"name": "Football-Data", "desc": "Football data", "category": "Sports", "url": "https://football-data.org"},
    {"name": "NBA", "desc": "Basketball data", "category": "Sports", "url": "https://nba.com"},
    {"name": "NFL", "desc": "Football data", "category": "Sports", "url": "https://nfl.com"},
    {"name": "MLB", "desc": "Baseball data", "category": "Sports", "url": "https://mlb.com"},
    {"name": "NHL", "desc": "Hockey data", "category": "Sports", "url": "https://nhl.com"},
    {"name": "F1", "desc": "Formula 1 data", "category": "Sports", "url": "https://formula1.com"},
    {"name": "Ergast", "desc": "F1 historical data", "category": "Sports", "url": "https://ergast.com"},
    {"name": "UFC", "desc": "MMA data", "category": "Sports", "url": "https://ufc.com"},
    {"name": "Oddsjam", "desc": "Sports betting", "category": "Sports", "url": "https://oddsjam.com"},
    {"name": "The Odds API", "desc": "Betting odds", "category": "Sports", "url": "https://the-odds-api.com"},
    {"name": "BetRadar", "desc": "Betting data", "category": "Sports", "url": "https://betradar.com"},
    {"name": "Mindbody", "desc": "Fitness business", "category": "Fitness", "url": "https://mindbody.io"},
    {"name": "Gympass", "desc": "Fitness benefits", "category": "Fitness", "url": "https://gympass.com"},
    {"name": "ClassPass", "desc": "Fitness membership", "category": "Fitness", "url": "https://classpass.com"},
    {"name": "Peloton", "desc": "Connected fitness", "category": "Fitness", "url": "https://onepeloton.com"},
    {"name": "Zwift", "desc": "Virtual cycling", "category": "Fitness", "url": "https://zwift.com"},
    {"name": "TrainerRoad", "desc": "Cycling training", "category": "Fitness", "url": "https://trainerroad.com"},
    {"name": "Training Peaks", "desc": "Athletic training", "category": "Fitness", "url": "https://trainingpeaks.com"},
    {"name": "Final Surge", "desc": "Athletic training", "category": "Fitness", "url": "https://finalsurge.com"},
    {"name": "Today's Plan", "desc": "Endurance training", "category": "Fitness", "url": "https://todaysplan.com.au"},
    {"name": "Intervals.icu", "desc": "Training analytics", "category": "Fitness", "url": "https://intervals.icu"},
    {"name": "Runalyze", "desc": "Running analytics", "category": "Fitness", "url": "https://runalyze.com"},
    {"name": "Smashrun", "desc": "Running analytics", "category": "Fitness", "url": "https://smashrun.com"},
    {"name": "Ride With GPS", "desc": "Cycling platform", "category": "Fitness", "url": "https://ridewithgps.com"},
    {"name": "Komoot", "desc": "Route planning", "category": "Fitness", "url": "https://komoot.com"},
    {"name": "AllTrails", "desc": "Trail database", "category": "Fitness", "url": "https://alltrails.com"},

    # News & Media (30)
    {"name": "NewsAPI", "desc": "News aggregation", "category": "News", "url": "https://newsapi.org"},
    {"name": "GNews", "desc": "News API", "category": "News", "url": "https://gnews.io"},
    {"name": "Currents", "desc": "News API", "category": "News", "url": "https://currentsapi.services"},
    {"name": "Newscatcher", "desc": "News API", "category": "News", "url": "https://newscatcherapi.com"},
    {"name": "Mediastack", "desc": "News data", "category": "News", "url": "https://mediastack.com"},
    {"name": "Perigon", "desc": "News API", "category": "News", "url": "https://goperigon.com"},
    {"name": "Event Registry", "desc": "News analytics", "category": "News", "url": "https://eventregistry.org"},
    {"name": "GDELT", "desc": "Global events", "category": "News", "url": "https://gdeltproject.org"},
    {"name": "RSS", "desc": "Feed syndication", "category": "News", "url": "https://rssboard.org"},
    {"name": "Feedly", "desc": "RSS reader", "category": "News", "url": "https://feedly.com"},
    {"name": "Inoreader", "desc": "RSS reader", "category": "News", "url": "https://inoreader.com"},
    {"name": "Readwise", "desc": "Reading highlights", "category": "News", "url": "https://readwise.io"},
    {"name": "Instapaper", "desc": "Read later", "category": "News", "url": "https://instapaper.com"},
    {"name": "Pocket", "desc": "Read later", "category": "News", "url": "https://getpocket.com"},
    {"name": "Matter", "desc": "Reading app", "category": "News", "url": "https://hq.getmatter.com"},
    {"name": "Hacker News", "desc": "Tech news", "category": "News", "url": "https://news.ycombinator.com"},
    {"name": "Reddit", "desc": "Social news", "category": "News", "url": "https://reddit.com"},
    {"name": "Product Hunt", "desc": "Product discovery", "category": "News", "url": "https://producthunt.com"},
    {"name": "Lobsters", "desc": "Tech news", "category": "News", "url": "https://lobste.rs"},
    {"name": "DEV", "desc": "Developer community", "category": "News", "url": "https://dev.to"},
    {"name": "Hashnode", "desc": "Developer blogs", "category": "News", "url": "https://hashnode.com"},
    {"name": "Medium", "desc": "Publishing platform", "category": "News", "url": "https://medium.com"},
    {"name": "Substack", "desc": "Newsletter platform", "category": "News", "url": "https://substack.com"},
    {"name": "Revue", "desc": "Newsletter platform", "category": "News", "url": "https://getrevue.co"},
    {"name": "TechCrunch", "desc": "Tech news", "category": "News", "url": "https://techcrunch.com"},
    {"name": "The Verge", "desc": "Tech news", "category": "News", "url": "https://theverge.com"},
    {"name": "Wired", "desc": "Tech culture", "category": "News", "url": "https://wired.com"},
    {"name": "Ars Technica", "desc": "Tech news", "category": "News", "url": "https://arstechnica.com"},
    {"name": "Engadget", "desc": "Tech news", "category": "News", "url": "https://engadget.com"},
    {"name": "Gizmodo", "desc": "Tech news", "category": "News", "url": "https://gizmodo.com"},
    
    # Finance & Accounting (40)
    {"name": "Plaid", "desc": "Banking API", "category": "Finance", "url": "https://plaid.com"},
    {"name": "Teller", "desc": "Banking API", "category": "Finance", "url": "https://teller.io"},
    {"name": "MX", "desc": "Financial data", "category": "Finance", "url": "https://mx.com"},
    {"name": "Finicity", "desc": "Financial data", "category": "Finance", "url": "https://finicity.com"},
    {"name": "Yodlee", "desc": "Financial data", "category": "Finance", "url": "https://yodlee.com"},
    {"name": "Akoya", "desc": "Financial data", "category": "Finance", "url": "https://akoya.com"},
    {"name": "Argyle", "desc": "Employment data", "category": "Finance", "url": "https://argyle.com"},
    {"name": "Pinwheel", "desc": "Payroll data", "category": "Finance", "url": "https://pinwheelapi.com"},
    {"name": "Atomic", "desc": "Payroll connectivity", "category": "Finance", "url": "https://atomicfi.com"},
    {"name": "Truework", "desc": "Income verification", "category": "Finance", "url": "https://truework.com"},
    {"name": "Heron Data", "desc": "Transaction data", "category": "Finance", "url": "https://herondata.io"},
    {"name": "Spade", "desc": "Transaction enrichment", "category": "Finance", "url": "https://spade.com"},
    {"name": "Ntropy", "desc": "Transaction AI", "category": "Finance", "url": "https://ntropy.com"},
    {"name": "QuickBooks", "desc": "Accounting software", "category": "Finance", "url": "https://quickbooks.intuit.com"},
    {"name": "Xero", "desc": "Accounting software", "category": "Finance", "url": "https://xero.com"},
    {"name": "FreshBooks", "desc": "Invoicing software", "category": "Finance", "url": "https://freshbooks.com"},
    {"name": "Wave", "desc": "Free accounting", "category": "Finance", "url": "https://waveapps.com"},
    {"name": "Sage", "desc": "Business software", "category": "Finance", "url": "https://sage.com"},
    {"name": "NetSuite", "desc": "ERP system", "category": "Finance", "url": "https://netsuite.com"},
    {"name": "Zoho Books", "desc": "Accounting software", "category": "Finance", "url": "https://zoho.com/books"},
    {"name": "Mercury", "desc": "Banking for startups", "category": "Finance", "url": "https://mercury.com"},
    {"name": "Brex", "desc": "Corporate cards", "category": "Finance", "url": "https://brex.com"},
    {"name": "Ramp", "desc": "Corporate cards", "category": "Finance", "url": "https://ramp.com"},
    {"name": "Airbase", "desc": "Spend management", "category": "Finance", "url": "https://airbase.io"},
    {"name": "Expensify", "desc": "Expense management", "category": "Finance", "url": "https://expensify.com"},
    {"name": "Divvy", "desc": "Expense management", "category": "Finance", "url": "https://divvy.co"},
    {"name": "Zip", "desc": "Procurement", "category": "Finance", "url": "https://ziphq.com"},
    {"name": "Coupa", "desc": "Business spend", "category": "Finance", "url": "https://coupa.com"},
    {"name": "SAP Ariba", "desc": "Procurement", "category": "Finance", "url": "https://ariba.com"},
    {"name": "Bill.com", "desc": "AP/AR automation", "category": "Finance", "url": "https://bill.com"},
    {"name": "Stampli", "desc": "AP automation", "category": "Finance", "url": "https://stampli.com"},
    {"name": "Tipalti", "desc": "Payables automation", "category": "Finance", "url": "https://tipalti.com"},
    {"name": "Melio", "desc": "B2B payments", "category": "Finance", "url": "https://meliopayments.com"},
    {"name": "Routable", "desc": "B2B payments", "category": "Finance", "url": "https://routable.com"},
    {"name": "Gusto", "desc": "Payroll", "category": "Finance", "url": "https://gusto.com"},
    {"name": "Rippling", "desc": "HR and payroll", "category": "Finance", "url": "https://rippling.com"},
    {"name": "Deel", "desc": "Global payroll", "category": "Finance", "url": "https://deel.com"},
    {"name": "Remote", "desc": "Global HR", "category": "Finance", "url": "https://remote.com"},
    {"name": "Papaya Global", "desc": "Global payroll", "category": "Finance", "url": "https://papayaglobal.com"},
    {"name": "Pilot", "desc": "Bookkeeping", "category": "Finance", "url": "https://pilot.com"},
]

def main():
    print("🦞 APIClaw Night Expansion - Batch 2")
    print("=" * 50)
    
    registry = load_registry()
    existing_ids = get_existing_ids(registry)
    
    print(f"Current APIs: {len(registry['apis'])}")
    
    added = 0
    for api in NEW_APIS:
        api_id = generate_id(api['name'])
        
        if api_id in existing_ids:
            continue
        
        new_api = {
            "id": api_id,
            "name": api['name'],
            "description": api['desc'],
            "category": api['category'],
            "authType": "apiKey",
            "baseUrl": api['url'],
            "docsUrl": api['url'],
            "addedAt": datetime.now().isoformat()
        }
        
        registry['apis'].append(new_api)
        existing_ids.add(api_id)
        added += 1
    
    save_registry(registry)
    
    print(f"Added: +{added} APIs")
    print(f"Total: {len(registry['apis'])}")
    
    return added

if __name__ == "__main__":
    main()
