#!/usr/bin/env python3
"""APIClaw Night Mega Batch - 2026-02-23 04:00 - Target 1000+ APIs"""

import json
import re
from datetime import datetime

# Load current registry
with open('/Users/gustavhemmingsson/Projects/apiclaw/src/registry/apis.json', 'r') as f:
    registry = json.load(f)

existing_ids = {api['id'] for api in registry['apis']}
initial_count = len(existing_ids)
new_apis = []

def add_api(name, desc, category, url, auth="unknown"):
    api_id = re.sub(r'[^a-z0-9]', '-', name.lower()).strip('-')
    api_id = re.sub(r'-+', '-', api_id)
    if api_id not in existing_ids and api_id and len(api_id) > 2:
        existing_ids.add(api_id)
        new_apis.append({
            "id": api_id,
            "name": name,
            "description": desc[:200] if len(desc) > 200 else desc,
            "category": category,
            "auth": auth,
            "https": True,
            "cors": "unknown",
            "link": url,
            "pricing": "unknown",
            "keywords": []
        })
        return True
    return False

# ===== MASSIVE API EXPANSION =====

# ---------- AI & Machine Learning (100+) ----------
ai_apis = [
    ("OpenAI GPT-4", "GPT-4 language model API", "https://platform.openai.com/docs/api-reference"),
    ("OpenAI DALL-E", "AI image generation", "https://platform.openai.com/docs/guides/images"),
    ("OpenAI Whisper", "Speech recognition API", "https://platform.openai.com/docs/guides/speech-to-text"),
    ("OpenAI TTS", "Text to speech API", "https://platform.openai.com/docs/guides/text-to-speech"),
    ("OpenAI Embeddings", "Vector embeddings API", "https://platform.openai.com/docs/guides/embeddings"),
    ("Claude API", "Anthropic Claude AI", "https://docs.anthropic.com/claude/reference"),
    ("Gemini API", "Google Gemini AI", "https://ai.google.dev/api/rest"),
    ("Llama API", "Meta Llama models", "https://llama.meta.com/"),
    ("Cohere Generate", "Text generation AI", "https://docs.cohere.ai/reference/generate"),
    ("Cohere Embed", "Text embeddings", "https://docs.cohere.ai/reference/embed"),
    ("Cohere Rerank", "Search reranking", "https://docs.cohere.ai/reference/rerank"),
    ("Stability AI SDXL", "Stable Diffusion XL", "https://platform.stability.ai/docs/api-reference"),
    ("Stability AI Video", "Video generation AI", "https://platform.stability.ai/docs/api-reference"),
    ("Midjourney API", "AI art generation", "https://docs.midjourney.com/"),
    ("FLUX AI", "Fast image generation", "https://blackforestlabs.ai/"),
    ("Leonardo AI", "AI image generation", "https://docs.leonardo.ai/"),
    ("Runway ML", "Creative AI tools", "https://docs.runwayml.com/"),
    ("Ideogram AI", "Text-to-image AI", "https://ideogram.ai/api"),
    ("ElevenLabs", "Voice AI synthesis", "https://elevenlabs.io/docs/api-reference"),
    ("Play.ht", "AI voice generator", "https://docs.play.ht/"),
    ("Resemble AI", "Voice cloning API", "https://www.resemble.ai/docs/"),
    ("Murf AI", "AI voice over", "https://murf.ai/api"),
    ("Speechify", "Text to speech AI", "https://speechify.com/api"),
    ("AssemblyAI", "Speech recognition", "https://www.assemblyai.com/docs/"),
    ("Deepgram", "Speech to text AI", "https://developers.deepgram.com/"),
    ("Rev AI", "Speech recognition", "https://www.rev.ai/docs"),
    ("Whisper API", "OpenAI Whisper", "https://platform.openai.com/docs/guides/speech-to-text"),
    ("Gladia", "Audio transcription", "https://docs.gladia.io/"),
    ("Hugging Face Inference", "ML model inference", "https://huggingface.co/docs/api-inference/"),
    ("Hugging Face Hub", "ML model repository", "https://huggingface.co/docs/hub/"),
    ("Replicate", "Run ML models", "https://replicate.com/docs"),
    ("Modal", "Serverless ML compute", "https://modal.com/docs"),
    ("Banana Dev", "ML model hosting", "https://docs.banana.dev/"),
    ("Baseten", "ML infrastructure", "https://docs.baseten.co/"),
    ("Cerebrium", "ML deployment", "https://docs.cerebrium.ai/"),
    ("LangChain", "LLM framework", "https://python.langchain.com/docs/"),
    ("LlamaIndex", "LLM data framework", "https://docs.llamaindex.ai/"),
    ("Pinecone", "Vector database", "https://docs.pinecone.io/"),
    ("Weaviate", "Vector search engine", "https://weaviate.io/developers/weaviate"),
    ("Qdrant", "Vector similarity search", "https://qdrant.tech/documentation/"),
    ("Milvus", "Vector database", "https://milvus.io/docs/"),
    ("Chroma", "Embedding database", "https://docs.trychroma.com/"),
    ("Clarifai", "Visual AI platform", "https://docs.clarifai.com/"),
    ("Roboflow", "Computer vision API", "https://docs.roboflow.com/"),
    ("Scale AI", "Data labeling platform", "https://scale.com/docs"),
    ("Labelbox", "Data labeling", "https://docs.labelbox.com/"),
    ("V7 Labs", "AI data platform", "https://docs.v7labs.com/"),
    ("Weights Biases", "ML experiment tracking", "https://docs.wandb.ai/"),
    ("MLflow", "ML lifecycle platform", "https://mlflow.org/docs/latest/rest-api.html"),
    ("Neptune AI", "ML metadata store", "https://docs.neptune.ai/"),
    ("Comet ML", "ML experiment tracking", "https://www.comet.com/docs/v2/api-and-sdk/rest-api/"),
    ("DVC", "Data version control", "https://dvc.org/doc"),
    ("Gradient", "ML cloud platform", "https://docs.paperspace.com/"),
    ("Lambda Labs", "GPU cloud", "https://lambdalabs.com/api"),
    ("CoreWeave", "GPU cloud platform", "https://docs.coreweave.com/"),
    ("RunPod", "GPU cloud AI", "https://docs.runpod.io/"),
    ("Vast AI", "GPU marketplace", "https://vast.ai/docs"),
    ("Suno AI", "AI music generation", "https://suno.ai/"),
    ("Udio", "AI music creation", "https://udio.com/"),
    ("Mubert", "AI music generation", "https://mubert.com/api"),
    ("AIVA", "AI music composer", "https://www.aiva.ai/api"),
    ("Riffusion", "AI music from text", "https://riffusion.com/"),
    ("Devin AI", "AI software engineer", "https://devin.ai/"),
    ("Cursor AI", "AI code editor", "https://cursor.sh/"),
    ("Tabnine", "AI code completion", "https://www.tabnine.com/"),
    ("Codeium", "AI code assistant", "https://codeium.com/"),
    ("Amazon CodeWhisperer", "AI coding assistant", "https://aws.amazon.com/codewhisperer/"),
    ("Sourcegraph Cody", "AI coding assistant", "https://docs.sourcegraph.com/cody"),
    ("Phind", "AI search for developers", "https://www.phind.com/"),
    ("Perplexity AI", "AI search engine", "https://docs.perplexity.ai/"),
    ("You.com", "AI search platform", "https://you.com/api"),
    ("Brave Search AI", "AI search API", "https://api.search.brave.com/"),
    ("Kagi AI", "AI search engine", "https://help.kagi.com/kagi/api/"),
    ("LLMonitor", "LLM observability", "https://llmonitor.com/docs"),
    ("Helicone", "LLM observability", "https://docs.helicone.ai/"),
    ("Langfuse", "LLM engineering platform", "https://langfuse.com/docs"),
    ("Portkey", "LLM gateway", "https://portkey.ai/docs"),
    ("LiteLLM", "LLM proxy", "https://docs.litellm.ai/"),
    ("OpenRouter", "LLM router", "https://openrouter.ai/docs"),
    ("Together AI", "Open source AI", "https://docs.together.ai/"),
    ("Anyscale", "Ray platform", "https://docs.anyscale.com/"),
    ("Fireworks AI", "Fast inference", "https://readme.fireworks.ai/"),
    ("Groq", "Fast AI inference", "https://console.groq.com/docs"),
    ("Lepton AI", "AI inference", "https://www.lepton.ai/docs"),
    ("SambaNova", "AI platform", "https://www.sambanova.ai/"),
    ("Cerebras", "AI compute", "https://www.cerebras.net/"),
    ("Modular", "AI infrastructure", "https://docs.modular.com/"),
    ("Unstructured", "Document parsing", "https://unstructured-io.github.io/unstructured/"),
    ("LlamaParse", "Document parsing", "https://docs.llamaindex.ai/en/stable/llama_cloud/llama_parse/"),
    ("Docugami", "Document AI", "https://docugami.com/api"),
    ("Nanonets", "Document AI", "https://nanonets.com/documentation/"),
    ("Rossum", "Document processing", "https://rossum.ai/developers/"),
    ("Anthropic Tools", "Claude tools API", "https://docs.anthropic.com/claude/docs/tool-use"),
    ("OpenAI Functions", "GPT function calling", "https://platform.openai.com/docs/guides/function-calling"),
    ("Voyage AI", "Embeddings API", "https://docs.voyageai.com/"),
    ("Jina AI", "AI search embeddings", "https://jina.ai/embeddings/"),
    ("Nomic AI", "Open embeddings", "https://docs.nomic.ai/"),
    ("Mixedbread AI", "Embeddings API", "https://www.mixedbread.ai/docs"),
]

for name, desc, url in ai_apis:
    add_api(name, desc, "AI & ML", url, "apiKey")

# ---------- Automation & Integration (80+) ----------
automation_apis = [
    ("Zapier", "Automation platform", "https://platform.zapier.com/"),
    ("Make", "Visual automation", "https://www.make.com/en/api-documentation"),
    ("n8n", "Workflow automation", "https://docs.n8n.io/api/"),
    ("Pipedream", "Integration platform", "https://pipedream.com/docs"),
    ("Tray.io", "Enterprise automation", "https://tray.io/documentation/"),
    ("Workato", "Enterprise integration", "https://docs.workato.com/"),
    ("Automate.io", "Cloud automation", "https://automate.io/"),
    ("Integromat", "Automation tool", "https://www.integromat.com/en/help/api"),
    ("IFTTT", "Applet automation", "https://platform.ifttt.com/docs"),
    ("Power Automate", "Microsoft automation", "https://docs.microsoft.com/power-automate/"),
    ("Retool", "Internal tools platform", "https://docs.retool.com/"),
    ("Budibase", "Low-code platform", "https://docs.budibase.com/"),
    ("Appsmith", "Low-code platform", "https://docs.appsmith.com/"),
    ("Tooljet", "Low-code platform", "https://docs.tooljet.com/"),
    ("Superblocks", "Internal tools", "https://docs.superblocks.com/"),
    ("Windmill", "Developer platform", "https://www.windmill.dev/docs/"),
    ("Airplane", "Internal tools", "https://docs.airplane.dev/"),
    ("Internal.io", "Internal tools", "https://www.internal.io/docs"),
    ("Appgyver", "No-code platform", "https://docs.appgyver.com/"),
    ("Bubble", "No-code app builder", "https://manual.bubble.io/"),
    ("Webflow", "Visual web builder", "https://developers.webflow.com/"),
    ("Framer", "Design to code", "https://www.framer.com/developers/"),
    ("Plasmic", "Visual builder", "https://docs.plasmic.app/"),
    ("Builder.io", "Visual CMS", "https://www.builder.io/c/docs"),
    ("Contentful", "Headless CMS", "https://www.contentful.com/developers/docs/"),
    ("Sanity", "Headless CMS", "https://www.sanity.io/docs"),
    ("Strapi", "Headless CMS", "https://docs.strapi.io/"),
    ("Directus", "Data platform", "https://docs.directus.io/"),
    ("Ghost", "Publishing platform", "https://ghost.org/docs/content-api/"),
    ("Prismic", "Headless CMS", "https://prismic.io/docs/technologies/rest-api"),
    ("DatoCMS", "Headless CMS", "https://www.datocms.com/docs/content-delivery-api"),
    ("Storyblok", "Headless CMS", "https://www.storyblok.com/docs/api/"),
    ("Hygraph", "GraphQL CMS", "https://hygraph.com/docs"),
    ("Payload CMS", "Headless CMS", "https://payloadcms.com/docs/rest-api"),
    ("KeystoneJS", "CMS framework", "https://keystonejs.com/docs/graphql/overview"),
    ("Forestry", "Git-based CMS", "https://forestry.io/docs/"),
    ("TinaCMS", "Git-backed CMS", "https://tina.io/docs/"),
    ("Netlify CMS", "Open source CMS", "https://www.netlifycms.org/docs/api/"),
    ("Webhook", "Webhook service", "https://webhook.site/"),
    ("RequestBin", "HTTP request inspector", "https://requestbin.com/"),
    ("Hookdeck", "Webhook infrastructure", "https://hookdeck.com/docs"),
    ("Svix", "Webhook service", "https://docs.svix.com/"),
    ("Convoy", "Webhook gateway", "https://convoy.readme.io/"),
    ("Inngest", "Event-driven functions", "https://www.inngest.com/docs"),
    ("Trigger.dev", "Background jobs", "https://trigger.dev/docs"),
    ("Defer", "Background jobs", "https://www.defer.run/docs"),
    ("Quirrel", "Job scheduling", "https://docs.quirrel.dev/"),
    ("BullMQ", "Queue system", "https://docs.bullmq.io/"),
    ("Temporal", "Workflow engine", "https://docs.temporal.io/"),
    ("Prefect", "Data orchestration", "https://docs.prefect.io/"),
    ("Dagster", "Data orchestration", "https://docs.dagster.io/"),
    ("Apache Airflow", "Workflow platform", "https://airflow.apache.org/docs/"),
    ("Conductor", "Workflow orchestration", "https://conductor.netflix.com/"),
    ("Argo Workflows", "Kubernetes workflows", "https://argoproj.github.io/argo-workflows/"),
]

for name, desc, url in automation_apis:
    add_api(name, desc, "Automation", url, "apiKey")

# ---------- Analytics & Data (60+) ----------
analytics_apis = [
    ("Google Analytics 4", "Web analytics", "https://developers.google.com/analytics/devguides/reporting/data/v1"),
    ("Mixpanel", "Product analytics", "https://developer.mixpanel.com/"),
    ("Amplitude", "Product analytics", "https://www.docs.developers.amplitude.com/"),
    ("Segment", "Customer data platform", "https://segment.com/docs/api/"),
    ("PostHog", "Product analytics", "https://posthog.com/docs/api"),
    ("Heap", "Digital analytics", "https://developers.heap.io/"),
    ("Pendo", "Product analytics", "https://engageapi.pendo.io/"),
    ("FullStory", "Digital experience", "https://developer.fullstory.com/"),
    ("Hotjar", "Behavior analytics", "https://help.hotjar.com/hc/en-us/articles/115011639887"),
    ("LogRocket", "Session replay", "https://docs.logrocket.com/"),
    ("Smartlook", "Analytics recording", "https://web.smartlook.com/docs/"),
    ("Mouseflow", "Session replay", "https://help.mouseflow.com/en/articles/4364529"),
    ("Lucky Orange", "Website analytics", "https://www.luckyorange.com/help/"),
    ("Plausible", "Privacy-friendly analytics", "https://plausible.io/docs/"),
    ("Fathom", "Simple analytics", "https://usefathom.com/api"),
    ("Simple Analytics", "Privacy analytics", "https://docs.simpleanalytics.com/api"),
    ("Matomo", "Web analytics", "https://developer.matomo.org/api-reference/"),
    ("Umami", "Open source analytics", "https://umami.is/docs/api"),
    ("Pirsch", "Privacy analytics", "https://pirsch.io/api"),
    ("Splitbee", "Analytics tracking", "https://splitbee.io/docs"),
    ("June", "Product analytics", "https://www.june.so/docs"),
    ("Koala", "Visitor intelligence", "https://getkoala.com/docs/api"),
    ("Clearbit", "B2B data enrichment", "https://clearbit.com/docs"),
    ("ZoomInfo", "B2B intelligence", "https://developers.zoominfo.com/"),
    ("Apollo", "Sales intelligence", "https://www.apollo.io/docs/"),
    ("Lusha", "B2B data", "https://www.lusha.com/api/"),
    ("Hunter", "Email finder", "https://hunter.io/api-documentation"),
    ("Snov.io", "Sales automation", "https://snov.io/api"),
    ("Dropcontact", "Data enrichment", "https://dropcontact.com/api"),
    ("People Data Labs", "People data", "https://docs.peopledatalabs.com/"),
    ("Proxycurl", "LinkedIn data", "https://nubela.co/proxycurl/docs"),
    ("Crunchbase", "Company data", "https://data.crunchbase.com/docs"),
    ("PitchBook", "Financial data", "https://pitchbook.com/data"),
    ("CB Insights", "Market intelligence", "https://www.cbinsights.com/api"),
    ("Owler", "Company insights", "https://corp.owler.com/products/owler-api"),
    ("SimilarWeb", "Web analytics", "https://developers.similarweb.com/"),
    ("SEMrush", "SEO analytics", "https://developer.semrush.com/"),
    ("Ahrefs", "SEO tools", "https://ahrefs.com/api"),
    ("Moz", "SEO software", "https://moz.com/products/api"),
    ("Majestic", "Link intelligence", "https://developer.majestic.com/"),
    ("SpyFu", "SEO PPC research", "https://www.spyfu.com/api"),
    ("Serpstat", "SEO platform", "https://serpstat.com/api/"),
    ("DataForSEO", "SEO data", "https://docs.dataforseo.com/"),
    ("Screaming Frog", "SEO spider", "https://www.screamingfrog.co.uk/"),
    ("BrightLocal", "Local SEO", "https://www.brightlocal.com/api/"),
    ("Yext", "Digital presence", "https://developer.yext.com/"),
    ("Google Search Console", "Search performance", "https://developers.google.com/webmaster-tools/"),
    ("Bing Webmaster", "Search tools", "https://docs.microsoft.com/en-us/bingwebmaster/"),
    ("Google PageSpeed", "Performance insights", "https://developers.google.com/speed/docs/insights/v5/get-started"),
    ("GTmetrix", "Page speed", "https://gtmetrix.com/api/"),
    ("WebPageTest", "Performance testing", "https://docs.webpagetest.org/api/"),
    ("Lighthouse", "Web auditing", "https://developers.google.com/web/tools/lighthouse"),
    ("Calibre", "Core Web Vitals", "https://calibreapp.com/docs/api"),
    ("SpeedCurve", "Performance monitoring", "https://support.speedcurve.com/en/articles/415403"),
    ("DebugBear", "Performance monitoring", "https://www.debugbear.com/docs/api"),
    ("Treo", "Web performance", "https://treo.sh/docs"),
]

for name, desc, url in analytics_apis:
    add_api(name, desc, "Analytics", url, "apiKey")

# ---------- Financial Services (70+) ----------
finance_apis = [
    ("Stripe", "Payment processing", "https://stripe.com/docs/api"),
    ("Stripe Connect", "Marketplace payments", "https://stripe.com/docs/connect"),
    ("Stripe Identity", "Identity verification", "https://stripe.com/docs/identity"),
    ("Stripe Radar", "Fraud prevention", "https://stripe.com/docs/radar"),
    ("PayPal", "Payment platform", "https://developer.paypal.com/docs/api/overview/"),
    ("Braintree", "Payment gateway", "https://developer.paypal.com/braintree/docs/"),
    ("Square", "Payments commerce", "https://developer.squareup.com/reference/square"),
    ("Adyen", "Payment platform", "https://docs.adyen.com/api-explorer/"),
    ("Checkout.com", "Payment processing", "https://www.checkout.com/docs/"),
    ("Mollie", "Payment API", "https://docs.mollie.com/"),
    ("Razorpay", "Payment gateway", "https://razorpay.com/docs/"),
    ("Paddle", "SaaS payments", "https://developer.paddle.com/"),
    ("Chargebee", "Subscription billing", "https://apidocs.chargebee.com/"),
    ("Recurly", "Subscription management", "https://developers.recurly.com/"),
    ("Zuora", "Subscription platform", "https://developer.zuora.com/"),
    ("FastSpring", "E-commerce platform", "https://developer.fastspring.com/"),
    ("Gumroad", "Creator commerce", "https://gumroad.com/api"),
    ("Lemon Squeezy", "Digital payments", "https://docs.lemonsqueezy.com/"),
    ("Wise", "International payments", "https://api-docs.wise.com/"),
    ("Revolut", "Banking API", "https://developer.revolut.com/"),
    ("Mercury", "Banking API", "https://docs.mercury.com/"),
    ("Brex", "Business finance", "https://developer.brex.com/"),
    ("Ramp", "Corporate cards", "https://docs.ramp.com/"),
    ("Plaid", "Financial data", "https://plaid.com/docs/"),
    ("Finicity", "Financial data", "https://developer.finicity.com/"),
    ("Yodlee", "Financial aggregation", "https://developer.yodlee.com/"),
    ("MX", "Financial data", "https://docs.mx.com/"),
    ("Tink", "Open banking", "https://docs.tink.com/"),
    ("TrueLayer", "Open banking", "https://docs.truelayer.com/"),
    ("Salt Edge", "Open banking", "https://docs.saltedge.com/"),
    ("Nordigen", "Open banking", "https://nordigen.com/en/docs/"),
    ("Belvo", "Open finance", "https://developers.belvo.com/"),
    ("Mono", "Open banking Africa", "https://docs.mono.co/"),
    ("Stitch", "Open banking Africa", "https://stitch.money/docs"),
    ("Dapi", "Open banking MENA", "https://docs.dapi.com/"),
    ("Lean", "Open banking MENA", "https://docs.leantech.me/"),
    ("Coinbase", "Crypto platform", "https://docs.cloud.coinbase.com/"),
    ("Binance", "Crypto exchange", "https://binance-docs.github.io/apidocs/"),
    ("Kraken", "Crypto exchange", "https://docs.kraken.com/rest/"),
    ("FTX", "Crypto exchange", "https://docs.ftx.com/"),
    ("Gemini", "Crypto exchange", "https://docs.gemini.com/"),
    ("Bitfinex", "Crypto exchange", "https://docs.bitfinex.com/"),
    ("Kucoin", "Crypto exchange", "https://docs.kucoin.com/"),
    ("Bybit", "Crypto exchange", "https://bybit-exchange.github.io/docs/"),
    ("OKX", "Crypto exchange", "https://www.okx.com/docs-v5/"),
    ("Moralis", "Web3 data", "https://docs.moralis.io/"),
    ("Alchemy", "Web3 development", "https://docs.alchemy.com/"),
    ("Infura", "Web3 infrastructure", "https://docs.infura.io/"),
    ("QuickNode", "Web3 infrastructure", "https://www.quicknode.com/docs"),
    ("Chainstack", "Blockchain platform", "https://docs.chainstack.com/"),
    ("Etherscan", "Ethereum explorer", "https://docs.etherscan.io/"),
    ("Polygonscan", "Polygon explorer", "https://polygonscan.com/apis"),
    ("BscScan", "BSC explorer", "https://docs.bscscan.com/"),
    ("Arbiscan", "Arbitrum explorer", "https://arbiscan.io/apis"),
    ("Snowtrace", "Avalanche explorer", "https://snowtrace.io/apis"),
    ("Solscan", "Solana explorer", "https://docs.solscan.io/"),
    ("The Graph", "Blockchain indexing", "https://thegraph.com/docs/"),
    ("Dune", "Blockchain analytics", "https://dune.com/docs/api/"),
    ("Nansen", "Blockchain analytics", "https://docs.nansen.ai/"),
    ("Flipside", "Blockchain analytics", "https://docs.flipsidecrypto.com/"),
    ("DefiLlama", "DeFi data", "https://defillama.com/docs/api"),
    ("CoinGecko", "Crypto data", "https://www.coingecko.com/api/documentation"),
    ("CoinMarketCap", "Crypto data", "https://coinmarketcap.com/api/documentation/"),
    ("Messari", "Crypto research", "https://messari.io/api"),
    ("Glassnode", "Onchain data", "https://docs.glassnode.com/"),
    ("Santiment", "Crypto analytics", "https://api.santiment.net/"),
]

for name, desc, url in finance_apis:
    add_api(name, desc, "Finance", url, "apiKey")

# ---------- Communication & Messaging (50+) ----------
comm_apis = [
    ("Twilio SMS", "SMS API", "https://www.twilio.com/docs/sms"),
    ("Twilio Voice", "Voice calls", "https://www.twilio.com/docs/voice"),
    ("Twilio Video", "Video calls", "https://www.twilio.com/docs/video"),
    ("Twilio WhatsApp", "WhatsApp Business", "https://www.twilio.com/whatsapp"),
    ("SendGrid", "Email delivery", "https://docs.sendgrid.com/api-reference"),
    ("Mailgun", "Email API", "https://documentation.mailgun.com/"),
    ("Postmark", "Email API", "https://postmarkapp.com/developer"),
    ("Amazon SES", "Email service", "https://docs.aws.amazon.com/ses/"),
    ("Mailchimp Transactional", "Email delivery", "https://mailchimp.com/developer/transactional/"),
    ("SparkPost", "Email delivery", "https://developers.sparkpost.com/"),
    ("Sendwithus", "Email automation", "https://www.dyspatch.io/"),
    ("Customer.io", "Messaging automation", "https://customer.io/docs/api/"),
    ("Braze", "Customer engagement", "https://www.braze.com/docs/api/"),
    ("Iterable", "Growth marketing", "https://api.iterable.com/api/docs"),
    ("Klaviyo", "Marketing automation", "https://developers.klaviyo.com/"),
    ("ActiveCampaign", "Email marketing", "https://developers.activecampaign.com/"),
    ("Drip", "E-commerce CRM", "https://developer.drip.com/"),
    ("ConvertKit", "Creator marketing", "https://developers.convertkit.com/"),
    ("Mailerlite", "Email marketing", "https://developers.mailerlite.com/"),
    ("Sendinblue", "Marketing platform", "https://developers.sendinblue.com/"),
    ("Moosend", "Email marketing", "https://www.moosend.com/api"),
    ("Omnisend", "E-commerce marketing", "https://api-docs.omnisend.com/"),
    ("Pushover", "Push notifications", "https://pushover.net/api"),
    ("OneSignal", "Push notifications", "https://documentation.onesignal.com/"),
    ("Firebase Cloud Messaging", "Push notifications", "https://firebase.google.com/docs/cloud-messaging"),
    ("Pusher", "Realtime messaging", "https://pusher.com/docs/"),
    ("Ably", "Realtime platform", "https://ably.com/docs"),
    ("PubNub", "Realtime messaging", "https://www.pubnub.com/docs/"),
    ("Stream", "Activity feeds chat", "https://getstream.io/docs/"),
    ("SendBird", "Chat messaging", "https://sendbird.com/docs"),
    ("CometChat", "Chat SDK", "https://www.cometchat.com/docs"),
    ("Intercom", "Customer messaging", "https://developers.intercom.com/"),
    ("Crisp", "Customer messaging", "https://docs.crisp.chat/api/"),
    ("Drift", "Conversational marketing", "https://devdocs.drift.com/"),
    ("LiveChat", "Customer service", "https://developers.livechat.com/"),
    ("Zendesk", "Customer service", "https://developer.zendesk.com/"),
    ("Freshdesk", "Customer support", "https://developers.freshdesk.com/"),
    ("Help Scout", "Customer support", "https://developer.helpscout.com/"),
    ("Front", "Customer operations", "https://dev.frontapp.com/"),
    ("Gorgias", "E-commerce support", "https://developers.gorgias.com/"),
    ("Slack", "Team messaging", "https://api.slack.com/"),
    ("Discord", "Community platform", "https://discord.com/developers/docs"),
    ("Microsoft Teams", "Team collaboration", "https://docs.microsoft.com/graph/teams-concept-overview"),
    ("Telegram Bot", "Messaging bot", "https://core.telegram.org/bots/api"),
    ("WhatsApp Business", "WhatsApp API", "https://developers.facebook.com/docs/whatsapp/"),
    ("Facebook Messenger", "Messenger platform", "https://developers.facebook.com/docs/messenger-platform/"),
    ("Viber", "Messaging platform", "https://developers.viber.com/"),
    ("LINE", "Messaging platform", "https://developers.line.biz/en/docs/"),
    ("WeChat", "Super app platform", "https://developers.weixin.qq.com/"),
    ("Zoom", "Video communications", "https://developers.zoom.us/docs/api/"),
]

for name, desc, url in comm_apis:
    add_api(name, desc, "Communication", url, "apiKey")

# ---------- E-commerce & Retail (50+) ----------
ecommerce_apis = [
    ("Shopify Admin", "Store management", "https://shopify.dev/docs/admin-api/"),
    ("Shopify Storefront", "Headless commerce", "https://shopify.dev/docs/storefront-api/"),
    ("WooCommerce", "WordPress commerce", "https://woocommerce.github.io/woocommerce-rest-api-docs/"),
    ("BigCommerce", "E-commerce platform", "https://developer.bigcommerce.com/"),
    ("Magento", "Adobe Commerce", "https://developer.adobe.com/commerce/webapi/"),
    ("Salesforce Commerce", "Commerce cloud", "https://developer.salesforce.com/docs/commerce"),
    ("Commercetools", "Headless commerce", "https://docs.commercetools.com/api/"),
    ("Saleor", "GraphQL commerce", "https://docs.saleor.io/"),
    ("Medusa", "Headless commerce", "https://docs.medusajs.com/"),
    ("Spree", "Open source commerce", "https://developer.spreecommerce.org/"),
    ("PrestaShop", "E-commerce platform", "https://devdocs.prestashop.com/"),
    ("OpenCart", "E-commerce platform", "https://docs.opencart.com/"),
    ("Ecwid", "E-commerce platform", "https://api-docs.ecwid.com/"),
    ("Wix Stores", "E-commerce", "https://dev.wix.com/docs/rest/api-overview/"),
    ("Squarespace", "Commerce platform", "https://developers.squarespace.com/commerce-apis"),
    ("Amazon SP-API", "Selling Partner API", "https://developer-docs.amazon.com/sp-api/"),
    ("eBay", "Marketplace API", "https://developer.ebay.com/"),
    ("Etsy", "Handmade marketplace", "https://developers.etsy.com/"),
    ("Walmart", "Marketplace API", "https://developer.walmart.com/"),
    ("Target", "Retail API", "https://developer.target.com/"),
    ("Best Buy", "Retail API", "https://developer.bestbuy.com/"),
    ("Home Depot", "Retail API", "https://developer.homedepot.com/"),
    ("Kroger", "Grocery API", "https://developer.kroger.com/"),
    ("Instacart", "Grocery delivery", "https://docs.instacart.com/"),
    ("DoorDash", "Delivery platform", "https://developer.doordash.com/"),
    ("Uber Eats", "Food delivery", "https://developer.uber.com/docs/eats/introduction"),
    ("Grubhub", "Food delivery", "https://developers.grubhub.com/"),
    ("Postmates", "Delivery API", "https://postmates.com/developer/"),
    ("Shippo", "Shipping API", "https://goshippo.com/docs/"),
    ("EasyPost", "Shipping API", "https://www.easypost.com/docs/api"),
    ("ShipStation", "Shipping software", "https://www.shipstation.com/docs/"),
    ("ShipEngine", "Shipping API", "https://shipengine.github.io/shipengine-openapi/"),
    ("Shipbob", "Fulfillment API", "https://developer.shipbob.com/"),
    ("Flexport", "Freight API", "https://apidocs.flexport.com/"),
    ("Returnly", "Returns management", "https://returnly.com/developers/"),
    ("Loop Returns", "Returns platform", "https://docs.loopreturns.com/"),
    ("AfterShip", "Tracking API", "https://docs.aftership.com/"),
    ("Parcel Perform", "Delivery tracking", "https://parcelperform.com/docs/"),
    ("Snipcart", "E-commerce cart", "https://docs.snipcart.com/"),
    ("Foxy", "E-commerce cart", "https://api.foxycart.com/docs"),
    ("TaxJar", "Sales tax API", "https://developers.taxjar.com/"),
    ("Avalara", "Tax compliance", "https://developer.avalara.com/"),
    ("Vertex", "Tax technology", "https://developer.vertexcloud.com/"),
    ("Bolt", "Checkout platform", "https://developers.bolt.com/"),
    ("Fast", "Checkout platform", "https://www.fast.co/developers"),
    ("Shop Pay", "Accelerated checkout", "https://shopify.dev/docs/custom-storefronts/building-with-the-customer-account-api/shop-pay"),
    ("Affirm", "Buy now pay later", "https://docs.affirm.com/"),
    ("Afterpay", "Pay in installments", "https://developers.afterpay.com/"),
    ("Klarna", "Shopping services", "https://docs.klarna.com/"),
    ("Sezzle", "Buy now pay later", "https://docs.sezzle.com/"),
]

for name, desc, url in ecommerce_apis:
    add_api(name, desc, "E-commerce", url, "apiKey")

# ---------- Developer Tools (60+) ----------
devtools_apis = [
    ("GitHub", "Code hosting", "https://docs.github.com/rest"),
    ("GitHub GraphQL", "GitHub data", "https://docs.github.com/graphql"),
    ("GitLab", "DevOps platform", "https://docs.gitlab.com/ee/api/"),
    ("Bitbucket", "Code hosting", "https://developer.atlassian.com/cloud/bitbucket/"),
    ("Jira", "Issue tracking", "https://developer.atlassian.com/cloud/jira/platform/rest/"),
    ("Confluence", "Documentation", "https://developer.atlassian.com/cloud/confluence/rest/"),
    ("Linear", "Issue tracking", "https://developers.linear.app/"),
    ("Notion", "Workspace", "https://developers.notion.com/"),
    ("Coda", "Docs platform", "https://coda.io/developers/apis/v1"),
    ("Airtable", "Database", "https://airtable.com/developers/web/api/"),
    ("Baserow", "Database", "https://baserow.io/api-docs"),
    ("NocoDB", "Database", "https://docs.nocodb.com/"),
    ("Supabase", "Backend platform", "https://supabase.com/docs/guides/api"),
    ("Firebase", "App platform", "https://firebase.google.com/docs/reference"),
    ("Appwrite", "Backend server", "https://appwrite.io/docs"),
    ("Parse", "Backend framework", "https://parseplatform.org/"),
    ("Backendless", "Backend platform", "https://backendless.com/docs/"),
    ("Pocketbase", "Backend in file", "https://pocketbase.io/docs/"),
    ("Convex", "Backend platform", "https://docs.convex.dev/"),
    ("Xata", "Serverless database", "https://xata.io/docs"),
    ("Planetscale", "MySQL platform", "https://planetscale.com/docs"),
    ("CockroachDB", "Distributed SQL", "https://www.cockroachlabs.com/docs/"),
    ("Neon", "Serverless Postgres", "https://neon.tech/docs"),
    ("Turso", "Edge database", "https://docs.turso.tech/"),
    ("Railway", "Deployment platform", "https://docs.railway.app/"),
    ("Render", "Cloud platform", "https://render.com/docs"),
    ("Fly.io", "Global apps", "https://fly.io/docs/"),
    ("Vercel", "Frontend cloud", "https://vercel.com/docs"),
    ("Netlify", "Web platform", "https://docs.netlify.com/"),
    ("Cloudflare Workers", "Edge compute", "https://developers.cloudflare.com/workers/"),
    ("Deno Deploy", "Edge runtime", "https://deno.com/deploy/docs"),
    ("Fastly", "Edge cloud", "https://developer.fastly.com/"),
    ("Akamai", "CDN platform", "https://techdocs.akamai.com/"),
    ("AWS Lambda", "Serverless compute", "https://docs.aws.amazon.com/lambda/"),
    ("Google Cloud Functions", "Serverless", "https://cloud.google.com/functions/docs"),
    ("Azure Functions", "Serverless", "https://docs.microsoft.com/azure/azure-functions/"),
    ("Sentry", "Error tracking", "https://docs.sentry.io/api/"),
    ("Bugsnag", "Error monitoring", "https://bugsnagapiv2.docs.apiary.io/"),
    ("Rollbar", "Error tracking", "https://docs.rollbar.com/"),
    ("LogDNA", "Log management", "https://docs.mezmo.com/"),
    ("Papertrail", "Log management", "https://www.papertrail.com/help/json-http-api/"),
    ("Logtail", "Log management", "https://betterstack.com/docs/logs/api/"),
    ("Datadog", "Monitoring", "https://docs.datadoghq.com/api/"),
    ("New Relic", "Observability", "https://docs.newrelic.com/docs/apis/"),
    ("Grafana", "Visualization", "https://grafana.com/docs/grafana/latest/http_api/"),
    ("Prometheus", "Monitoring", "https://prometheus.io/docs/prometheus/latest/querying/api/"),
    ("PagerDuty", "Incident response", "https://developer.pagerduty.com/"),
    ("OpsGenie", "Alerting", "https://docs.opsgenie.com/docs/api-overview"),
    ("VictorOps", "Incident management", "https://portal.victorops.com/public/api-docs.html"),
    ("StatusPage", "Status pages", "https://developer.statuspage.io/"),
    ("Instatus", "Status pages", "https://instatus.com/help/api"),
    ("Checkly", "Monitoring", "https://www.checklyhq.com/docs/api/"),
    ("Uptime Robot", "Monitoring", "https://uptimerobot.com/api/"),
    ("Cronitor", "Cron monitoring", "https://cronitor.io/docs/api"),
    ("Better Uptime", "Monitoring", "https://betterstack.com/docs/uptime/api/"),
    ("LaunchDarkly", "Feature flags", "https://docs.launchdarkly.com/home/connecting/api"),
    ("Split", "Feature flags", "https://docs.split.io/reference"),
    ("Flagsmith", "Feature flags", "https://docs.flagsmith.com/"),
    ("PostHog", "Feature flags", "https://posthog.com/docs/api/feature-flags"),
    ("ConfigCat", "Feature flags", "https://configcat.com/docs/api/reference/"),
]

for name, desc, url in devtools_apis:
    add_api(name, desc, "Development", url, "apiKey")

# ---------- Media & Entertainment (50+) ----------
media_apis = [
    ("Spotify", "Music streaming", "https://developer.spotify.com/documentation/web-api/"),
    ("Apple Music", "Music streaming", "https://developer.apple.com/documentation/applemusicapi"),
    ("YouTube Data", "Video platform", "https://developers.google.com/youtube/v3"),
    ("YouTube Analytics", "Video analytics", "https://developers.google.com/youtube/analytics"),
    ("Vimeo", "Video hosting", "https://developer.vimeo.com/"),
    ("Dailymotion", "Video platform", "https://developer.dailymotion.com/"),
    ("Twitch", "Live streaming", "https://dev.twitch.tv/docs/api/"),
    ("Kick", "Live streaming", "https://kick.com/api"),
    ("SoundCloud", "Audio sharing", "https://developers.soundcloud.com/docs/api/guide"),
    ("Deezer", "Music streaming", "https://developers.deezer.com/api"),
    ("Tidal", "Music streaming", "https://developer.tidal.com/"),
    ("Pandora", "Music streaming", "https://developer.pandora.com/"),
    ("Last.fm", "Music discovery", "https://www.last.fm/api"),
    ("MusicBrainz", "Music database", "https://musicbrainz.org/doc/MusicBrainz_API"),
    ("Discogs", "Music database", "https://www.discogs.com/developers/"),
    ("Genius", "Song lyrics", "https://docs.genius.com/"),
    ("Musixmatch", "Lyrics API", "https://developer.musixmatch.com/"),
    ("Shazam", "Music recognition", "https://www.shazam.com/developer"),
    ("TMDb", "Movie database", "https://developers.themoviedb.org/3"),
    ("IMDb", "Movie database", "https://www.imdb.com/interfaces/"),
    ("OMDb", "Movie data", "https://www.omdbapi.com/"),
    ("TVmaze", "TV show data", "https://www.tvmaze.com/api"),
    ("Trakt", "TV movie tracking", "https://trakt.docs.apiary.io/"),
    ("JustWatch", "Streaming search", "https://www.justwatch.com/"),
    ("Reelgood", "Streaming guide", "https://www.reelgood.com/"),
    ("Podcast Index", "Podcast data", "https://podcastindex.org/developers"),
    ("Listen Notes", "Podcast search", "https://www.listennotes.com/api/"),
    ("Transistor", "Podcast hosting", "https://api.transistor.fm/"),
    ("Anchor", "Podcast platform", "https://anchor.fm/"),
    ("Simplecast", "Podcast hosting", "https://simplecast.com/api/"),
    ("Spreaker", "Podcast platform", "https://developers.spreaker.com/"),
    ("Podbean", "Podcast hosting", "https://developers.podbean.com/"),
    ("RSS.com", "Podcast hosting", "https://rss.com/api/"),
    ("Buzzsprout", "Podcast hosting", "https://github.com/Buzzsprout/buzzsprout-api"),
    ("Pexels", "Stock photos", "https://www.pexels.com/api/documentation/"),
    ("Unsplash", "Stock photos", "https://unsplash.com/documentation"),
    ("Pixabay", "Stock media", "https://pixabay.com/api/docs/"),
    ("Shutterstock", "Stock media", "https://developers.shutterstock.com/"),
    ("Getty Images", "Stock media", "https://developers.gettyimages.com/"),
    ("Adobe Stock", "Stock media", "https://developer.adobe.com/stock/docs/"),
    ("iStock", "Stock media", "https://www.istockphoto.com/developers"),
    ("Storyblocks", "Stock media", "https://www.storyblocks.com/developer"),
    ("Artlist", "Stock music", "https://artlist.io/"),
    ("Epidemic Sound", "Stock music", "https://www.epidemicsound.com/"),
    ("PremiumBeat", "Stock music", "https://www.premiumbeat.com/"),
    ("Pond5", "Stock media", "https://www.pond5.com/"),
    ("Envato", "Creative assets", "https://build.envato.com/"),
    ("Giphy", "GIF platform", "https://developers.giphy.com/docs/api/"),
    ("Tenor", "GIF platform", "https://tenor.com/gifapi/documentation"),
    ("Imgur", "Image hosting", "https://api.imgur.com/"),
]

for name, desc, url in media_apis:
    add_api(name, desc, "Media", url, "apiKey")

# ---------- Social & Marketing (50+) ----------
social_apis = [
    ("Facebook Graph", "Facebook platform", "https://developers.facebook.com/docs/graph-api/"),
    ("Instagram Basic", "Instagram API", "https://developers.facebook.com/docs/instagram-basic-display-api/"),
    ("Instagram Business", "Instagram business", "https://developers.facebook.com/docs/instagram-api/"),
    ("Twitter API v2", "Twitter platform", "https://developer.twitter.com/en/docs/twitter-api"),
    ("LinkedIn", "Professional network", "https://developer.linkedin.com/"),
    ("Pinterest", "Visual discovery", "https://developers.pinterest.com/"),
    ("TikTok", "Short video", "https://developers.tiktok.com/"),
    ("Snapchat", "Social media", "https://kit.snapchat.com/"),
    ("Reddit", "Social news", "https://www.reddit.com/dev/api/"),
    ("Discord", "Community platform", "https://discord.com/developers/docs"),
    ("Slack", "Workplace messaging", "https://api.slack.com/"),
    ("Mastodon", "Decentralized social", "https://docs.joinmastodon.org/api/"),
    ("Bluesky", "Social protocol", "https://atproto.com/"),
    ("Threads", "Meta social", "https://developers.facebook.com/docs/threads/"),
    ("Tumblr", "Microblogging", "https://www.tumblr.com/docs/en/api/v2"),
    ("Medium", "Publishing platform", "https://github.com/Medium/medium-api-docs"),
    ("Substack", "Newsletter platform", "https://substack.com/"),
    ("Ghost", "Publishing platform", "https://ghost.org/docs/admin-api/"),
    ("Dev.to", "Developer community", "https://developers.forem.com/api"),
    ("Hashnode", "Developer blogs", "https://api.hashnode.com/"),
    ("Product Hunt", "Product launches", "https://api.producthunt.com/v2/docs"),
    ("Buffer", "Social scheduling", "https://buffer.com/developers/api"),
    ("Hootsuite", "Social management", "https://developer.hootsuite.com/"),
    ("Sprout Social", "Social management", "https://developer.sproutsocial.com/"),
    ("Later", "Social scheduling", "https://later.com/api-docs/"),
    ("Sprinklr", "Social management", "https://developer.sprinklr.com/"),
    ("Brandwatch", "Social listening", "https://developers.brandwatch.com/"),
    ("Mention", "Media monitoring", "https://mention.com/en/api/"),
    ("Talkwalker", "Social analytics", "https://www.talkwalker.com/api"),
    ("Meltwater", "Media intelligence", "https://developer.meltwater.com/"),
    ("Canva", "Design platform", "https://www.canva.com/developers/"),
    ("Adobe Creative Cloud", "Creative tools", "https://developer.adobe.com/"),
    ("Figma", "Design platform", "https://www.figma.com/developers/api"),
    ("InVision", "Design collaboration", "https://developers.invisionapp.com/"),
    ("Sketch", "Design tool", "https://developer.sketch.com/"),
    ("Loom", "Video messaging", "https://dev.loom.com/docs/api"),
    ("Vidyard", "Video platform", "https://knowledge.vidyard.com/hc/en-us/articles/360009879754"),
    ("Wistia", "Video hosting", "https://wistia.com/support/developers/"),
    ("Veed.io", "Video editing", "https://www.veed.io/api"),
    ("Kapwing", "Content creation", "https://www.kapwing.com/developers"),
    ("Bitly", "Link management", "https://dev.bitly.com/"),
    ("Rebrandly", "Link management", "https://developers.rebrandly.com/"),
    ("TinyURL", "URL shortening", "https://tinyurl.com/api-docs"),
    ("Short.io", "Link management", "https://developers.short.io/"),
    ("Dub", "Link management", "https://dub.sh/docs/api-reference"),
    ("Linktree", "Link in bio", "https://linktree.com/"),
    ("Beacons", "Link in bio", "https://beacons.ai/"),
    ("Koji", "Creator tools", "https://developer.withkoji.com/"),
    ("Gumroad", "Creator commerce", "https://gumroad.com/api"),
    ("Patreon", "Creator membership", "https://www.patreon.com/portal/registration/register-clients"),
]

for name, desc, url in social_apis:
    add_api(name, desc, "Social", url, "apiKey")

# ---------- Healthcare & Life Sciences (40+) ----------
health_apis = [
    ("FHIR", "Healthcare interoperability", "https://www.hl7.org/fhir/"),
    ("OpenFDA", "FDA public data", "https://open.fda.gov/apis/"),
    ("CMS Blue Button", "Medicare data", "https://bluebutton.cms.gov/"),
    ("Healthkit", "Apple health data", "https://developer.apple.com/documentation/healthkit"),
    ("Google Fit", "Fitness data", "https://developers.google.com/fit"),
    ("Fitbit", "Fitness tracking", "https://dev.fitbit.com/"),
    ("Whoop", "Performance monitoring", "https://developer.whoop.com/"),
    ("Oura", "Sleep tracking", "https://cloud.ouraring.com/docs/"),
    ("Garmin", "Sports tracking", "https://developer.garmin.com/"),
    ("Strava", "Activity tracking", "https://developers.strava.com/"),
    ("Withings", "Health devices", "https://developer.withings.com/"),
    ("Dexcom", "Glucose monitoring", "https://developer.dexcom.com/"),
    ("Medtronic", "Medical devices", "https://developer.medtronic.com/"),
    ("Abbott", "Health devices", "https://www.abbott.com/"),
    ("Epic FHIR", "EHR integration", "https://fhir.epic.com/"),
    ("Cerner FHIR", "EHR integration", "https://fhir.cerner.com/"),
    ("Allscripts", "EHR platform", "https://developer.allscripts.com/"),
    ("DrChrono", "EHR platform", "https://www.drchrono.com/api/"),
    ("Athenahealth", "Healthcare platform", "https://developer.athenahealth.com/"),
    ("Kareo", "Medical software", "https://developer.kareo.com/"),
    ("Practice Fusion", "EHR platform", "https://www.practicefusion.com/"),
    ("SimplePractice", "Practice management", "https://developer.simplepractice.com/"),
    ("Healthie", "Practice management", "https://developer.healthie.com/"),
    ("Zocdoc", "Healthcare marketplace", "https://developer.zocdoc.com/"),
    ("Teladoc", "Telehealth platform", "https://www.teladoc.com/"),
    ("Amwell", "Telehealth platform", "https://www.amwell.com/"),
    ("Doxy.me", "Telehealth platform", "https://doxy.me/en/"),
    ("Redox", "Healthcare integration", "https://developer.redoxengine.com/"),
    ("Health Gorilla", "Health data network", "https://www.healthgorilla.com/"),
    ("Particle Health", "Healthcare data", "https://www.particlehealth.com/"),
    ("Human API", "Health data", "https://www.humanapi.co/"),
    ("Validic", "Health data", "https://docs.validic.com/"),
    ("Welltory", "Health analytics", "https://developers.welltory.com/"),
    ("Gyant", "Health AI", "https://gyant.com/"),
    ("Ada Health", "Symptom checker", "https://ada.com/"),
    ("Infermedica", "Medical AI", "https://developer.infermedica.com/"),
    ("Buoy Health", "Health AI", "https://www.buoyhealth.com/"),
    ("K Health", "AI health", "https://khealth.com/"),
    ("Babylon Health", "AI healthcare", "https://www.babylonhealth.com/"),
    ("Forward", "Healthcare AI", "https://goforward.com/"),
]

for name, desc, url in health_apis:
    add_api(name, desc, "Health", url, "apiKey")

# ---------- Education & Learning (30+) ----------
edu_apis = [
    ("Canvas LMS", "Learning management", "https://canvas.instructure.com/doc/api/"),
    ("Moodle", "Learning platform", "https://docs.moodle.org/dev/Web_service_API_functions"),
    ("Blackboard", "Learning management", "https://developer.blackboard.com/"),
    ("Schoology", "Learning management", "https://developers.schoology.com/"),
    ("Google Classroom", "Education platform", "https://developers.google.com/classroom"),
    ("Microsoft Education", "Education platform", "https://docs.microsoft.com/graph/education-concept-overview"),
    ("Edmodo", "Education network", "https://developers.edmodo.com/"),
    ("ClassDojo", "Classroom management", "https://developers.classdojo.com/"),
    ("Clever", "Education data", "https://dev.clever.com/"),
    ("Instructure", "Learning platform", "https://canvas.instructure.com/doc/api/"),
    ("Kahoot", "Learning games", "https://kahoot.com/business/api/"),
    ("Quizlet", "Study tools", "https://quizlet.com/api/"),
    ("Duolingo", "Language learning", "https://www.duolingo.com/"),
    ("Coursera", "Online courses", "https://coursera.org/"),
    ("Udemy", "Online courses", "https://www.udemy.com/developers/"),
    ("edX", "Online education", "https://www.edx.org/"),
    ("Skillshare", "Creative learning", "https://www.skillshare.com/"),
    ("LinkedIn Learning", "Professional learning", "https://docs.microsoft.com/linkedin/learning/"),
    ("Pluralsight", "Tech learning", "https://www.pluralsight.com/product/integrations"),
    ("Codecademy", "Coding education", "https://www.codecademy.com/"),
    ("Khan Academy", "Free education", "https://www.khanacademy.org/"),
    ("Brilliant", "STEM learning", "https://brilliant.org/"),
    ("Masterclass", "Expert classes", "https://www.masterclass.com/"),
    ("O'Reilly", "Tech learning", "https://www.oreilly.com/"),
    ("DataCamp", "Data science", "https://www.datacamp.com/"),
    ("Treehouse", "Tech education", "https://teamtreehouse.com/"),
    ("Egghead", "Web development", "https://egghead.io/"),
    ("Frontend Masters", "Web development", "https://frontendmasters.com/"),
    ("LeetCode", "Coding practice", "https://leetcode.com/"),
    ("HackerRank", "Coding challenges", "https://www.hackerrank.com/"),
]

for name, desc, url in edu_apis:
    add_api(name, desc, "Education", url, "apiKey")

# ---------- Real Estate & Property (25+) ----------
realestate_apis = [
    ("Zillow", "Real estate data", "https://www.zillow.com/howto/api/APIOverview.htm"),
    ("Redfin", "Real estate data", "https://www.redfin.com/"),
    ("Realtor.com", "Property listings", "https://www.realtor.com/api/"),
    ("Trulia", "Real estate", "https://www.trulia.com/"),
    ("Apartments.com", "Rental listings", "https://www.apartments.com/"),
    ("Rentals.com", "Rental listings", "https://www.rentals.com/"),
    ("HotPads", "Rental search", "https://hotpads.com/"),
    ("Zumper", "Rental platform", "https://www.zumper.com/"),
    ("Roofstock", "Investment properties", "https://www.roofstock.com/"),
    ("Fundrise", "Real estate investing", "https://fundrise.com/"),
    ("RealtyMogul", "Real estate crowdfunding", "https://www.realtymogul.com/"),
    ("CrowdStreet", "Real estate investing", "https://www.crowdstreet.com/"),
    ("HomeLight", "Real estate agents", "https://www.homelight.com/"),
    ("Opendoor", "iBuying platform", "https://www.opendoor.com/"),
    ("Offerpad", "Home buying", "https://www.offerpad.com/"),
    ("Knock", "Home trade-in", "https://www.knock.com/"),
    ("Ribbon", "Home buying", "https://www.ribbon.com/"),
    ("Compass", "Real estate platform", "https://www.compass.com/"),
    ("eXp Realty", "Real estate brokerage", "https://exprealty.com/"),
    ("Keller Williams", "Real estate", "https://www.kw.com/"),
    ("RE/MAX", "Real estate", "https://www.remax.com/"),
    ("Coldwell Banker", "Real estate", "https://www.coldwellbanker.com/"),
    ("Century 21", "Real estate", "https://www.century21.com/"),
    ("Sotheby's Realty", "Luxury real estate", "https://www.sothebysrealty.com/"),
    ("CoreLogic", "Property data", "https://www.corelogic.com/"),
]

for name, desc, url in realestate_apis:
    add_api(name, desc, "Real Estate", url, "apiKey")

# ---------- Sports & Fitness (30+) ----------
sports_apis = [
    ("ESPN", "Sports news data", "https://www.espn.com/apis/devcenter/"),
    ("Sports Reference", "Sports statistics", "https://www.sports-reference.com/"),
    ("NFL", "Football data", "https://www.nfl.com/"),
    ("NBA", "Basketball data", "https://www.nba.com/stats/"),
    ("MLB", "Baseball data", "https://statsapi.mlb.com/"),
    ("NHL", "Hockey data", "https://gitlab.com/dword4/nhlapi"),
    ("MLS", "Soccer data", "https://www.mlssoccer.com/"),
    ("PGA", "Golf data", "https://www.pga.com/"),
    ("ATP", "Tennis data", "https://www.atptour.com/"),
    ("WTA", "Tennis data", "https://www.wtatennis.com/"),
    ("UFC", "MMA data", "https://www.ufc.com/"),
    ("F1", "Formula 1 data", "https://ergast.com/mrd/"),
    ("NASCAR", "Racing data", "https://www.nascar.com/"),
    ("Cricket", "Cricket data", "https://cricketapi.com/"),
    ("Football-Data", "Soccer API", "https://www.football-data.org/"),
    ("API-Football", "Football stats", "https://www.api-football.com/"),
    ("TheSportsDB", "Sports database", "https://www.thesportsdb.com/api.php"),
    ("Sportradar", "Sports data", "https://developer.sportradar.com/"),
    ("SportsDataIO", "Sports feeds", "https://sportsdata.io/"),
    ("Odds API", "Betting odds", "https://the-odds-api.com/"),
    ("BetFair", "Betting exchange", "https://developer.betfair.com/"),
    ("DraftKings", "Fantasy sports", "https://www.draftkings.com/"),
    ("FanDuel", "Fantasy sports", "https://www.fanduel.com/"),
    ("Yahoo Fantasy", "Fantasy sports", "https://developer.yahoo.com/fantasysports/"),
    ("Strava", "Activity tracking", "https://developers.strava.com/"),
    ("Peloton", "Fitness platform", "https://www.peloton.com/"),
    ("ClassPass", "Fitness classes", "https://classpass.com/"),
    ("Mindbody", "Wellness software", "https://developers.mindbodyonline.com/"),
    ("TrainingPeaks", "Training platform", "https://www.trainingpeaks.com/"),
    ("Zwift", "Virtual cycling", "https://www.zwift.com/"),
]

for name, desc, url in sports_apis:
    add_api(name, desc, "Sports", url, "apiKey")

# ---------- Travel & Transportation (30+) ----------
travel_apis = [
    ("Google Flights", "Flight search", "https://developers.google.com/travel/flights"),
    ("Skyscanner", "Travel search", "https://partners.skyscanner.net/"),
    ("Kayak", "Travel search", "https://www.kayak.com/"),
    ("Expedia", "Travel booking", "https://developer.expedia.com/"),
    ("Booking.com", "Hotel booking", "https://developers.booking.com/"),
    ("Airbnb", "Vacation rentals", "https://www.airbnb.com/partner/"),
    ("VRBO", "Vacation rentals", "https://www.vrbo.com/"),
    ("Hotels.com", "Hotel booking", "https://www.hotels.com/"),
    ("Tripadvisor", "Travel reviews", "https://developer-tripadvisor.com/"),
    ("Yelp", "Local business", "https://www.yelp.com/developers/"),
    ("Foursquare", "Location data", "https://developer.foursquare.com/"),
    ("Google Places", "Places data", "https://developers.google.com/maps/documentation/places/"),
    ("HERE Places", "Location data", "https://developer.here.com/"),
    ("Mapbox", "Maps platform", "https://docs.mapbox.com/api/"),
    ("OpenStreetMap", "Map data", "https://wiki.openstreetmap.org/wiki/API"),
    ("TomTom", "Maps navigation", "https://developer.tomtom.com/"),
    ("Uber", "Ride-sharing", "https://developer.uber.com/"),
    ("Lyft", "Ride-sharing", "https://www.lyft.com/developers"),
    ("DiDi", "Ride-sharing", "https://www.didiglobal.com/"),
    ("Grab", "Super app", "https://developer.grab.com/"),
    ("Gojek", "Super app", "https://www.gojek.com/"),
    ("Lime", "Micro-mobility", "https://www.li.me/"),
    ("Bird", "Scooter sharing", "https://www.bird.co/"),
    ("Spin", "Micro-mobility", "https://www.spin.app/"),
    ("FlightAware", "Flight tracking", "https://flightaware.com/commercial/flightxml/"),
    ("Flightradar24", "Flight tracking", "https://www.flightradar24.com/"),
    ("ADS-B Exchange", "Aircraft tracking", "https://www.adsbexchange.com/data/"),
    ("OpenSky", "Air traffic", "https://openskynetwork.github.io/opensky-api/"),
    ("Rome2rio", "Travel planning", "https://www.rome2rio.com/"),
    ("Wanderu", "Bus train search", "https://www.wanderu.com/"),
]

for name, desc, url in travel_apis:
    add_api(name, desc, "Travel", url, "apiKey")

# ---------- IoT & Hardware (30+) ----------
iot_apis = [
    ("AWS IoT", "IoT platform", "https://docs.aws.amazon.com/iot/"),
    ("Azure IoT", "IoT platform", "https://docs.microsoft.com/azure/iot-hub/"),
    ("Google Cloud IoT", "IoT platform", "https://cloud.google.com/iot/docs/"),
    ("Particle", "IoT platform", "https://docs.particle.io/reference/cloud-apis/api/"),
    ("Arduino Cloud", "IoT platform", "https://www.arduino.cc/reference/en/iot/api/"),
    ("Adafruit IO", "IoT platform", "https://io.adafruit.com/api/docs/"),
    ("ThingSpeak", "IoT analytics", "https://www.mathworks.com/help/thingspeak/"),
    ("Blynk", "IoT platform", "https://docs.blynk.io/"),
    ("Losant", "IoT platform", "https://docs.losant.com/rest-api/overview/"),
    ("Ubidots", "IoT platform", "https://ubidots.com/docs/api/"),
    ("Cayenne", "IoT platform", "https://developers.mydevices.com/cayenne/"),
    ("Home Assistant", "Home automation", "https://developers.home-assistant.io/docs/api/rest"),
    ("SmartThings", "Smart home", "https://developer.smartthings.com/"),
    ("Apple HomeKit", "Smart home", "https://developer.apple.com/homekit/"),
    ("Google Home", "Smart home", "https://developers.google.com/assistant/smarthome/"),
    ("Amazon Alexa", "Smart home", "https://developer.amazon.com/en-US/alexa"),
    ("Philips Hue", "Smart lighting", "https://developers.meethue.com/"),
    ("LIFX", "Smart lighting", "https://api.developer.lifx.com/"),
    ("Nanoleaf", "Smart lighting", "https://forum.nanoleaf.me/docs"),
    ("Nest", "Smart thermostat", "https://developers.nest.com/"),
    ("Ecobee", "Smart thermostat", "https://www.ecobee.com/developers/"),
    ("Ring", "Smart security", "https://ring.com/"),
    ("Arlo", "Smart security", "https://www.arlo.com/"),
    ("August", "Smart locks", "https://august.com/"),
    ("Yale", "Smart locks", "https://www.yalehome.com/"),
    ("Schlage", "Smart locks", "https://www.schlage.com/"),
    ("Wyze", "Smart home", "https://wyzelabs.zendesk.com/hc/en-us/articles/360030692872"),
    ("Tuya", "IoT platform", "https://developer.tuya.com/"),
    ("Espressif", "IoT chips", "https://docs.espressif.com/"),
    ("Raspberry Pi", "SBC platform", "https://www.raspberrypi.com/"),
]

for name, desc, url in iot_apis:
    add_api(name, desc, "IoT", url, "apiKey")

# Add all new APIs to registry
registry['apis'].extend(new_apis)
registry['count'] = len(registry['apis'])
registry['lastUpdated'] = datetime.utcnow().isoformat()

# Save updated registry
with open('/Users/gustavhemmingsson/Projects/apiclaw/src/registry/apis.json', 'w') as f:
    json.dump(registry, f, indent=2)

added = len(new_apis)
print(f"✅ Added {added} new APIs")
print(f"📊 Total APIs: {registry['count']}")
print(f"📈 Growth: {initial_count} → {registry['count']} (+{registry['count'] - initial_count})")
