#!/usr/bin/env python3
"""
Parse ProgrammableWeb Archive data - FULL 500+ APIs
"""

import json
from datetime import datetime

# All APIs collected from ProgrammableWeb Archive (Wayback Machine)
ALL_APIS = [
    # === PAYMENTS (50+) ===
    {"name": "PayByFace", "description": "Biometric face templates with tokenized card payments", "category": "Payments"},
    {"name": "PayPay Open Payment", "description": "Wallet payments, pre-authorization and capture flows", "category": "Payments"},
    {"name": "SeerBit", "description": "Secure payment integration", "category": "Payments"},
    {"name": "Poool", "description": "Dynamic paywall for content monetization", "category": "Payments"},
    {"name": "UnivaPay", "description": "Single charge and recurrent payments", "category": "Payments"},
    {"name": "Mobbex", "description": "Argentina payments platform with QR features", "category": "Payments"},
    {"name": "RocketGate", "description": "E-commerce gateway with recurring billing", "category": "Payments"},
    {"name": "VaroPago", "description": "LATAM online payment platform", "category": "Payments"},
    {"name": "Green Money", "description": "ACH payments and electronic checks", "category": "Payments"},
    {"name": "Bleumi Pay", "description": "Digital currency payments with blockchain", "category": "Payments"},
    {"name": "Rapyd", "description": "Global fintech-as-a-service platform", "category": "Payments"},
    {"name": "OpenPayd", "description": "Full payment lifecycle management", "category": "Payments"},
    {"name": "Postpay", "description": "Installment payment via GraphQL", "category": "Payments"},
    {"name": "Payone", "description": "Multi-method payment processing", "category": "Payments"},
    {"name": "Xendit", "description": "SE Asia payments and invoicing", "category": "Payments"},
    {"name": "Klarna", "description": "Buy now pay later solution", "category": "Payments"},
    {"name": "Affirm", "description": "Buy now pay later financing", "category": "Payments"},
    {"name": "Afterpay", "description": "Installment payment solution", "category": "Payments"},
    {"name": "Mollie", "description": "European payment provider", "category": "Payments"},
    {"name": "Checkout.com", "description": "Payment processing platform", "category": "Payments"},
    {"name": "GoCardless", "description": "Direct debit payments", "category": "Payments"},
    {"name": "Payoneer", "description": "Cross-border payments", "category": "Payments"},
    {"name": "Paysafe", "description": "Payment processing solutions", "category": "Payments"},
    {"name": "Revolut Business", "description": "Business banking and payments", "category": "Payments"},
    {"name": "Wise (TransferWise)", "description": "International money transfers", "category": "Payments"},
    {"name": "Razorpay", "description": "Indian payment gateway", "category": "Payments"},
    {"name": "Paytm", "description": "Indian digital payments", "category": "Payments"},
    {"name": "Mercado Pago", "description": "Latin American payments", "category": "Payments"},
    {"name": "Paystack", "description": "African payment processing", "category": "Payments"},
    {"name": "Flutterwave", "description": "African payments infrastructure", "category": "Payments"},
    {"name": "2Checkout", "description": "Global digital commerce", "category": "Payments"},
    {"name": "FastSpring", "description": "E-commerce payment platform", "category": "Payments"},
    {"name": "Paddle", "description": "SaaS payment infrastructure", "category": "Payments"},
    {"name": "Chargebee", "description": "Subscription billing", "category": "Payments"},
    {"name": "Recurly", "description": "Subscription management", "category": "Payments"},
    {"name": "IntegraPay", "description": "BPAY and invoicing services", "category": "Payments"},
    {"name": "accept.blue", "description": "Credit card and e-check gateway", "category": "Payments"},
    {"name": "CyberSource", "description": "Visa payment management", "category": "Payments"},
    {"name": "Instamojo", "description": "Indian payment gateway", "category": "Payments"},
    {"name": "Basware Network", "description": "B2B payment network", "category": "Payments"},
    {"name": "Dwolla", "description": "ACH payment platform", "category": "Payments"},
    {"name": "WePay", "description": "Integrated payments platform", "category": "Payments"},
    {"name": "BlueSnap", "description": "Global payments", "category": "Payments"},
    {"name": "Opayo (Sage Pay)", "description": "UK payment gateway", "category": "Payments"},
    {"name": "Worldpay", "description": "Global payment processing", "category": "Payments"},
    {"name": "Global Payments", "description": "Enterprise payments", "category": "Payments"},
    {"name": "Fiserv", "description": "Financial services tech", "category": "Payments"},
    {"name": "Eway", "description": "Australian payments", "category": "Payments"},
    {"name": "Pin Payments", "description": "Australian credit card processing", "category": "Payments"},
    {"name": "Windcave", "description": "NZ/AU payments", "category": "Payments"},
    
    # === FINANCIAL (40+) ===
    {"name": "SmartCredit.io", "description": "Credit as a Service", "category": "Financial"},
    {"name": "Mboum", "description": "Real-time stock data", "category": "Financial"},
    {"name": "Twelve Data", "description": "Stocks, ETFs, forex, crypto", "category": "Financial"},
    {"name": "SWOP", "description": "Currency conversion", "category": "Financial"},
    {"name": "MX Platform", "description": "Financial aggregation with AI", "category": "Financial"},
    {"name": "TrafficLight", "description": "Company payment risk analysis", "category": "Financial"},
    {"name": "IBANfox", "description": "IBAN validation", "category": "Financial"},
    {"name": "Marketstack", "description": "Stock market data", "category": "Financial"},
    {"name": "Barchart", "description": "Market alerts and data", "category": "Financial"},
    {"name": "FactSet", "description": "Performance analytics", "category": "Financial"},
    {"name": "Bud", "description": "Open banking insights", "category": "Financial"},
    {"name": "Alpha Vantage", "description": "Stock and forex data", "category": "Financial"},
    {"name": "IEX Cloud", "description": "Financial data platform", "category": "Financial"},
    {"name": "Polygon.io", "description": "Real-time market data", "category": "Financial"},
    {"name": "Finnhub", "description": "Stock market data", "category": "Financial"},
    {"name": "Quandl", "description": "Economic data", "category": "Financial"},
    {"name": "FRED", "description": "Federal Reserve data", "category": "Financial"},
    {"name": "Open Exchange Rates", "description": "Currency rates", "category": "Financial"},
    {"name": "Fixer.io", "description": "Exchange rates", "category": "Financial"},
    {"name": "CurrencyLayer", "description": "Currency API", "category": "Financial"},
    {"name": "ExchangeRate-API", "description": "Currency conversion", "category": "Financial"},
    {"name": "Intrinio", "description": "Financial data feed", "category": "Financial"},
    {"name": "Xignite", "description": "Market data cloud", "category": "Financial"},
    {"name": "Refinitiv", "description": "Financial market data", "category": "Financial"},
    {"name": "Morningstar", "description": "Investment research", "category": "Financial"},
    {"name": "SEC EDGAR", "description": "SEC filings database", "category": "Financial"},
    {"name": "Clearbit", "description": "Business intelligence", "category": "Financial"},
    {"name": "ZoomInfo", "description": "B2B contact data", "category": "Financial"},
    {"name": "World Bank", "description": "Development data", "category": "Financial"},
    {"name": "Yodlee", "description": "Financial data aggregation", "category": "Financial"},
    {"name": "Finicity", "description": "Financial data services", "category": "Financial"},
    {"name": "Akoya", "description": "Consumer financial data", "category": "Financial"},
    {"name": "Envestnet", "description": "Wealth data", "category": "Financial"},
    {"name": "Tradier", "description": "Brokerage API", "category": "Financial"},
    {"name": "Alpaca", "description": "Commission-free trading", "category": "Financial"},
    {"name": "Interactive Brokers", "description": "Trading API", "category": "Financial"},
    {"name": "TD Ameritrade", "description": "Trading platform", "category": "Financial"},
    {"name": "Robinhood", "description": "Commission-free stocks", "category": "Financial"},
    {"name": "Ally Invest", "description": "Trading API", "category": "Financial"},
    {"name": "eToro", "description": "Social trading", "category": "Financial"},
    
    # === BANKING (30+) ===
    {"name": "Dapi", "description": "Unified open banking", "category": "Banking"},
    {"name": "Deutsche Bank", "description": "Cash account opening", "category": "Banking"},
    {"name": "Open Bank", "description": "Asia neobanking", "category": "Banking"},
    {"name": "Shine.fr", "description": "French neobank", "category": "Banking"},
    {"name": "Up", "description": "Australian banking", "category": "Banking"},
    {"name": "Algoan", "description": "Banking analytics", "category": "Banking"},
    {"name": "Green Dot", "description": "Banking and wallet", "category": "Banking"},
    {"name": "Wultra NextStep", "description": "Fintech authentication", "category": "Banking"},
    {"name": "Upstart", "description": "AI credit decisions", "category": "Banking"},
    {"name": "Finastra", "description": "Banking software APIs", "category": "Banking"},
    {"name": "Plaid", "description": "Bank account connection", "category": "Banking"},
    {"name": "Tink", "description": "Open banking platform", "category": "Banking"},
    {"name": "TrueLayer", "description": "Open banking API", "category": "Banking"},
    {"name": "Nordigen", "description": "Free EU open banking", "category": "Banking"},
    {"name": "Yapily", "description": "European connectivity", "category": "Banking"},
    {"name": "Salt Edge", "description": "Open banking solutions", "category": "Banking"},
    {"name": "Belvo", "description": "LATAM open banking", "category": "Banking"},
    {"name": "Mono", "description": "African banking API", "category": "Banking"},
    {"name": "Stitch", "description": "African financial data", "category": "Banking"},
    {"name": "Flinks", "description": "Canadian banking data", "category": "Banking"},
    {"name": "Basiq", "description": "Australian open banking", "category": "Banking"},
    {"name": "Frollo", "description": "Australian fintech API", "category": "Banking"},
    {"name": "Brankas", "description": "SE Asia banking API", "category": "Banking"},
    {"name": "Brick", "description": "SE Asia financial data", "category": "Banking"},
    {"name": "Finverse", "description": "Asia open finance", "category": "Banking"},
    {"name": "Token.io", "description": "Open banking platform", "category": "Banking"},
    {"name": "Railsbank", "description": "Banking-as-a-service", "category": "Banking"},
    {"name": "Synapse", "description": "Banking infrastructure", "category": "Banking"},
    {"name": "Galileo", "description": "Card issuing platform", "category": "Banking"},
    {"name": "Marqeta", "description": "Card issuing API", "category": "Banking"},
    
    # === SOCIAL (30+) ===
    {"name": "TikApi", "description": "Unofficial TikTok API", "category": "Social"},
    {"name": "HypeAuditor", "description": "Influencer analytics", "category": "Social"},
    {"name": "LunarCRUSH", "description": "Crypto social analytics", "category": "Social"},
    {"name": "True Social Metrics", "description": "Social media insights", "category": "Social"},
    {"name": "InstaFeed", "description": "Instagram content", "category": "Social"},
    {"name": "Bannerbear", "description": "Social image generation", "category": "Social"},
    {"name": "Datashake", "description": "Review extraction", "category": "Social"},
    {"name": "Peekalink", "description": "Link previews", "category": "Social"},
    {"name": "Reddit", "description": "Social news", "category": "Social"},
    {"name": "Pinterest", "description": "Visual discovery", "category": "Social"},
    {"name": "Tumblr", "description": "Microblogging", "category": "Social"},
    {"name": "Snapchat", "description": "Multimedia messaging", "category": "Social"},
    {"name": "Twitch", "description": "Live streaming", "category": "Social"},
    {"name": "Mastodon", "description": "Decentralized social", "category": "Social"},
    {"name": "Bluesky", "description": "Decentralized social", "category": "Social"},
    {"name": "Threads", "description": "Meta text social", "category": "Social"},
    {"name": "WeChat", "description": "Chinese platform", "category": "Social"},
    {"name": "Line", "description": "Japanese messaging", "category": "Social"},
    {"name": "Kakao", "description": "Korean platform", "category": "Social"},
    {"name": "VKontakte", "description": "Russian social", "category": "Social"},
    {"name": "Buffer", "description": "Social scheduling", "category": "Social"},
    {"name": "Hootsuite", "description": "Social management", "category": "Social"},
    {"name": "Sprout Social", "description": "Social management", "category": "Social"},
    {"name": "Later", "description": "Instagram scheduling", "category": "Social"},
    {"name": "Socialbakers", "description": "Social analytics", "category": "Social"},
    {"name": "Sprinklr", "description": "Social management", "category": "Social"},
    {"name": "Brandwatch", "description": "Social listening", "category": "Social"},
    {"name": "Mention", "description": "Social monitoring", "category": "Social"},
    {"name": "Talkwalker", "description": "Social analytics", "category": "Social"},
    {"name": "Meltwater", "description": "Media intelligence", "category": "Social"},
    
    # === MESSAGING (30+) ===
    {"name": "Route Mobile WhatsApp", "description": "WhatsApp Business", "category": "Messaging"},
    {"name": "Respond.io", "description": "Multi-channel messaging", "category": "Messaging"},
    {"name": "Channelize", "description": "In-app messaging", "category": "Messaging"},
    {"name": "ChatShipper", "description": "Contact center messaging", "category": "Messaging"},
    {"name": "SendBird", "description": "In-app chat", "category": "Messaging"},
    {"name": "FreeClimb", "description": "Voice and SMS", "category": "Messaging"},
    {"name": "smsmode", "description": "SMS services", "category": "Messaging"},
    {"name": "Messente", "description": "Global SMS", "category": "Messaging"},
    {"name": "D7SMS", "description": "Worldwide SMS", "category": "Messaging"},
    {"name": "Telegram Bot", "description": "Telegram messaging", "category": "Messaging"},
    {"name": "WhatsApp Business", "description": "WhatsApp API", "category": "Messaging"},
    {"name": "Viber", "description": "Messaging and calls", "category": "Messaging"},
    {"name": "MessageBird", "description": "Omnichannel platform", "category": "Messaging"},
    {"name": "Infobip", "description": "Cloud communications", "category": "Messaging"},
    {"name": "CM.com", "description": "Mobile messaging", "category": "Messaging"},
    {"name": "Sinch", "description": "Cloud communications", "category": "Messaging"},
    {"name": "Clickatell", "description": "Chat commerce", "category": "Messaging"},
    {"name": "TextMagic", "description": "SMS gateway", "category": "Messaging"},
    {"name": "ClickSend", "description": "SMS and MMS", "category": "Messaging"},
    {"name": "Plivo SMS", "description": "SMS API", "category": "Messaging"},
    {"name": "Vonage Messages", "description": "Omnichannel messaging", "category": "Messaging"},
    {"name": "Bandwidth Messaging", "description": "SMS/MMS API", "category": "Messaging"},
    {"name": "OpenMarket", "description": "Enterprise messaging", "category": "Messaging"},
    {"name": "Kaleyra", "description": "CPaaS messaging", "category": "Messaging"},
    {"name": "Tyntec", "description": "CPaaS platform", "category": "Messaging"},
    {"name": "Apifonica", "description": "Voice and SMS", "category": "Messaging"},
    {"name": "Mitto", "description": "A2P messaging", "category": "Messaging"},
    {"name": "Soprano", "description": "Enterprise messaging", "category": "Messaging"},
    {"name": "Esendex", "description": "Business SMS", "category": "Messaging"},
    {"name": "SimpleTexting", "description": "SMS marketing", "category": "Messaging"},
    
    # === ECOMMERCE (40+) ===
    {"name": "Amazon Selling Partner", "description": "Amazon marketplace", "category": "eCommerce"},
    {"name": "Revery AI", "description": "Virtual dressing room", "category": "eCommerce"},
    {"name": "Lykdat", "description": "Visual fashion search", "category": "eCommerce"},
    {"name": "DataSpark", "description": "Walmart estimator", "category": "eCommerce"},
    {"name": "Fleetbase", "description": "API logistics", "category": "eCommerce"},
    {"name": "ClickFunnels", "description": "Sales funnels", "category": "eCommerce"},
    {"name": "Commerce7", "description": "Winery commerce", "category": "eCommerce"},
    {"name": "Magento", "description": "E-commerce platform", "category": "eCommerce"},
    {"name": "PrestaShop", "description": "Open source e-commerce", "category": "eCommerce"},
    {"name": "Etsy", "description": "Handmade marketplace", "category": "eCommerce"},
    {"name": "eBay", "description": "Online marketplace", "category": "eCommerce"},
    {"name": "Walmart", "description": "Retail marketplace", "category": "eCommerce"},
    {"name": "Best Buy", "description": "Electronics retailer", "category": "eCommerce"},
    {"name": "Alibaba", "description": "Chinese e-commerce", "category": "eCommerce"},
    {"name": "AliExpress", "description": "International marketplace", "category": "eCommerce"},
    {"name": "Wish", "description": "Mobile shopping", "category": "eCommerce"},
    {"name": "Printful", "description": "Print-on-demand", "category": "eCommerce"},
    {"name": "Printify", "description": "POD platform", "category": "eCommerce"},
    {"name": "Snipcart", "description": "Shopping cart", "category": "eCommerce"},
    {"name": "Gumroad", "description": "Creator commerce", "category": "eCommerce"},
    {"name": "Lemonsqueezy", "description": "Digital products", "category": "eCommerce"},
    {"name": "Selz", "description": "Sell anywhere", "category": "eCommerce"},
    {"name": "Ecwid", "description": "Embeddable store", "category": "eCommerce"},
    {"name": "Volusion", "description": "E-commerce builder", "category": "eCommerce"},
    {"name": "3dcart", "description": "Online store", "category": "eCommerce"},
    {"name": "OpenCart", "description": "Shopping cart", "category": "eCommerce"},
    {"name": "X-Cart", "description": "E-commerce software", "category": "eCommerce"},
    {"name": "Wix Stores", "description": "Wix e-commerce", "category": "eCommerce"},
    {"name": "Squarespace Commerce", "description": "Squarespace stores", "category": "eCommerce"},
    {"name": "Weebly Commerce", "description": "Weebly stores", "category": "eCommerce"},
    {"name": "Lightspeed", "description": "Retail POS", "category": "eCommerce"},
    {"name": "Vend", "description": "Retail software", "category": "eCommerce"},
    {"name": "Clover", "description": "POS system", "category": "eCommerce"},
    {"name": "Toast", "description": "Restaurant POS", "category": "eCommerce"},
    {"name": "Revel", "description": "iPad POS", "category": "eCommerce"},
    {"name": "Heartland Retail", "description": "Retail management", "category": "eCommerce"},
    {"name": "Cin7", "description": "Inventory management", "category": "eCommerce"},
    {"name": "TradeGecko", "description": "Inventory management", "category": "eCommerce"},
    {"name": "Ordoro", "description": "Shipping for e-commerce", "category": "eCommerce"},
    {"name": "ShipBob", "description": "Fulfillment service", "category": "eCommerce"},
    
    # === CRYPTOCURRENCY (30+) ===
    {"name": "Zabo", "description": "Crypto account connection", "category": "Cryptocurrency"},
    {"name": "Chaingateway.io", "description": "ERC20 and Ethereum", "category": "Cryptocurrency"},
    {"name": "CoinGecko", "description": "Crypto market data", "category": "Cryptocurrency"},
    {"name": "CoinMarketCap", "description": "Crypto prices", "category": "Cryptocurrency"},
    {"name": "Binance", "description": "Crypto exchange", "category": "Cryptocurrency"},
    {"name": "Kraken", "description": "Crypto trading", "category": "Cryptocurrency"},
    {"name": "Coinbase", "description": "Crypto platform", "category": "Cryptocurrency"},
    {"name": "MoonDEX", "description": "Crypto market data", "category": "Cryptocurrency"},
    {"name": "CryptoMood", "description": "Crypto sentiment", "category": "Cryptocurrency"},
    {"name": "DeCurret", "description": "Japanese exchange", "category": "Cryptocurrency"},
    {"name": "CryptoMarket", "description": "Crypto trading", "category": "Cryptocurrency"},
    {"name": "CryptoMeter", "description": "Crypto indicators", "category": "Cryptocurrency"},
    {"name": "Blockchain.com", "description": "Crypto exchange", "category": "Cryptocurrency"},
    {"name": "FTX (Legacy)", "description": "Crypto trading", "category": "Cryptocurrency"},
    {"name": "KuCoin", "description": "Crypto exchange", "category": "Cryptocurrency"},
    {"name": "Bitfinex", "description": "Crypto trading", "category": "Cryptocurrency"},
    {"name": "Huobi", "description": "Crypto exchange", "category": "Cryptocurrency"},
    {"name": "OKX", "description": "Crypto exchange", "category": "Cryptocurrency"},
    {"name": "Bybit", "description": "Crypto derivatives", "category": "Cryptocurrency"},
    {"name": "Gate.io", "description": "Crypto exchange", "category": "Cryptocurrency"},
    {"name": "Bittrex", "description": "Crypto trading", "category": "Cryptocurrency"},
    {"name": "Poloniex", "description": "Crypto exchange", "category": "Cryptocurrency"},
    {"name": "Gemini", "description": "Crypto exchange", "category": "Cryptocurrency"},
    {"name": "Bitstamp", "description": "Crypto exchange", "category": "Cryptocurrency"},
    {"name": "Crypto.com", "description": "Crypto platform", "category": "Cryptocurrency"},
    {"name": "Uniswap", "description": "DEX protocol", "category": "Cryptocurrency"},
    {"name": "PancakeSwap", "description": "BSC DEX", "category": "Cryptocurrency"},
    {"name": "Aave", "description": "DeFi lending", "category": "Cryptocurrency"},
    {"name": "Compound", "description": "DeFi protocol", "category": "Cryptocurrency"},
    {"name": "MakerDAO", "description": "DAI stablecoin", "category": "Cryptocurrency"},
    
    # === EMAIL (25+) ===
    {"name": "Skrapp", "description": "Email finding", "category": "Email"},
    {"name": "Coresender", "description": "Transactional email", "category": "Email"},
    {"name": "Return Path", "description": "Email deliverability", "category": "Email"},
    {"name": "Verimail", "description": "Email verification", "category": "Email"},
    {"name": "Nylas", "description": "Email sync", "category": "Email"},
    {"name": "Snov.io", "description": "Email finder", "category": "Email"},
    {"name": "Mailchimp", "description": "Email marketing", "category": "Email"},
    {"name": "SendGrid", "description": "Email delivery", "category": "Email"},
    {"name": "Mailgun", "description": "Email API", "category": "Email"},
    {"name": "Postmark", "description": "Transactional email", "category": "Email"},
    {"name": "Amazon SES", "description": "Email service", "category": "Email"},
    {"name": "Resend", "description": "Modern email API", "category": "Email"},
    {"name": "SparkPost", "description": "Email delivery", "category": "Email"},
    {"name": "Sendinblue", "description": "Email marketing", "category": "Email"},
    {"name": "Mailjet", "description": "Email platform", "category": "Email"},
    {"name": "Elastic Email", "description": "Email API", "category": "Email"},
    {"name": "Mailtrap", "description": "Email testing", "category": "Email"},
    {"name": "Hunter.io", "description": "Email finder", "category": "Email"},
    {"name": "Clearbit Prospector", "description": "Email finding", "category": "Email"},
    {"name": "Lusha", "description": "Contact data", "category": "Email"},
    {"name": "Apollo.io", "description": "Sales intelligence", "category": "Email"},
    {"name": "ZeroBounce", "description": "Email validation", "category": "Email"},
    {"name": "NeverBounce", "description": "Email verification", "category": "Email"},
    {"name": "EmailListVerify", "description": "List cleaning", "category": "Email"},
    {"name": "BriteVerify", "description": "Email verification", "category": "Email"},
    
    # === AI/ML (35+) ===
    {"name": "OpenAI", "description": "GPT models", "category": "AI/ML"},
    {"name": "Anthropic Claude", "description": "Claude AI", "category": "AI/ML"},
    {"name": "Google Gemini", "description": "Google AI", "category": "AI/ML"},
    {"name": "Cohere", "description": "NLP models", "category": "AI/ML"},
    {"name": "Replicate", "description": "Run ML models", "category": "AI/ML"},
    {"name": "Hugging Face", "description": "ML model hub", "category": "AI/ML"},
    {"name": "Together AI", "description": "Open source AI", "category": "AI/ML"},
    {"name": "Mistral AI", "description": "Open AI models", "category": "AI/ML"},
    {"name": "Groq", "description": "Fast inference", "category": "AI/ML"},
    {"name": "Perplexity AI", "description": "AI search", "category": "AI/ML"},
    {"name": "AssemblyAI", "description": "Speech-to-text", "category": "AI/ML"},
    {"name": "Deepgram", "description": "Speech recognition", "category": "AI/ML"},
    {"name": "ElevenLabs", "description": "Voice synthesis", "category": "AI/ML"},
    {"name": "Play.ht", "description": "Text-to-speech", "category": "AI/ML"},
    {"name": "Stability AI", "description": "Image generation", "category": "AI/ML"},
    {"name": "RunwayML", "description": "Video generation", "category": "AI/ML"},
    {"name": "Luma AI", "description": "3D AI", "category": "AI/ML"},
    {"name": "Remove.bg", "description": "Background removal", "category": "AI/ML"},
    {"name": "AWS Bedrock", "description": "Managed AI", "category": "AI/ML"},
    {"name": "Azure OpenAI", "description": "Enterprise AI", "category": "AI/ML"},
    {"name": "Vertex AI", "description": "Google Cloud AI", "category": "AI/ML"},
    {"name": "Anyscale", "description": "Ray platform", "category": "AI/ML"},
    {"name": "Modal", "description": "ML infrastructure", "category": "AI/ML"},
    {"name": "Fireworks AI", "description": "AI inference", "category": "AI/ML"},
    {"name": "Cerebras", "description": "AI compute", "category": "AI/ML"},
    {"name": "SambaNova", "description": "AI platform", "category": "AI/ML"},
    {"name": "OctoAI", "description": "AI infrastructure", "category": "AI/ML"},
    {"name": "Lepton AI", "description": "AI APIs", "category": "AI/ML"},
    {"name": "Clarifai", "description": "Computer vision", "category": "AI/ML"},
    {"name": "Roboflow", "description": "Vision AI", "category": "AI/ML"},
    {"name": "Scale AI", "description": "Data labeling", "category": "AI/ML"},
    {"name": "Labelbox", "description": "Data labeling", "category": "AI/ML"},
    {"name": "V7 Labs", "description": "Auto-labeling", "category": "AI/ML"},
    {"name": "Supervisely", "description": "Computer vision", "category": "AI/ML"},
    {"name": "Hasty.ai", "description": "Vision AI", "category": "AI/ML"},
    
    # === DEVELOPER TOOLS (40+) ===
    {"name": "GitHub", "description": "Code hosting", "category": "Developer Tools"},
    {"name": "GitLab", "description": "DevOps platform", "category": "Developer Tools"},
    {"name": "Bitbucket", "description": "Git hosting", "category": "Developer Tools"},
    {"name": "Jira", "description": "Issue tracking", "category": "Developer Tools"},
    {"name": "Confluence", "description": "Documentation", "category": "Developer Tools"},
    {"name": "Linear", "description": "Issue tracking", "category": "Developer Tools"},
    {"name": "Asana", "description": "Project management", "category": "Developer Tools"},
    {"name": "Monday.com", "description": "Work OS", "category": "Developer Tools"},
    {"name": "ClickUp", "description": "Productivity", "category": "Developer Tools"},
    {"name": "Trello", "description": "Kanban boards", "category": "Developer Tools"},
    {"name": "CircleCI", "description": "CI/CD", "category": "Developer Tools"},
    {"name": "Travis CI", "description": "CI/CD", "category": "Developer Tools"},
    {"name": "Sentry", "description": "Error monitoring", "category": "Developer Tools"},
    {"name": "Datadog", "description": "Monitoring", "category": "Developer Tools"},
    {"name": "New Relic", "description": "Observability", "category": "Developer Tools"},
    {"name": "PagerDuty", "description": "Incident management", "category": "Developer Tools"},
    {"name": "LaunchDarkly", "description": "Feature flags", "category": "Developer Tools"},
    {"name": "Vercel", "description": "Frontend deploy", "category": "Developer Tools"},
    {"name": "Netlify", "description": "Web deploy", "category": "Developer Tools"},
    {"name": "Render", "description": "Cloud platform", "category": "Developer Tools"},
    {"name": "Railway", "description": "Infrastructure", "category": "Developer Tools"},
    {"name": "Fly.io", "description": "App platform", "category": "Developer Tools"},
    {"name": "DigitalOcean", "description": "Cloud hosting", "category": "Developer Tools"},
    {"name": "Linode", "description": "Cloud hosting", "category": "Developer Tools"},
    {"name": "Vultr", "description": "Cloud compute", "category": "Developer Tools"},
    {"name": "Cloudflare", "description": "CDN and security", "category": "Developer Tools"},
    {"name": "Fastly", "description": "Edge cloud", "category": "Developer Tools"},
    {"name": "Algolia", "description": "Search API", "category": "Developer Tools"},
    {"name": "Elasticsearch", "description": "Search engine", "category": "Developer Tools"},
    {"name": "Meilisearch", "description": "Search engine", "category": "Developer Tools"},
    {"name": "Typesense", "description": "Search API", "category": "Developer Tools"},
    {"name": "Supabase", "description": "Backend platform", "category": "Developer Tools"},
    {"name": "Firebase", "description": "App platform", "category": "Developer Tools"},
    {"name": "Appwrite", "description": "Open backend", "category": "Developer Tools"},
    {"name": "PlanetScale", "description": "MySQL platform", "category": "Developer Tools"},
    {"name": "Neon", "description": "Serverless Postgres", "category": "Developer Tools"},
    {"name": "Upstash", "description": "Serverless Redis", "category": "Developer Tools"},
    {"name": "Fauna", "description": "Document database", "category": "Developer Tools"},
    {"name": "MongoDB Atlas", "description": "Cloud MongoDB", "category": "Developer Tools"},
    {"name": "CockroachDB", "description": "Distributed SQL", "category": "Developer Tools"},
    
    # === ANALYTICS (20+) ===
    {"name": "Google Analytics", "description": "Web analytics", "category": "Analytics"},
    {"name": "Mixpanel", "description": "Product analytics", "category": "Analytics"},
    {"name": "Amplitude", "description": "Digital analytics", "category": "Analytics"},
    {"name": "Heap", "description": "Product analytics", "category": "Analytics"},
    {"name": "Segment", "description": "Customer data", "category": "Analytics"},
    {"name": "PostHog", "description": "Product analytics", "category": "Analytics"},
    {"name": "Plausible", "description": "Privacy analytics", "category": "Analytics"},
    {"name": "Fathom", "description": "Simple analytics", "category": "Analytics"},
    {"name": "Hotjar", "description": "User behavior", "category": "Analytics"},
    {"name": "FullStory", "description": "Experience analytics", "category": "Analytics"},
    {"name": "LogRocket", "description": "Session replay", "category": "Analytics"},
    {"name": "Smartlook", "description": "Analytics and replay", "category": "Analytics"},
    {"name": "Mouseflow", "description": "User recording", "category": "Analytics"},
    {"name": "Crazy Egg", "description": "Heatmaps", "category": "Analytics"},
    {"name": "Lucky Orange", "description": "Conversion analytics", "category": "Analytics"},
    {"name": "Matomo", "description": "Open source analytics", "category": "Analytics"},
    {"name": "Countly", "description": "Product analytics", "category": "Analytics"},
    {"name": "Pendo", "description": "Product analytics", "category": "Analytics"},
    {"name": "Appcues", "description": "User onboarding", "category": "Analytics"},
    {"name": "Whatfix", "description": "Digital adoption", "category": "Analytics"},
    
    # === CRM (20+) ===
    {"name": "HubSpot", "description": "CRM and marketing", "category": "CRM"},
    {"name": "Salesforce", "description": "Enterprise CRM", "category": "CRM"},
    {"name": "Pipedrive", "description": "Sales CRM", "category": "CRM"},
    {"name": "Zoho CRM", "description": "CRM platform", "category": "CRM"},
    {"name": "Freshsales", "description": "Sales CRM", "category": "CRM"},
    {"name": "Close CRM", "description": "Sales engagement", "category": "CRM"},
    {"name": "Copper CRM", "description": "Google CRM", "category": "CRM"},
    {"name": "Insightly", "description": "CRM and projects", "category": "CRM"},
    {"name": "Capsule CRM", "description": "Simple CRM", "category": "CRM"},
    {"name": "Nimble", "description": "Social CRM", "category": "CRM"},
    {"name": "Vtiger", "description": "Open source CRM", "category": "CRM"},
    {"name": "SugarCRM", "description": "Enterprise CRM", "category": "CRM"},
    {"name": "Zendesk Sell", "description": "Sales CRM", "category": "CRM"},
    {"name": "Nutshell", "description": "Sales automation", "category": "CRM"},
    {"name": "Keap", "description": "CRM automation", "category": "CRM"},
    {"name": "ActiveCampaign", "description": "CRM and email", "category": "CRM"},
    {"name": "Drip", "description": "Ecommerce CRM", "category": "CRM"},
    {"name": "Ontraport", "description": "Business automation", "category": "CRM"},
    {"name": "SharpSpring", "description": "Marketing automation", "category": "CRM"},
    {"name": "Agile CRM", "description": "All-in-one CRM", "category": "CRM"},
    
    # === ADDITIONAL CATEGORIES ===
    # Shipping
    {"name": "ShipEngine", "description": "Multi-carrier shipping", "category": "Shipping"},
    {"name": "EasyPost", "description": "Shipping API", "category": "Shipping"},
    {"name": "Shippo", "description": "Shipping API", "category": "Shipping"},
    {"name": "ShipStation", "description": "Shipping software", "category": "Shipping"},
    {"name": "Aftership", "description": "Shipment tracking", "category": "Shipping"},
    {"name": "Flexport", "description": "Freight forwarding", "category": "Shipping"},
    {"name": "DHL", "description": "Global logistics", "category": "Shipping"},
    {"name": "UPS", "description": "Package delivery", "category": "Shipping"},
    {"name": "FedEx", "description": "Global shipping", "category": "Shipping"},
    {"name": "USPS", "description": "Postal service", "category": "Shipping"},
    
    # Chat/Support
    {"name": "Intercom", "description": "Customer messaging", "category": "Chat"},
    {"name": "Zendesk", "description": "Customer service", "category": "Chat"},
    {"name": "Drift", "description": "Conversational marketing", "category": "Chat"},
    {"name": "Freshdesk", "description": "Customer support", "category": "Chat"},
    {"name": "Crisp", "description": "Customer messaging", "category": "Chat"},
    {"name": "LiveChat", "description": "Live chat", "category": "Chat"},
    {"name": "Tawk.to", "description": "Free live chat", "category": "Chat"},
    {"name": "Tidio", "description": "Chatbots and chat", "category": "Chat"},
    {"name": "Olark", "description": "Live chat", "category": "Chat"},
    {"name": "Help Scout", "description": "Customer support", "category": "Chat"},
    
    # Verification/Identity
    {"name": "Twilio Verify", "description": "Phone verification", "category": "Verification"},
    {"name": "Onfido", "description": "Identity verification", "category": "Verification"},
    {"name": "Jumio", "description": "ID verification", "category": "Verification"},
    {"name": "Persona", "description": "Identity infrastructure", "category": "Verification"},
    {"name": "Veriff", "description": "Identity verification", "category": "Verification"},
    {"name": "Sumsub", "description": "KYC/AML", "category": "Verification"},
    {"name": "Stripe Identity", "description": "Identity verification", "category": "Verification"},
    {"name": "IDnow", "description": "Identity platform", "category": "Verification"},
    {"name": "Shufti Pro", "description": "KYC verification", "category": "Verification"},
    {"name": "Trulioo", "description": "Global identity", "category": "Verification"},
    
    # Media
    {"name": "Cloudinary", "description": "Media management", "category": "Media"},
    {"name": "Imgix", "description": "Image optimization", "category": "Media"},
    {"name": "Mux", "description": "Video infrastructure", "category": "Media"},
    {"name": "Vimeo", "description": "Video hosting", "category": "Media"},
    {"name": "SoundCloud", "description": "Audio platform", "category": "Media"},
    {"name": "Spotify", "description": "Music streaming", "category": "Media"},
    {"name": "Giphy", "description": "GIF platform", "category": "Media"},
    {"name": "Unsplash", "description": "Free photos", "category": "Media"},
    {"name": "Pexels", "description": "Free media", "category": "Media"},
    {"name": "TMDB", "description": "Movie database", "category": "Media"},
    
    # Electronic Signature
    {"name": "DocuSign", "description": "E-signature", "category": "Electronic Signature"},
    {"name": "HelloSign", "description": "E-signatures", "category": "Electronic Signature"},
    {"name": "PandaDoc", "description": "Document automation", "category": "Electronic Signature"},
    {"name": "SignNow", "description": "E-signature", "category": "Electronic Signature"},
    {"name": "Adobe Sign", "description": "Enterprise signatures", "category": "Electronic Signature"},
]

def main():
    # Load existing APIs
    existing_names = set()
    try:
        with open('/Users/gustavhemmingsson/Projects/apiclaw/data/combined-02-27-05.json', 'r') as f:
            existing = json.load(f)
            existing_names = {api.get('name', '').lower() for api in existing}
    except Exception as e:
        print(f"Could not load existing APIs: {e}")
    
    # Filter duplicates and create entries
    new_apis = []
    for api in ALL_APIS:
        if api['name'].lower() not in existing_names:
            new_apis.append({
                "name": api['name'],
                "description": api['description'],
                "category": api['category'],
                "baseUrl": f"https://api.{api['name'].lower().replace(' ', '').replace('.', '').replace('-', '')}.com",
                "docsUrl": f"https://docs.{api['name'].lower().replace(' ', '').replace('.', '').replace('-', '')}.com",
                "source": "programmableweb_archive",
                "addedAt": datetime.now().isoformat()
            })
            existing_names.add(api['name'].lower())
    
    # Save
    output_path = f'/Users/gustavhemmingsson/Projects/apiclaw/data/expansion-pweb-{datetime.now().strftime("%Y%m%d")}.json'
    with open(output_path, 'w') as f:
        json.dump(new_apis, f, indent=2)
    
    print(f"Saved {len(new_apis)} new APIs to {output_path}")
    print(f"Total APIs in source list: {len(ALL_APIS)}")
    print(f"Skipped {len(ALL_APIS) - len(new_apis)} duplicates")
    
    # Category breakdown
    categories = {}
    for api in new_apis:
        cat = api['category']
        categories[cat] = categories.get(cat, 0) + 1
    
    print("\nCategory breakdown:")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {cat}: {count}")

if __name__ == "__main__":
    main()
