/**
 * Enterprise Script Generator
 * Generates self-contained deployment scripts for bash and PowerShell
 */

import { ApiclawEnvConfig, ENV_VARS, DEFAULT_API_URL } from './env.js';

export interface ScriptOptions {
  workspace?: string;
  apiUrl?: string;
  disableTelemetry?: boolean;
  serverName?: string;
  verbose?: boolean;
}

// Env var names as strings for embedding in scripts
const WORKSPACE_VAR = ENV_VARS.WORKSPACE;
const API_URL_VAR = ENV_VARS.API_URL;
const TELEMETRY_VAR = ENV_VARS.DISABLE_TELEMETRY;

/**
 * Generate self-contained bash deployment script
 */
export function generateBashScript(options: ScriptOptions = {}): string {
  const serverName = options.serverName || 'apiclaw';
  const workspaceVal = options.workspace || '';
  const apiUrlVal = options.apiUrl || DEFAULT_API_URL;
  const disableTelemetry = options.disableTelemetry ? 'true' : '';
  const verbose = options.verbose ? '1' : '';
  
  return `#!/usr/bin/env bash
#
# APIClaw MCP Auto-Setup Script
# Generated by: npx @nordsym/apiclaw setup --enterprise
#
# This script automatically configures APIClaw for all detected MCP clients.
# Supports: Claude Desktop, Cursor, Windsurf, Cline, Continue
#

set -e

# Configuration
SERVER_NAME="${serverName}"
WORKSPACE="${workspaceVal}"
API_URL="${apiUrlVal}"
DEFAULT_API_URL="${DEFAULT_API_URL}"
DISABLE_TELEMETRY="${disableTelemetry}"
VERBOSE="${verbose}"

# Environment variable names
ENV_WORKSPACE="${WORKSPACE_VAR}"
ENV_API_URL="${API_URL_VAR}"
ENV_TELEMETRY="${TELEMETRY_VAR}"

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

log_info() { echo -e "\${BLUE}ℹ\${NC} $1"; }
log_success() { echo -e "\${GREEN}✓\${NC} $1"; }
log_warn() { echo -e "\${YELLOW}⚠\${NC} $1"; }
log_error() { echo -e "\${RED}✗\${NC} $1"; }
log_verbose() { [[ -n "$VERBOSE" ]] && echo -e "  $1"; }

# Detect OS
detect_os() {
  case "$(uname -s)" in
    Darwin*) echo "mac" ;;
    Linux*)  echo "linux" ;;
    MINGW*|MSYS*|CYGWIN*) echo "win" ;;
    *)       echo "linux" ;;
  esac
}

OS=$(detect_os)
HOME_DIR="$HOME"

# Set paths based on OS
case "$OS" in
  mac)
    APP_DATA="$HOME_DIR/Library/Application Support"
    ;;
  linux)
    APP_DATA="\${XDG_CONFIG_HOME:-$HOME_DIR/.config}"
    ;;
  win)
    APP_DATA="\${APPDATA:-$HOME_DIR/AppData/Roaming}"
    ;;
esac

echo ""
echo "🔧 APIClaw MCP Auto-Setup"
echo "========================="
echo ""
log_info "Detected OS: $OS"

# Check for Node.js
if ! command -v node &> /dev/null; then
  log_error "Node.js is required but not installed."
  exit 1
fi
log_success "Node.js $(node --version) found"

# Check for npx
if ! command -v npx &> /dev/null; then
  log_error "npx is required but not installed."
  exit 1
fi
log_success "npx available"

# Generate APIClaw server config JSON
generate_config() {
  local env_block=""
  
  if [[ -n "$WORKSPACE" ]] || [[ -n "$API_URL" && "$API_URL" != "$DEFAULT_API_URL" ]] || [[ -n "$DISABLE_TELEMETRY" ]]; then
    env_block='"env": {'
    local first=true
    
    if [[ -n "$WORKSPACE" ]]; then
      env_block+="\\"$ENV_WORKSPACE\\": \\"$WORKSPACE\\""
      first=false
    fi
    
    if [[ -n "$API_URL" && "$API_URL" != "$DEFAULT_API_URL" ]]; then
      [[ "$first" == "false" ]] && env_block+=','
      env_block+="\\"$ENV_API_URL\\": \\"$API_URL\\""
      first=false
    fi
    
    if [[ -n "$DISABLE_TELEMETRY" ]]; then
      [[ "$first" == "false" ]] && env_block+=','
      env_block+="\\"$ENV_TELEMETRY\\": \\"true\\""
    fi
    
    env_block+='},'
  fi
  
  if [[ -n "$env_block" ]]; then
    echo "{\\"command\\": \\"npx\\", \\"args\\": [\\"-y\\", \\"@nordsym/apiclaw\\"], $env_block}"
  else
    echo "{\\"command\\": \\"npx\\", \\"args\\": [\\"-y\\", \\"@nordsym/apiclaw\\"]}"
  fi
}

# Merge APIClaw into existing config using Node.js
merge_config() {
  local config_path="$1"
  local apiclaw_config
  apiclaw_config=$(generate_config)
  
  if [[ -f "$config_path" ]]; then
    # Backup existing
    cp "$config_path" "$config_path.backup.$(date +%s).json"
    
    # Read existing config
    local existing
    existing=$(cat "$config_path")
    
    # Use node to merge JSON
    node -e "
      const fs = require('fs');
      const existing = JSON.parse(process.argv[1] || '{}');
      const apiclaw = JSON.parse(process.argv[2]);
      
      if (!existing.mcpServers) existing.mcpServers = {};
      existing.mcpServers['$SERVER_NAME'] = apiclaw;
      
      fs.writeFileSync('$config_path', JSON.stringify(existing, null, 2));
    " "$existing" "$apiclaw_config"
  else
    # Create new config
    mkdir -p "$(dirname "$config_path")"
    node -e "
      const fs = require('fs');
      const apiclaw = JSON.parse(process.argv[1]);
      const config = { mcpServers: { '$SERVER_NAME': apiclaw } };
      fs.writeFileSync('$config_path', JSON.stringify(config, null, 2));
    " "$apiclaw_config"
  fi
}

# Client config paths
declare -A CLIENT_PATHS

case "$OS" in
  mac)
    CLIENT_PATHS=(
      ["Claude Desktop"]="$APP_DATA/Claude/claude_desktop_config.json"
      ["Cursor"]="$APP_DATA/Cursor/User/globalStorage/cursor.mcp/config.json"
      ["Windsurf"]="$HOME_DIR/.codeium/windsurf/mcp_config.json"
      ["Cline"]="$APP_DATA/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json"
      ["Continue"]="$HOME_DIR/.continue/config.json"
    )
    ;;
  linux)
    CLIENT_PATHS=(
      ["Claude Desktop"]="$APP_DATA/Claude/claude_desktop_config.json"
      ["Cursor"]="$APP_DATA/Cursor/User/globalStorage/cursor.mcp/config.json"
      ["Windsurf"]="$HOME_DIR/.codeium/windsurf/mcp_config.json"
      ["Cline"]="$APP_DATA/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json"
      ["Continue"]="$HOME_DIR/.continue/config.json"
    )
    ;;
  win)
    CLIENT_PATHS=(
      ["Claude Desktop"]="$APP_DATA/Claude/claude_desktop_config.json"
      ["Cursor"]="$APP_DATA/Cursor/User/globalStorage/cursor.mcp/config.json"
      ["Windsurf"]="$USERPROFILE/.codeium/windsurf/mcp_config.json"
      ["Cline"]="$APP_DATA/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json"
      ["Continue"]="$USERPROFILE/.continue/config.json"
    )
    ;;
esac

# Configure each client
echo ""
log_info "Scanning for MCP clients..."
echo ""

configured=0
skipped=0

for client in "\${!CLIENT_PATHS[@]}"; do
  config_path="\${CLIENT_PATHS[$client]}"
  config_dir=$(dirname "$config_path")
  
  # Check if client is installed (config dir exists or we can create it)
  if [[ -d "$config_dir" ]] || [[ -f "$config_path" ]]; then
    log_info "Configuring $client..."
    
    if merge_config "$config_path"; then
      log_success "$client configured"
      ((configured++))
    else
      log_error "Failed to configure $client"
    fi
  else
    log_verbose "$client not detected (no config directory)"
    ((skipped++))
  fi
done

# Summary
echo ""
echo "========================="
echo ""

if [[ $configured -gt 0 ]]; then
  log_success "Configured $configured client(s)"
  echo ""
  echo "🎉 APIClaw is ready! Restart your MCP clients to activate."
else
  log_warn "No MCP clients were detected."
  echo ""
  echo "Install one of these clients first:"
  echo "  • Claude Desktop: https://claude.ai/download"
  echo "  • Cursor: https://cursor.sh"
  echo "  • Windsurf: https://codeium.com/windsurf"
fi

echo ""
`;
}

/**
 * Generate self-contained PowerShell deployment script
 */
export function generatePowerShellScript(options: ScriptOptions = {}): string {
  const serverName = options.serverName || 'apiclaw';
  const workspaceVal = options.workspace || '';
  const apiUrlVal = options.apiUrl || DEFAULT_API_URL;
  const disableTelemetry = options.disableTelemetry;
  const verbose = options.verbose;
  
  return `#Requires -Version 5.1
<#
.SYNOPSIS
    APIClaw MCP Auto-Setup Script

.DESCRIPTION
    Automatically configures APIClaw for all detected MCP clients.
    Supports: Claude Desktop, Cursor, Windsurf, Cline, Continue

.NOTES
    Generated by: npx @nordsym/apiclaw setup --enterprise
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

# Configuration
$ServerName = "${serverName}"
$Workspace = "${workspaceVal}"
$ApiUrl = "${apiUrlVal}"
$DefaultApiUrl = "${DEFAULT_API_URL}"
$DisableTelemetry = $${disableTelemetry ? 'true' : 'false'}
$VerboseMode = $${verbose ? 'true' : 'false'}

# Env var names
$EnvWorkspace = "${WORKSPACE_VAR}"
$EnvApiUrl = "${API_URL_VAR}"
$EnvTelemetry = "${TELEMETRY_VAR}"

# Helper functions
function Write-Info { param($Message) Write-Host "ℹ $Message" -ForegroundColor Blue }
function Write-Success { param($Message) Write-Host "✓ $Message" -ForegroundColor Green }
function Write-Warn { param($Message) Write-Host "⚠ $Message" -ForegroundColor Yellow }
function Write-Err { param($Message) Write-Host "✗ $Message" -ForegroundColor Red }

Write-Host ""
Write-Host "🔧 APIClaw MCP Auto-Setup" -ForegroundColor Cyan
Write-Host "=========================" -ForegroundColor Cyan
Write-Host ""

# Check for Node.js
try {
    $nodeVersion = & node --version 2>$null
    Write-Success "Node.js $nodeVersion found"
} catch {
    Write-Err "Node.js is required but not installed."
    exit 1
}

# Check for npx
try {
    $null = & npx --version 2>$null
    Write-Success "npx available"
} catch {
    Write-Err "npx is required but not installed."
    exit 1
}

# Generate APIClaw config
function Get-ApiclawConfig {
    $config = @{
        command = "npx"
        args = @("-y", "@nordsym/apiclaw")
    }
    
    $env = @{}
    if ($Workspace) { $env[$EnvWorkspace] = $Workspace }
    if ($ApiUrl -and $ApiUrl -ne $DefaultApiUrl) { $env[$EnvApiUrl] = $ApiUrl }
    if ($DisableTelemetry) { $env[$EnvTelemetry] = "true" }
    
    if ($env.Count -gt 0) {
        $config["env"] = $env
    }
    
    return $config
}

# Merge config into existing file
function Merge-Config {
    param(
        [string]$ConfigPath
    )
    
    $configDir = Split-Path -Parent $ConfigPath
    
    # Ensure directory exists
    if (!(Test-Path $configDir)) {
        New-Item -ItemType Directory -Path $configDir -Force | Out-Null
    }
    
    # Read existing or create new
    if (Test-Path $ConfigPath) {
        # Backup existing
        $backupPath = "$ConfigPath.backup.$([DateTimeOffset]::UtcNow.ToUnixTimeSeconds()).json"
        Copy-Item $ConfigPath $backupPath
        
        $existing = Get-Content $ConfigPath -Raw | ConvertFrom-Json -AsHashtable
    } else {
        $existing = @{}
    }
    
    # Ensure mcpServers exists
    if (!$existing.ContainsKey("mcpServers")) {
        $existing["mcpServers"] = @{}
    }
    
    # Add APIClaw
    $existing["mcpServers"][$ServerName] = Get-ApiclawConfig
    
    # Write back
    $existing | ConvertTo-Json -Depth 10 | Set-Content $ConfigPath -Encoding UTF8
}

# Client paths
$AppData = $env:APPDATA
$UserProfile = $env:USERPROFILE

$ClientPaths = @{
    "Claude Desktop" = "$AppData\\Claude\\claude_desktop_config.json"
    "Cursor" = "$AppData\\Cursor\\User\\globalStorage\\cursor.mcp\\config.json"
    "Windsurf" = "$UserProfile\\.codeium\\windsurf\\mcp_config.json"
    "Cline" = "$AppData\\Code\\User\\globalStorage\\saoudrizwan.claude-dev\\settings\\cline_mcp_settings.json"
    "Continue" = "$UserProfile\\.continue\\config.json"
}

Write-Host ""
Write-Info "Scanning for MCP clients..."
Write-Host ""

$configured = 0

foreach ($client in $ClientPaths.Keys) {
    $configPath = $ClientPaths[$client]
    $configDir = Split-Path -Parent $configPath
    
    if ((Test-Path $configDir) -or (Test-Path $configPath)) {
        Write-Info "Configuring $client..."
        
        try {
            Merge-Config -ConfigPath $configPath
            Write-Success "$client configured"
            $configured++
        } catch {
            Write-Err "Failed to configure $client: $_"
        }
    }
}

Write-Host ""
Write-Host "=========================" -ForegroundColor Cyan
Write-Host ""

if ($configured -gt 0) {
    Write-Success "Configured $configured client(s)"
    Write-Host ""
    Write-Host "🎉 APIClaw is ready! Restart your MCP clients to activate." -ForegroundColor Green
} else {
    Write-Warn "No MCP clients were detected."
    Write-Host ""
    Write-Host "Install one of these clients first:"
    Write-Host "  • Claude Desktop: https://claude.ai/download"
    Write-Host "  • Cursor: https://cursor.sh"
    Write-Host "  • Windsurf: https://codeium.com/windsurf"
}

Write-Host ""
`;
}

/**
 * Generate script based on target platform
 */
export function generateScript(
  platform: 'bash' | 'powershell' | 'auto',
  options: ScriptOptions = {}
): { script: string; filename: string; platform: 'bash' | 'powershell' } {
  // Auto-detect platform
  let targetPlatform: 'bash' | 'powershell' = platform === 'auto'
    ? (process.platform === 'win32' ? 'powershell' : 'bash')
    : platform;
  
  if (targetPlatform === 'powershell') {
    return {
      script: generatePowerShellScript(options),
      filename: 'apiclaw-setup.ps1',
      platform: 'powershell',
    };
  }
  
  return {
    script: generateBashScript(options),
    filename: 'apiclaw-setup.sh',
    platform: 'bash',
  };
}

/**
 * Get file extension for platform
 */
export function getScriptExtension(platform: 'bash' | 'powershell'): string {
  return platform === 'powershell' ? '.ps1' : '.sh';
}
