/**
 * APIClaw Direct Call - Execute API calls through connected providers
 */

import { getCredentials } from './credentials.js';
import { callProxy, PROXY_PROVIDERS } from './proxy.js';
import { executeDynamicAction, hasDynamicConfig, listDynamicActions } from './execute-dynamic.js';

interface ExecuteResult {
  success: boolean;
  provider: string;
  action: string;
  data?: unknown;
  error?: string;
  cost?: number;
  // Normalized top-level fields (extracted from data for convenience)
  url?: string;
  id?: string;
  content?: string;
  status?: string;
}

/**
 * Normalize response by extracting common fields to top-level
 * Makes it easier for agents to access key data without digging into provider-specific structures
 */
function normalizeResponse(result: ExecuteResult): ExecuteResult {
  if (!result.success || !result.data) return result;
  
  const data = result.data as Record<string, unknown>;
  const normalized: ExecuteResult = { ...result };
  
  // Extract URL (various field names across providers)
  const urlFields = ['url', 'audioUrl', 'audio_url', 'output_url', 'image_url', 'video_url', 'file_url', 'download_url'];
  for (const field of urlFields) {
    if (data[field] && typeof data[field] === 'string') {
      normalized.url = data[field] as string;
      break;
    }
  }
  // Handle array outputs (e.g., Replicate returns output: ["url1", "url2"])
  if (!normalized.url && Array.isArray(data.output) && data.output.length > 0 && typeof data.output[0] === 'string') {
    normalized.url = data.output[0];
  }
  
  // Extract ID
  const idFields = ['id', 'sid', 'message_id', 'prediction_id', 'job_id', 'request_id'];
  for (const field of idFields) {
    if (data[field] && (typeof data[field] === 'string' || typeof data[field] === 'number')) {
      normalized.id = String(data[field]);
      break;
    }
  }
  
  // Extract content (for LLM/text responses)
  const contentFields = ['content', 'text', 'message', 'response', 'output'];
  for (const field of contentFields) {
    if (data[field] && typeof data[field] === 'string') {
      normalized.content = data[field] as string;
      break;
    }
  }
  
  // Extract status
  const statusFields = ['status', 'state'];
  for (const field of statusFields) {
    if (data[field] && typeof data[field] === 'string') {
      normalized.status = data[field] as string;
      break;
    }
  }
  
  return normalized;
}

interface DryRunResult {
  dry_run: true;
  provider: string;
  action: string;
  would_send: {
    url: string;
    method: string;
    headers: Record<string, string>;
    body?: unknown;
  };
  mock_response: {
    success: boolean;
    data: unknown;
    estimated_cost?: string;
  };
  notes: string[];
}

// Mock response generators for dry-run mode
const mockResponses: Record<string, Record<string, (params: any) => unknown>> = {
  '46elks': {
    send_sms: (params) => ({
      id: 'mock_sms_' + Date.now(),
      to: params.to,
      from: params.from || 'APIClaw',
      message: params.message,
      status: 'delivered',
      cost: 5200, // ~0.52 SEK in microöre
    }),
  },
  twilio: {
    send_sms: (params) => ({
      sid: 'SMmock' + Date.now(),
      to: params.to,
      from: params.from || '+15017122661',
      body: params.message,
      status: 'queued',
    }),
  },
  brave_search: {
    search: (params) => ({
      query: params.query,
      results: [
        { title: 'Mock Result 1', url: 'https://example.com/1', description: 'This is a mock search result for dry-run testing.' },
        { title: 'Mock Result 2', url: 'https://example.com/2', description: 'Another mock result to simulate search.' },
      ],
      total: 2,
    }),
  },
  resend: {
    send_email: (params) => ({
      id: 'mock_email_' + Date.now(),
      to: params.to,
      from: params.from || 'APIClaw <noreply@apiclaw.nordsym.com>',
      subject: params.subject,
      status: 'sent',
    }),
  },
  openrouter: {
    chat: (params) => ({
      content: '[DRY-RUN] This is a mock response. In production, this would be generated by ' + (params.model || 'anthropic/claude-3-haiku'),
      model: params.model || 'anthropic/claude-3-haiku',
      usage: { prompt_tokens: 10, completion_tokens: 20, total_tokens: 30 },
    }),
  },
  elevenlabs: {
    text_to_speech: (params) => ({
      audio_base64: 'W0RSWV9SVU5fTU9DS19BVURJT10=', // "[DRY_RUN_MOCK_AUDIO]" in base64
      format: 'mp3',
      text_length: params.text?.length || 0,
    }),
  },
  replicate: {
    run: (params) => ({
      status: 'succeeded',
      output: ['https://example.com/mock-image.png'],
      model: params.model,
      metrics: { predict_time: 2.5 },
    }),
    list_models: () => ({
      models: [
        { name: 'stability-ai/sdxl', description: 'Mock model listing' },
      ],
      message: 'DRY-RUN: Would list available models',
    }),
  },
  firecrawl: {
    scrape: (params) => ({
      markdown: `# Mock Scrape of ${params.url}\n\nThis is a dry-run mock of scraped content.`,
      metadata: { title: 'Mock Page', url: params.url },
    }),
    crawl: (params) => ({
      id: 'crawl_mock_' + Date.now(),
      status: 'started',
      message: 'DRY-RUN: Crawl job would be started',
    }),
    map: (params) => ({
      links: ['https://example.com/page1', 'https://example.com/page2'],
    }),
  },
  github: {
    search_repos: (params) => ({
      total: 2,
      repos: [
        { name: 'mock/repo', description: 'Mock repository', stars: 100, url: 'https://github.com/mock/repo', language: 'TypeScript' },
      ],
    }),
    get_repo: (params) => ({
      name: `${params.owner}/${params.repo}`,
      description: 'Mock repository details',
      stars: 100,
      forks: 10,
      language: 'TypeScript',
      url: `https://github.com/${params.owner}/${params.repo}`,
    }),
    list_issues: () => ({
      issues: [{ number: 1, title: 'Mock Issue', state: 'open', user: 'mock-user' }],
    }),
    create_issue: (params) => ({
      number: 1,
      url: `https://github.com/${params.owner}/${params.repo}/issues/1`,
    }),
    get_file: (params) => ({
      name: params.path.split('/').pop(),
      path: params.path,
      size: 100,
      content: '// Mock file content for dry-run',
    }),
  },
  e2b: {
    run_code: (params) => ({
      text: 'DRY-RUN: Code would execute: ' + (params.code?.substring(0, 50) || ''),
      logs: { stdout: [], stderr: [] },
      results: [],
    }),
    run_shell: (params) => ({
      stdout: 'DRY-RUN: Would run: ' + params.command,
      stderr: '',
      exitCode: 0,
    }),
  },
};

// API endpoint info for dry-run
const apiEndpoints: Record<string, Record<string, { url: string; method: string; estimatedCost?: string }>> = {
  '46elks': {
    send_sms: { url: 'https://api.46elks.com/a1/sms', method: 'POST', estimatedCost: '~0.35-0.52 SEK' },
  },
  twilio: {
    send_sms: { url: 'https://api.twilio.com/2010-04-01/Accounts/{accountSid}/Messages.json', method: 'POST', estimatedCost: '~$0.0079/SMS' },
  },
  brave_search: {
    search: { url: 'https://api.search.brave.com/res/v1/web/search', method: 'GET' },
  },
  resend: {
    send_email: { url: 'https://api.resend.com/emails', method: 'POST' },
  },
  openrouter: {
    chat: { url: 'https://openrouter.ai/api/v1/chat/completions', method: 'POST', estimatedCost: 'varies by model' },
  },
  elevenlabs: {
    text_to_speech: { url: 'https://api.elevenlabs.io/v1/text-to-speech/{voice_id}', method: 'POST', estimatedCost: '~$0.30/1000 chars' },
  },
  replicate: {
    run: { url: 'https://api.replicate.com/v1/predictions', method: 'POST', estimatedCost: 'varies by model' },
    list_models: { url: 'https://api.replicate.com/v1/models', method: 'GET' },
  },
  firecrawl: {
    scrape: { url: 'https://api.firecrawl.dev/v1/scrape', method: 'POST' },
    crawl: { url: 'https://api.firecrawl.dev/v1/crawl', method: 'POST' },
    map: { url: 'https://api.firecrawl.dev/v1/map', method: 'POST' },
  },
  github: {
    search_repos: { url: 'https://api.github.com/search/repositories', method: 'GET' },
    get_repo: { url: 'https://api.github.com/repos/{owner}/{repo}', method: 'GET' },
    list_issues: { url: 'https://api.github.com/repos/{owner}/{repo}/issues', method: 'GET' },
    create_issue: { url: 'https://api.github.com/repos/{owner}/{repo}/issues', method: 'POST' },
    get_file: { url: 'https://api.github.com/repos/{owner}/{repo}/contents/{path}', method: 'GET' },
  },
  e2b: {
    run_code: { url: 'https://api.e2b.dev/v1/sandboxes', method: 'POST' },
    run_shell: { url: 'https://api.e2b.dev/v1/sandboxes', method: 'POST' },
  },
};

/**
 * Generate a dry-run result showing what would be sent without making actual API calls
 */
export function generateDryRun(
  providerId: string,
  action: string,
  params: Record<string, any>
): DryRunResult {
  const endpoint = apiEndpoints[providerId]?.[action] || { url: 'unknown', method: 'POST' };
  const mockGen = mockResponses[providerId]?.[action];
  const mockData = mockGen ? mockGen(params) : { message: 'Mock response for ' + action };

  // Build what would be sent
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };

  // Add auth header hints
  if (['46elks', 'twilio'].includes(providerId)) {
    headers['Authorization'] = 'Basic [base64(username:password)]';
  } else if (['brave_search'].includes(providerId)) {
    headers['X-Subscription-Token'] = '[API_KEY]';
  } else if (['resend', 'openrouter', 'replicate', 'firecrawl'].includes(providerId)) {
    headers['Authorization'] = 'Bearer [API_KEY]';
  } else if (providerId === 'elevenlabs') {
    headers['xi-api-key'] = '[API_KEY]';
  } else if (providerId === 'github') {
    headers['Authorization'] = 'Bearer [GITHUB_TOKEN]';
    headers['User-Agent'] = 'APIClaw';
  }

  // Determine body based on method
  let body: unknown = undefined;
  if (endpoint.method === 'POST') {
    if (providerId === '46elks') {
      body = { from: params.from || 'APIClaw', to: params.to, message: params.message };
    } else if (providerId === 'twilio') {
      body = { From: params.from, To: params.to, Body: params.message };
    } else {
      body = params;
    }
  }

  const notes: string[] = [
    '⚠️ DRY-RUN MODE: No actual API call was made',
    'This shows what WOULD be sent if you remove dry_run: true',
  ];

  if (endpoint.estimatedCost) {
    notes.push(`Estimated cost: ${endpoint.estimatedCost}`);
  }

  return {
    dry_run: true,
    provider: providerId,
    action,
    would_send: {
      url: endpoint.url,
      method: endpoint.method,
      headers,
      ...(body ? { body } : {}),
    },
    mock_response: {
      success: true,
      data: mockData,
      ...(endpoint.estimatedCost ? { estimated_cost: endpoint.estimatedCost } : {}),
    },
    notes,
  };
}

// Helper to safely access properties
function safeGet(obj: unknown, ...keys: string[]): unknown {
  let current: unknown = obj;
  for (const key of keys) {
    if (current && typeof current === 'object' && key in current) {
      current = (current as Record<string, unknown>)[key];
    } else {
      return undefined;
    }
  }
  return current;
}

// Provider action handlers
const handlers: Record<string, Record<string, (params: any, creds: any) => Promise<ExecuteResult>>> = {
  
  // 46elks - Swedish SMS/Voice
  '46elks': {
    send_sms: async (params, creds) => {
      const { to, message, from = 'APIClaw' } = params;
      
      if (!to || !message) {
        return { success: false, provider: '46elks', action: 'send_sms', error: 'Missing required params: to, message' };
      }

      const auth = Buffer.from(`${creds.username}:${creds.password}`).toString('base64');
      
      const response = await fetch('https://api.46elks.com/a1/sms', {
        method: 'POST',
        headers: {
          'Authorization': `Basic ${auth}`,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: new URLSearchParams({ from, to, message }),
      });

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok) {
        return { success: false, provider: '46elks', action: 'send_sms', error: (data.message as string) || 'SMS failed' };
      }

      return { 
        success: true, 
        provider: '46elks', 
        action: 'send_sms',
        data: { id: data.id, to: data.to, cost: data.cost },
        cost: parseInt(String(data.cost)) / 10000000 // Convert microöre to SEK
      };
    },
  },

  // Twilio - Global SMS/Voice
  twilio: {
    send_sms: async (params, creds) => {
      const { to, message, from } = params;
      
      if (!to || !message) {
        return { success: false, provider: 'twilio', action: 'send_sms', error: 'Missing required params: to, message' };
      }

      const auth = Buffer.from(`${creds.username}:${creds.password}`).toString('base64');
      const fromNumber = from || creds.from_number || '+15017122661';
      
      const response = await fetch(
        `https://api.twilio.com/2010-04-01/Accounts/${creds.username}/Messages.json`,
        {
          method: 'POST',
          headers: {
            'Authorization': `Basic ${auth}`,
            'Content-Type': 'application/x-www-form-urlencoded',
          },
          body: new URLSearchParams({ From: fromNumber, To: to, Body: message }),
        }
      );

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok) {
        return { success: false, provider: 'twilio', action: 'send_sms', error: (data.message as string) || 'SMS failed' };
      }

      return { 
        success: true, 
        provider: 'twilio', 
        action: 'send_sms',
        data: { sid: data.sid, to: data.to, status: data.status }
      };
    },
  },

  // Brave Search
  brave_search: {
    search: async (params, creds) => {
      const { query, count = 5 } = params;
      
      if (!query) {
        return { success: false, provider: 'brave_search', action: 'search', error: 'Missing required param: query' };
      }

      const url = new URL('https://api.search.brave.com/res/v1/web/search');
      url.searchParams.set('q', query);
      url.searchParams.set('count', count.toString());

      const response = await fetch(url.toString(), {
        headers: { 'X-Subscription-Token': creds.api_key },
      });

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok) {
        return { success: false, provider: 'brave_search', action: 'search', error: (data.message as string) || 'Search failed' };
      }

      const webData = data.web as Record<string, unknown> | undefined;
      const rawResults = (webData?.results as Array<Record<string, unknown>>) || [];
      const results = rawResults.map((r) => ({
        title: r.title,
        url: r.url,
        description: r.description,
      }));

      return { 
        success: true, 
        provider: 'brave_search', 
        action: 'search',
        data: { query, results, total: results.length }
      };
    },
  },

  // Resend - Email
  resend: {
    send_email: async (params, creds) => {
      const { to, subject, html, text, from = 'APIClaw <noreply@apiclaw.nordsym.com>' } = params;
      
      if (!to || !subject || (!html && !text)) {
        return { success: false, provider: 'resend', action: 'send_email', error: 'Missing required params: to, subject, html or text' };
      }

      const response = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${creds.api_key}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ from, to, subject, html, text }),
      });

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok) {
        return { success: false, provider: 'resend', action: 'send_email', error: (data.message as string) || 'Email failed' };
      }

      return { 
        success: true, 
        provider: 'resend', 
        action: 'send_email',
        data: { id: data.id }
      };
    },
  },

  // OpenRouter - AI Models
  openrouter: {
    chat: async (params, creds) => {
      const { messages, model = 'anthropic/claude-3-haiku', max_tokens = 1000 } = params;
      
      if (!messages || !Array.isArray(messages)) {
        return { success: false, provider: 'openrouter', action: 'chat', error: 'Missing required param: messages (array)' };
      }

      const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${creds.api_key}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://apiclaw.nordsym.com',
        },
        body: JSON.stringify({ model, messages, max_tokens }),
      });

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok) {
        const errorData = data.error as Record<string, unknown> | undefined;
        return { success: false, provider: 'openrouter', action: 'chat', error: (errorData?.message as string) || 'Chat failed' };
      }

      const choices = data.choices as Array<Record<string, unknown>> | undefined;
      const firstChoice = choices?.[0];
      const message = firstChoice?.message as Record<string, unknown> | undefined;

      return { 
        success: true, 
        provider: 'openrouter', 
        action: 'chat',
        data: { 
          content: message?.content,
          model: data.model,
          usage: data.usage 
        }
      };
    },
  },

  // ElevenLabs - Text-to-Speech
  elevenlabs: {
    text_to_speech: async (params, creds) => {
      const { text, voice_id = '21m00Tcm4TlvDq8ikWAM', model_id = 'eleven_monolingual_v1' } = params;
      
      if (!text) {
        return { success: false, provider: 'elevenlabs', action: 'text_to_speech', error: 'Missing required param: text' };
      }

      const response = await fetch(
        `https://api.elevenlabs.io/v1/text-to-speech/${voice_id}`,
        {
          method: 'POST',
          headers: {
            'xi-api-key': creds.api_key,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ text, model_id }),
        }
      );

      if (!response.ok) {
        const error = await response.json().catch(() => ({})) as Record<string, unknown>;
        return { success: false, provider: 'elevenlabs', action: 'text_to_speech', error: (error.detail as string) || 'TTS failed' };
      }

      // Return audio as base64
      const buffer = await response.arrayBuffer();
      const base64 = Buffer.from(buffer).toString('base64');

      return { 
        success: true, 
        provider: 'elevenlabs', 
        action: 'text_to_speech',
        data: { 
          audio_base64: base64,
          format: 'mp3',
          text_length: text.length
        }
      };
    },
  },

  // Replicate - Run any AI model (images, audio, video, text)
  replicate: {
    run: async (params, creds) => {
      const { model, input } = params;
      
      if (!model) {
        return { success: false, provider: 'replicate', action: 'run', error: 'Missing required param: model (e.g., "stability-ai/sdxl:...")' };
      }
      if (!input) {
        return { success: false, provider: 'replicate', action: 'run', error: 'Missing required param: input (object with model inputs)' };
      }

      // Parse model into owner/name and version
      const [modelPath, version] = model.split(':');
      
      // Create prediction
      const response = await fetch('https://api.replicate.com/v1/predictions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${creds.api_key}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          version: version || undefined,
          model: version ? undefined : modelPath,
          input,
        }),
      });

      if (!response.ok) {
        const error = await response.json().catch(() => ({})) as Record<string, unknown>;
        return { success: false, provider: 'replicate', action: 'run', error: (error.detail as string) || 'Prediction failed' };
      }

      const prediction = await response.json() as Record<string, unknown>;
      
      // Poll for completion (max 60 seconds)
      let result = prediction;
      const startTime = Date.now();
      while (result.status === 'starting' || result.status === 'processing') {
        if (Date.now() - startTime > 60000) {
          return { 
            success: true, 
            provider: 'replicate', 
            action: 'run',
            data: { 
              status: 'pending',
              prediction_id: result.id,
              message: 'Prediction still running. Use prediction_id to check status.',
              urls: result.urls
            }
          };
        }
        await new Promise(resolve => setTimeout(resolve, 1000));
        const pollResponse = await fetch((result.urls as Record<string, string>)?.get || `https://api.replicate.com/v1/predictions/${result.id}`, {
          headers: { 'Authorization': `Bearer ${creds.api_key}` },
        });
        result = await pollResponse.json() as Record<string, unknown>;
      }

      if (result.status === 'failed') {
        return { success: false, provider: 'replicate', action: 'run', error: (result.error as string) || 'Prediction failed' };
      }

      return { 
        success: true, 
        provider: 'replicate', 
        action: 'run',
        data: { 
          status: result.status,
          output: result.output,
          model: modelPath,
          metrics: result.metrics
        }
      };
    },

    list_models: async (_params, creds) => {
      const response = await fetch('https://api.replicate.com/v1/models', {
        headers: { 'Authorization': `Bearer ${creds.api_key}` },
      });

      if (!response.ok) {
        return { success: false, provider: 'replicate', action: 'list_models', error: 'Failed to list models' };
      }

      const data = await response.json() as Record<string, unknown>;
      
      return { 
        success: true, 
        provider: 'replicate', 
        action: 'list_models',
        data: { 
          models: data.results,
          message: 'Use model owner/name with run action. Popular: stability-ai/sdxl, meta/llama-2-70b-chat, openai/whisper'
        }
      };
    },
  },

  // Firecrawl - Web scraping and crawling
  firecrawl: {
    scrape: async (params, creds) => {
      const { url, formats = ['markdown'] } = params;
      
      if (!url) {
        return { success: false, provider: 'firecrawl', action: 'scrape', error: 'Missing required param: url' };
      }

      const response = await fetch('https://api.firecrawl.dev/v1/scrape', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${creds.api_key}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ url, formats }),
      });

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok || !data.success) {
        return { success: false, provider: 'firecrawl', action: 'scrape', error: (data.error as string) || 'Scrape failed' };
      }

      return { 
        success: true, 
        provider: 'firecrawl', 
        action: 'scrape',
        data: data.data,
      };
    },

    crawl: async (params, creds) => {
      const { url, limit = 10 } = params;
      
      if (!url) {
        return { success: false, provider: 'firecrawl', action: 'crawl', error: 'Missing required param: url' };
      }

      const response = await fetch('https://api.firecrawl.dev/v1/crawl', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${creds.api_key}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ url, limit }),
      });

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok || !data.success) {
        return { success: false, provider: 'firecrawl', action: 'crawl', error: (data.error as string) || 'Crawl failed' };
      }

      return { 
        success: true, 
        provider: 'firecrawl', 
        action: 'crawl',
        data: { id: data.id, status: 'started', message: 'Crawl job started. Poll status with crawl_status action.' },
      };
    },

    map: async (params, creds) => {
      const { url } = params;
      
      if (!url) {
        return { success: false, provider: 'firecrawl', action: 'map', error: 'Missing required param: url' };
      }

      const response = await fetch('https://api.firecrawl.dev/v1/map', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${creds.api_key}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ url }),
      });

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok || !data.success) {
        return { success: false, provider: 'firecrawl', action: 'map', error: (data.error as string) || 'Map failed' };
      }

      return { 
        success: true, 
        provider: 'firecrawl', 
        action: 'map',
        data: { links: data.links },
      };
    },
  },

  // GitHub - Code & Repos
  github: {
    search_repos: async (params, creds) => {
      const { query, sort = 'stars', limit = 10 } = params;
      
      if (!query) {
        return { success: false, provider: 'github', action: 'search_repos', error: 'Missing required param: query' };
      }

      const response = await fetch(`https://api.github.com/search/repositories?q=${encodeURIComponent(query)}&sort=${sort}&per_page=${limit}`, {
        headers: {
          'Authorization': `Bearer ${creds.token}`,
          'Accept': 'application/vnd.github+json',
          'User-Agent': 'APIClaw',
        },
      });

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok) {
        return { success: false, provider: 'github', action: 'search_repos', error: (data.message as string) || 'Search failed' };
      }

      const items = (data.items as any[]) || [];
      return { 
        success: true, 
        provider: 'github', 
        action: 'search_repos',
        data: { 
          total: data.total_count,
          repos: items.slice(0, limit).map(r => ({
            name: r.full_name,
            description: r.description,
            stars: r.stargazers_count,
            url: r.html_url,
            language: r.language,
          }))
        },
      };
    },

    get_repo: async (params, creds) => {
      const { owner, repo } = params;
      
      if (!owner || !repo) {
        return { success: false, provider: 'github', action: 'get_repo', error: 'Missing required params: owner, repo' };
      }

      const response = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
        headers: {
          'Authorization': `Bearer ${creds.token}`,
          'Accept': 'application/vnd.github+json',
          'User-Agent': 'APIClaw',
        },
      });

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok) {
        return { success: false, provider: 'github', action: 'get_repo', error: (data.message as string) || 'Get repo failed' };
      }

      return { 
        success: true, 
        provider: 'github', 
        action: 'get_repo',
        data: {
          name: data.full_name,
          description: data.description,
          stars: data.stargazers_count,
          forks: data.forks_count,
          language: data.language,
          url: data.html_url,
          created: data.created_at,
          updated: data.updated_at,
        },
      };
    },

    list_issues: async (params, creds) => {
      const { owner, repo, state = 'open', limit = 10 } = params;
      
      if (!owner || !repo) {
        return { success: false, provider: 'github', action: 'list_issues', error: 'Missing required params: owner, repo' };
      }

      const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues?state=${state}&per_page=${limit}`, {
        headers: {
          'Authorization': `Bearer ${creds.token}`,
          'Accept': 'application/vnd.github+json',
          'User-Agent': 'APIClaw',
        },
      });

      const data = await response.json() as unknown[];
      
      if (!response.ok) {
        return { success: false, provider: 'github', action: 'list_issues', error: 'List issues failed' };
      }

      return { 
        success: true, 
        provider: 'github', 
        action: 'list_issues',
        data: { 
          issues: (data as any[]).map(i => ({
            number: i.number,
            title: i.title,
            state: i.state,
            user: i.user?.login,
            url: i.html_url,
            created: i.created_at,
          }))
        },
      };
    },

    create_issue: async (params, creds) => {
      const { owner, repo, title, body = '' } = params;
      
      if (!owner || !repo || !title) {
        return { success: false, provider: 'github', action: 'create_issue', error: 'Missing required params: owner, repo, title' };
      }

      const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${creds.token}`,
          'Accept': 'application/vnd.github+json',
          'User-Agent': 'APIClaw',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ title, body }),
      });

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok) {
        return { success: false, provider: 'github', action: 'create_issue', error: (data.message as string) || 'Create issue failed' };
      }

      return { 
        success: true, 
        provider: 'github', 
        action: 'create_issue',
        data: { 
          number: data.number,
          url: data.html_url,
        },
      };
    },

    get_file: async (params, creds) => {
      const { owner, repo, path } = params;
      
      if (!owner || !repo || !path) {
        return { success: false, provider: 'github', action: 'get_file', error: 'Missing required params: owner, repo, path' };
      }

      const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
        headers: {
          'Authorization': `Bearer ${creds.token}`,
          'Accept': 'application/vnd.github+json',
          'User-Agent': 'APIClaw',
        },
      });

      const data = await response.json() as Record<string, unknown>;
      
      if (!response.ok) {
        return { success: false, provider: 'github', action: 'get_file', error: (data.message as string) || 'Get file failed' };
      }

      // Decode base64 content
      const content = data.content ? Buffer.from(data.content as string, 'base64').toString('utf-8') : null;

      return { 
        success: true, 
        provider: 'github', 
        action: 'get_file',
        data: { 
          name: data.name,
          path: data.path,
          size: data.size,
          content,
        },
      };
    },
  },

  // E2B - Code Sandbox for AI Agents
  // Uses @e2b/code-interpreter SDK
  e2b: {
    run_code: async (params, creds) => {
      const { code, language = 'python' } = params;
      
      if (!code) {
        return { success: false, provider: 'e2b', action: 'run_code', error: 'Missing required param: code' };
      }

      try {
        // Dynamic import to avoid issues if SDK not installed
        const { Sandbox } = await import('@e2b/code-interpreter');
        
        // Set API key via env (SDK reads from E2B_API_KEY)
        process.env.E2B_API_KEY = creds.api_key;
        
        const sandbox = await Sandbox.create();
        
        try {
          const execution = await sandbox.runCode(code);
          
          return { 
            success: true, 
            provider: 'e2b', 
            action: 'run_code',
            data: { 
              text: execution.text,
              logs: execution.logs,
              results: execution.results,
            },
          };
        } finally {
          await sandbox.kill().catch(() => {});
        }
      } catch (error: any) {
        return { 
          success: false, 
          provider: 'e2b', 
          action: 'run_code', 
          error: error.message || 'Code execution failed' 
        };
      }
    },

    run_shell: async (params, creds) => {
      const { command } = params;
      
      if (!command) {
        return { success: false, provider: 'e2b', action: 'run_shell', error: 'Missing required param: command' };
      }

      try {
        const { Sandbox } = await import('@e2b/code-interpreter');
        
        process.env.E2B_API_KEY = creds.api_key;
        
        const sandbox = await Sandbox.create();
        
        try {
          const result = await sandbox.commands.run(command);
          
          return { 
            success: true, 
            provider: 'e2b', 
            action: 'run_shell',
            data: { 
              stdout: result.stdout,
              stderr: result.stderr,
              exitCode: result.exitCode,
            },
          };
        } finally {
          await sandbox.kill().catch(() => {});
        }
      } catch (error: any) {
        return { 
          success: false, 
          provider: 'e2b', 
          action: 'run_shell', 
          error: error.message || 'Shell execution failed' 
        };
      }
    },
  },
};

// Get available actions for a provider (static handlers only)
export function getProviderActions(providerId: string): string[] {
  return Object.keys(handlers[providerId] || {});
}

// Get available actions for a provider (includes dynamic providers)
export async function getProviderActionsAsync(providerId: string): Promise<string[]> {
  // First check static handlers
  const staticActions = Object.keys(handlers[providerId] || {});
  if (staticActions.length > 0) {
    return staticActions;
  }
  
  // Then check dynamic providers
  return listDynamicActions(providerId);
}

// Get all connected providers with their actions (static handlers only)
export function getConnectedProviders(): { provider: string; actions: string[] }[] {
  return Object.entries(handlers).map(([provider, actions]) => ({
    provider,
    actions: Object.keys(actions),
  }));
}

// Execute an API call
export async function executeAPICall(
  providerId: string, 
  action: string, 
  params: Record<string, any>,
  userId?: string,
  customerKey?: string
): Promise<ExecuteResult> {
  // Check for dynamic (self-service) provider config first
  if (userId) {
    const isDynamic = await hasDynamicConfig(providerId);
    if (isDynamic) {
      const dynamicResult = await executeDynamicAction(providerId, action, params, userId, customerKey);
      return normalizeResponse(dynamicResult);
    }
  }
  
  // Fall back to hardcoded handlers
  // Check if provider exists
  const providerHandlers = handlers[providerId];
  if (!providerHandlers) {
    // Check if it might be a dynamic provider without userId
    const dynamicActions = await listDynamicActions(providerId);
    if (dynamicActions.length > 0) {
      return {
        success: false,
        provider: providerId,
        action,
        error: `Provider '${providerId}' requires userId for dynamic execution. Available actions: ${dynamicActions.join(', ')}`,
      };
    }
    return {
      success: false,
      provider: providerId,
      action,
      error: `Provider '${providerId}' not connected. Available: ${Object.keys(handlers).join(', ')}`,
    };
  }

  // Check if action exists
  const handler = providerHandlers[action];
  if (!handler) {
    return {
      success: false,
      provider: providerId,
      action,
      error: `Action '${action}' not available for ${providerId}. Available: ${Object.keys(providerHandlers).join(', ')}`,
    };
  }

  // Providers that don't require credentials (free/open APIs)
  const NO_CREDS_PROVIDERS = ['coingecko'];
  
  // Get credentials - customer key takes priority, then local secrets, then proxy
  // Set both apiKey and token so it works with different handler patterns (most use apiKey, GitHub uses token)
  let creds = customerKey ? { apiKey: customerKey, api_key: customerKey, token: customerKey, apiSecret: '' } : getCredentials(providerId);
  const usingCustomerKey = !!customerKey;
  
  // For providers that don't need credentials, use empty creds
  if (!creds && NO_CREDS_PROVIDERS.includes(providerId)) {
    creds = { apiKey: '', api_key: '', token: '', apiSecret: '' };
  }
  
  if (!creds) {
    // Try proxy for supported providers
    if (PROXY_PROVIDERS.includes(providerId)) {
      try {
        const proxyResult = await callProxy(providerId, { action, ...params });
        return normalizeResponse({
          success: true,
          provider: providerId,
          action,
          data: proxyResult,
        });
      } catch (e: any) {
        return {
          success: false,
          provider: providerId,
          action,
          error: e.message || 'Proxy call failed',
        };
      }
    }
    return {
      success: false,
      provider: providerId,
      action,
      error: `No credentials configured for ${providerId}. Set up ~/.secrets/${providerId}.env`,
    };
  }

  // Execute and normalize response
  try {
    const result = await handler(params, creds);
    return normalizeResponse(result);
  } catch (error: any) {
    return {
      success: false,
      provider: providerId,
      action,
      error: error.message || 'Unknown error',
    };
  }
}
